### ISSUE TITLE
findObject only considers the first 1000 items, with no way to paginate

### ISSUE THREAD

**Issue by MattIPv4** [algolia/algoliasearch-client-javascript#1060]
**Describe the bug 🐛**

When using findObject, if the object is not found in the first 1000 items, a not found error is thrown.

No additional data is output, so it is impossible to paginate to continue trying to find this object yourself as there is no context given for what page you are on or how many pages are left.

**To Reproduce 🔍**

1. Create an index with more than 1000 items.
2. Use findObject with criteria that will match an item past the 1000th position in the index.
3. Observe the error thrown by findObject and the lack of any other data outputted.

This behaviour can currently be seen on our WIP new cdnjs site, which is attempting to find the Algolia entry as part of rendering the library page (see console): https://cdnjs.dev/libraries/hi-sven

Relevant source: https://github.com/cdnjs/static-website/blob/e42ed16e0966cd47787bdeaaded6f772b2df47b1/src/util/get_library.js#L11-L22

**Expected behavior 💭**

Either:

1. Automatically, internally, continues searching through the entire index before throwing the error.

Or:

2. When the error is thrown, include pagination data so the end-user can continue searching on the next page themselves.

**Screenshots 🖥**

<img width="612" alt="image" src="https://user-images.githubusercontent.com/12371363/76209057-df0a4f80-61f8-11ea-8aa8-c3e8725607bc.png">

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/12371363/76209188-31e40700-61f9-11ea-99d3-55369034273b.png">

**Comment by nunomaduro** [comment]
@MattIPv4 By default, the `findObject` only search on the first 1000 items. If you want the `findObject` to keep search on the next pages, you need to use the `paginate: true` option.

```
  const data = await index.findObject(hit => hit.name === name, { paginate: true }).catch((e) => {
      console.log('Caught error:', e);
  });
```

**Comment by MattIPv4** [comment]
Hey @nunomaduro,

I added in the paginate option and the behaviour is identical still?

The docs state that the default value for this is true, which is why I didn't provide this initially and why I created the report: https://www.algolia.com/doc/api-reference/api-methods/find-object/#parameters

```
const algolia = async name => {
    const hits = [];
    const data = await index.findObject(hit => {
        hits.push(hit);
        return hit.name === name;
    }, { paginate: true }).catch((e) => {
        console.log('Caught error:', e);
    });
    console.log('Promise result:', data);
    console.log('Hits checked:', hits.length, hits);
    return data && data.object ? data.object : {};
};
```

<img width="615" alt="image" src="https://user-images.githubusercontent.com/12371363/76230464-ab8cec80-621b-11ea-889d-815eb724caad.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/12371363/76230484-b051a080-621b-11ea-9df9-f03c6a0ec467.png">

**Comment by nunomaduro** [comment]
I may need to have access to your use case, and your application. Since this question is not a actual bug, can you contact algolia using : `support@algolia.com`? Thanks!
