### ISSUE TITLE
Ensure correct serialization of searchSynonyms' type query parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1069]
When performing a `index.searchSynonyms()` call, a [`type` query
parameter](https://www.algolia.com/doc/rest-api/search/#method-param-type) can
be passed to restrict the type(s) of synonyms one wants to search for.

@maxiloc reported us that the Java implementation is accepting an array of
strings for this parameter. However, the engine only accepts a comma-separated
string for this. We then need to double check the implementation of the
serialization of this parameter and provide a fix if needed.

**Comment by Haroenv** [comment]
type is a string for JS, if you pass an array it would indeed serialise wrong, but since that's not the right type there's no issue :)

**Comment by nunomaduro** [comment]
Thanks for validating this @Haroenv .
