### ISSUE TITLE
Ensure secured API key param `restrictSources` only accepts string

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1071]
When generating secured API keys, an optional [restrictSources](https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/#method-param-restrictsources)
parameter can be used as a string (such as `"192.168.1.0"` or
`"192.168.1.0/24"`). We discovered that some API clients wrongly accept other
types (such a list of strings, etc.) which is wrong.

Could you make sure that `restrictSources` only accepts string as a valid type
as a secured API keys parameter?

**Comment by Haroenv** [comment]
yes, it's only a  string

**Comment by nunomaduro** [comment]
Thanks for validating this @Haroenv .
