### ISSUE TITLE
Ensure correcty tying of API key's restrictIndices parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1076]
The `restrictIndices` of API keys should be typed as:

 - an array of strings OR
 - a comma-separated string

Both format should be handled at serialization/deserialization time.

**Comment by Haroenv** [comment]
duplicate of https://github.com/algolia/algoliasearch-client-javascript/issues/1071, only string is accepted

**Comment by aseure** [comment]
Sorry about the duplicate @Haroenv, I mixed things up with all the pending issues we had recently. Thanks for noticing.

**Comment by aseure** [comment]
@Haroenv I'm reopening since #1071 is about `restrictSources` while this issue is about `restrictIndices` (and the types are different).

**Comment by Haroenv** [comment]
Ah good call, since it  allows an array  here, which for consistency should also be just a string https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/client-search/src/types/SecuredApiKeyRestrictions.ts#L12

**Comment by aseure** [comment]
Thanks for checking @Haroenv. Does it mean that both types are indeed accepted? Our concern with this issue was really about the possibility that some users may pass restrictIndices either as a coma-separated string or as an array in the past, and we want both format to be accepted when generating the secured API key. So do you confirm?

**Comment by Haroenv** [comment]
We stringify the parameters here: 

https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/client-search/src/methods/client/generateSecuredApiKey.ts#L8

which uses this:

https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/transporter/src/serializer.ts#L22-L35

And thus is left as-is, and will accept any object
