### ISSUE TITLE
Ensure correcty tying of API key's restrictSources parameter

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1077]
The `restrictSources` of API keys should be typed as:

 - a comma-separated string

This parameter does **not** support array of strings as a valid type.

**Comment by aseure** [comment]
I assumed this was closed because of duplication of https://github.com/algolia/algoliasearch-client-javascript/issues/1071?

**Comment by Haroenv** [comment]
No, closed, because it's a string: https://github.com/algolia/algoliasearch-client-javascript/blob/e6dec843932bdfaac13ffa1e0a11964975499078/packages/client-search/src/types/SecuredApiKeyRestrictions.ts#L17
