### ISSUE TITLE
TypeScript Guide

### ISSUE THREAD

**Issue by shadow1349** [algolia/algoliasearch-client-javascript#1079]
I'm currently trying to migrate from using @types/algoliasearch to using algoliasearch@4.1.0 (from 3.35.1).

I was using a generic class to handle all interactions with algolia in my project and to do that I needed to access the QueryParameters interface. Here is an example

```typescript
import algoliasearch, { SearchIndex } from 'algoliasearch';

export class AlgoliaSearch {
  private index: SearchIndex;

  constructor(index: SearchIndex) {
    this.index = index;
  }

  // Cannot access RequestOptions or SearchOptions
  search<T>(params: RequestOptions & SearchOptions) {
    return this.index.search<T>(params);
  }
}
```

Only after looking through your type definitions did I realize that I had to install 2 different packages: `@algolia/cient-search` and `@algolia/transporter` for the right types.

Is there any way you guys can put up a TypeScript guide?

Thanks!

**Comment by shadow1349** [comment]
I would also be happy to spend some time to help contribute to the guide as well, there are just a lot of gotchas when using algoliaSearch >= 4.0 with TypeScript that I have been running into

**Comment by nunomaduro** [comment]
Exporting all types from the `algoliasearch` would fix your problem? https://github.com/algolia/algoliasearch-client-javascript/issues/1080

**Comment by shadow1349** [comment]
RequestOptions is only available as part of the @algolia/transporter package as well as SearchOptions is only available from @algolia/client-search. When I tried to export those types from algoliasearch they aren't directly exported so they can't be found

**Comment by nunomaduro** [comment]
@shadow1349 Got! So indeed, if we re-export all the types from `algoliasearch`, that would fix your problem. So let's consider this issue, a duplicated of #1080.

Maybe you can help us there?
