### ISSUE TITLE
proposal: re-exports all types in `algoliasearch`

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-javascript#1080]
Today, types like `SearchOptions`, or `Rule` are not exported by the `algoliasearch` package. 

People are actually importing them directly from the modular packages:

```
import { SearchOptions } from '@algolia/client-search';
```

**Solution**: re-exports all types, and types from modular packages, in `algoliasearch` and configure API Extrator to warn us about non exported types.

**Comment by Haroenv** [comment]
Yes, we should make sure that you don't need to reach  into implementation details to be able to fully use the types (they aren't always inferred if you wrap the client e.g.)

**Comment by bodinsamuel** [comment]
Yes please

**Comment by pinkfish** [comment]
+1, this took me quite a while to work out why I couldn't import things directly from algoiasearch.

**Comment by wiesson** [comment]
Any update to this topic?

**Comment by Haroenv** [comment]
Reopening the pull request, I lost track of it. Thanks @wiesson !

**Comment by wiesson** [comment]
@Haroenv no problem :) 

I kind of solved it for now:

```Typescript
import type { RequestOptions } from "@algolia/transporter";
import type { SearchOptions } from "@algolia/client-search";

// hacky attempt to remove readonly
type Mutable<T> = { -readonly [P in keyof T]: T[P] };

(...)

let requestOptions: Partial<RequestOptions & Mutable<SearchOptions>> = {
  hitsPerPage: resultsPerPage,
};

if (page) {
  requestOptions.page = page;
}

if (lat && lng) {
  requestOptions.aroundLatLng = `${lat}, ${lng}`;
  requestOptions.aroundRadius =  radius * 1000;
}

if (boundingBox) {
  requestOptions.insideBoundingBox = [boundingBox];
}

const { hits, nbHits, page, nbPages } = await searchIndex.search(q, requestOptions);

(...)
```

**Comment by Kraloz** [comment]
Any workaround on this issue?

**Comment by Haroenv** [comment]
All types are exported, but from other packages, like @algolia/client-search, so you can look into the reference and find the import that way.

**Comment by shortcuts** [comment]
done in v4

**Comment by ryanjwilke** [comment]
@shortcuts Is this issue also related to this error that I'm getting locally and in CI? This started happening recently and it's a bit confusing as to what might have triggered this issue.

Here's the log output I'm seeing from CI:
```
(node:1783) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///home/runner/work/cypress.io/cypress.io/node_modules/algoliasearch/dist/node.js:54
import { EventType } from "@algolia/client-personalization";
         ^^^^^^^^^
SyntaxError: The requested module '@algolia/client-personalization' does not provide an export named 'EventType'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:146:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:22[9](https://github.com/cypress-io/cypress.io/actions/runs/11487393453/job/31972113009#step:6:10):5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)
```

It would appear that this issue is stemming from inside the package, but I could be wrong.
