### ISSUE TITLE
Search Results hits and nbhits not accurate

### ISSUE THREAD

**Issue by SirPhemmiey** [algolia/algoliasearch-client-javascript#1090]
Hi guys, 

Please i have a little issue. I don't know if it's a bug or something. 

In my Algolia search, results.hits.length is 20 while results.nbhits is more than 20. Why is that please?

Thanks in advance.

**Comment by Haroenv** [comment]
nbHits is the total number of hits for all pages, hits is the list for just one page @SirPhemmiey

**Comment by SirPhemmiey** [comment]
Thanks for clarifying @Haroenv . So how do I get all the results?

**Comment by Haroenv** [comment]
You can get all the results by using browse: https://www.algolia.com/doc/api-reference/api-methods/browse/?language=javascript
