### ISSUE TITLE
feat(query): adds naturalLanguages parameter

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-javascript#1107]
**Summary**

The `naturalLanguages` parameter provide users with an easy way to implement voice and natural languages best practices.

The parameter is a list of languages, which applies the following settings:

- `removeStopWords` to the naturalLanguages param value
- `ignorePlural`s to the naturalLanguages param value
- `removeWordsIfNoResults` to allOptional
- adds `analytics tag` of naturalLanguages
- adds `query rule context` of naturalLanguages

The parameter is list of string. Example: `naturalLanguages=["de","fr"]`

**Comment by Haroenv** [comment]
is there a list of supported iso strings?

**Comment by nunomaduro** [comment]
To make it ready for all languages that may appear in the future I would go for a list of strings here.

**Comment by Ant-hem** [comment]
The list is the same as the one for `removeStopWords`: https://www.algolia.com/doc/api-reference/api-parameters/removeStopWords/#usage-notes

**Comment by aseure** [comment]
@nunomaduro I let you check the `release` box when JavaScript will get released (the change is on `master` but hasn't been released yet).

@VladislavFitz I let you take care of checking the boxes and updating the doc if you already added it to the next major release for the Swift client.
