### ISSUE TITLE
Clarify status of `addObject` and `addObjects` methods on SearchIndex

### ISSUE THREAD

**Issue by kimroen** [algolia/algoliasearch-client-javascript#1121]
We are trying to upgrade our usage of this library to the latest version in the 4 series from version `3.35.1`, and ran into the following error when compiling the TypeScript:

```
Property 'addObject' does not exist on type 'SearchIndex'.
```

I did not see anything in [the migration guide](https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/#the-search-index) regarding `addObject` and `addObjects` being removed, but I have seen some PRs and issues in this repository mentioning it.

It's also noteworthy that the ["Add object" documentation](https://www.algolia.com/doc/api-reference/api-methods/add-objects/) no longer seems to mention `addObject` - it uses `saveObject` instead.

What's going on here? Is it just missing from the types, or is it actually removed? If it's removed, what happened to the migration guide, and how should we be migrating?

Thanks!

**Comment by Haroenv** [comment]
The replacement is `saveObjects(..., { autoGenerateObjectIDIfNotExist: true })`, but this indeed doesn't seem to be mentioned in the migration guide, which is a mistake, cc @nunomaduro 

We'll update the migration guide, thanks

**Comment by nunomaduro** [comment]
This migration guide was being updated: https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/#the-addobject-and-addobjects-methods.
