### ISSUE TITLE
Expose rule.consequence.promote.objectIDs string array

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1155]
On top of the existing `objectID` (singular) string field, a new `objectIDs`
(plural) string array field is now be exposed in the `rule.consequence.promote`
Rule object representation. This lets the user easily promote a full group of
objects without letting some priority conflicts to shift some objects at the end
of the promoted object list.

**Comment by Haroenv** [comment]
looks like we only accept `objectID` (singular) now: https://github.com/algolia/algoliasearch-client-javascript/blob/master/packages/client-search/src/types/Rule.ts#L84

**Comment by nunomaduro** [comment]
This feature can't be merged yet: algolia/algoliasearch-client-specs-internal#118.
