### ISSUE TITLE
Invalid Application-ID or API key

### ISSUE THREAD

**Issue by KevinOl** [algolia/algoliasearch-client-javascript#1157]
algoliasearch version 4.2.0

I am using it on a search result page in order to retrieve and show the hits. However, whenever I load the page or refresh it, I get a 403 forbidden message for the request along side this 'Invalid Application-ID or API key'.

It is not always happening but just 'random'. At first I used the one provided in dashboard but then decided to create a custom api search key. Same. I did not restrict access to it. eg. number of call per hour...

Not sure what to do. This is not good if a user has to refresh the page a couple of times before hopefully seeing the results ;)

**Comment by KevinOl** [comment]
Still experiencing this issue...idea? help? anybody?

**Comment by nunomaduro** [comment]
Can you share the environment? Also, when you have the error, can you share the exact error object?

**Comment by KevinOl** [comment]
Hi,

actually I think I found out why it is not working.
The request to algolia is intercepted by Ghostery and the x-algolia-application-id is modified.
I tried in another browser without ad blockers installed and it fetches without errors.
