### ISSUE TITLE
migration guide (v3=>v4) is missing addObjects => saveObjects

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [algolia/algoliasearch-client-javascript#1159]
While migrating from v3 to v4, I was looking at the [migration guide](https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/#renamed-methods-1)

I think `addObjects` doesn't exist anymore on v4, and is renamed to [`saveObjects`](https://www.algolia.com/doc/api-reference/api-methods/add-objects/), but it's missing from the guide.

**Comment by Haroenv** [comment]
That's true, the mention of `addObject(obj)` -> `saveObject(obj, { autoGenerateObjectIDIfNotExist: true })` needs to be documented.

**Comment by Haroenv** [comment]
The docs now have a new section explaining this, thanks for catching @AbdelrahmanHafez!
