### ISSUE TITLE
Disable indexing

### ISSUE THREAD

**Issue by malimccalla** [algolia/algoliasearch-client-javascript#1168]
I'm unable to disable my algolia requests in a test environment. Is it currently possible to disable indexing for specific environments? I stumbled upon this in the docs but it only shows instructions for Ruby https://www.algolia.com/doc/framework-integration/rails/advanced/dev-and-testing/?language=ruby#disabling-indexing

It would be great If i could do something like this

```ts
const algoliaClient = algoliasearch(algoliaAppId, algoliaAppSecret, { sandboxMode: process.env.NODE_ENV === 'test' });
```

**Comment by Haroenv** [comment]
Sorry this is a feature we’ve so far only heard interest for in ruby/rails. For now I’d suggest you wrap the client in a creation function which either returns a stub of the methods you need, either the real ones based on the disableIndexing command.

**Comment by malimccalla** [comment]
Ok thanks. Will close this and just register my interest in this feature.

**Comment by Haroenv** [comment]
Thanks indeed for opening this issue, this way it's written down clearly what you could use the feature for, if this gets investigated in the future
