### ISSUE TITLE
Type error on typescripts

### ISSUE THREAD

**Issue by mimiqkz** [algolia/algoliasearch-client-javascript#1169]
```
index
  .search(name, {
      attributesToRetrieve: ['name', 'manufactor'],
    })
    .then(({hits}) => {
        return hits
    })
```
I got error on type when trying to fetch data.
Error when I try to put this into a state is:
`Type 'ObjectWithObjectID' is missing the following properties from type 'ProductProps': name, manufactor `

The state is declared as follow:
```
export interface ProductProps {
  name: string
  manufactor: string
  objectID: string
}

 const [products, setProducts] = useState<ProductProps[]>([])
```

Even when I tried to use `import { ObjectWithObjectID } from "@algolia/client-search"`
I still got error as I can't read the field (`name, manufactor`) from it, because it gives back only the `objectID`. And when I tried to extends the `ProductProps` with `ObjectWithObjectID` and take out the `objectID` from it. It still doesn't work. This is very annoying

**Comment by nunomaduro** [comment]
Can you provide me the entire snippet, with the exact line is failing?

**Comment by mimiqkz** [comment]
```
export function getSearch(name: string) {
  let products
  try {
    if (ALGOLIA_ID && ALGOLIA_SEARCH_KEY) {
      const client = algoliasearch(ALGOLIA_ID, ALGOLIA_SEARCH_KEY)
      const index = client.initIndex('products')
      products = index.search(name).then(({hits}) => {
        return hits
      })
    }
  } catch (err) {
    console.error(err)
  }
  return products
}
```

Note that the code below failed on extended from` import { ObjectWithObjectID } from "@algolia/client-search"` as well

```
export interface ProductProps {
  name: string
  manufactor: string
  objectID: string // if it's extended then I take this out
}
```

`  const [products, setProducts] = useState<ProductProps[]>([])`
```
const onSearch = async(value: string) => {
    const result = await getSearch(value)
    if (result) {
      setProducts(result) // error here
      setShowResult(true)
    }
  }
```
Error msg (regardless of using extends or not)
```
Argument of type 'ObjectWithObjectID[]' is not assignable to parameter of type 'SetStateAction<ProductProps[]>'.
  Type 'ObjectWithObjectID[]' is not assignable to type 'ProductProps[]'.
    Type 'ObjectWithObjectID' is missing the following properties from type 'ProductProps': name, manufactor
```

**Comment by mimiqkz** [comment]
https://codesandbox.io/s/wild-fire-rv5o5?file=/src/App.ts

The code has been solved as above
