### ISSUE TITLE
feat: built-in operations `IncrementFrom` and `IncrementSet`

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-javascript#1172]
**TL DR: Update API Client types so both `IncrementFrom` and `IncrementSet` can be used for built-in operations.**

The built-in operations `IncrementFrom` and `IncrementSet` guarantee that the update will be idempotent, as those operations will force the update to be rejected if applied more than once.

```js
    index.partialUpdateObject({
      version: {
        _operation: 'IncrementFrom',
        value: 2,
      },
      objectID: 'myID',
    })
    .then(({ objectIDs }) => {
      console.log(objectIDs);
    });
```

Internal specs issue: [#127](https://github.com/algolia/algoliasearch-client-specs-internal/issues/127)

**Comment by aseure** [comment]
Closed because the operations are not statically-typed.
