### ISSUE TITLE
Implement retry until success for restore_api_key() call in CTS test

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#1175]
Because of the way Algolia is designed, performing a `restoreApiKey` may not
succeed because the previous `deleteApiKey` takes some time to get propagated
to all Algolia servers, giving us the following response: `[404] Key already
exists`.

To prevent that, we need to change the `testApiKeys` CTS test, if implemented,
to retry even on `[404] Key already exists` response.

**Comment by Haroenv** [comment]
I think this already is implemented here: https://github.com/algolia/algoliasearch-client-javascript/blob/c14f631abd111b822ef92d8d25b321c325959e44/packages/client-search/src/__tests__/integration/api-keys.test.ts#L65-L75

**Comment by aseure** [comment]
Thanks for checking @Haroenv 👍 Sounds good to me. Closing it!
