### ISSUE TITLE
multipleBatch errors with a timeout

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-javascript#1181]
Hello friends,

I'm having timeout error (`Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.`) when trying to execute a batch of operations. I don't think the host is really unreachable (it works for other operations), but that something is wrong with my batch.

I made a repro repo here: https://github.com/pixelastic/algolia-batch-issue. Just run `yarn run test` and it will try to batch the content of the `input.json` and display the error when caught

My guess so far is that my batch is taking too long to execute on the server, so the client considers it a timeout error. I tried investigating through debug statements in `algoliasearch` and `@algolia/client-search` in my `node_modules`, and it seems that the `.wait()` on `multipleBatch` is never called (ie. it errors before that).

My batch is only 3.2Mb, so I'm surprised that it takes that long to execute, though.

I tried splitting the batch in smaller chunks, and running them in parallel and I seemed to have a better luck that way, but not even reliably. I'm looking to understand the cause of the initial issue so I can tailor the number of chunks and parallel requests.

I also tried increasing the write timeout to 60s instead of the default 30, but I don't think it had any effect. I could set the timeout smaller (like 2s) and see it fail earlier, but setting it higher didn't seem like I could really make it go above 30s.

Any help would be appreciated

_Note that because in this specific case I only have an array of `addObject` I could use the `addObjects` method directly and not bother with a batch, but I would still be very interested in understanding the limitations of the `multipleBatch` method_

**Comment by Haroenv** [comment]
Is this an issue which already existed in v3, or is it particular to v4? We did change implementations indeed

**Comment by pixelastic** [comment]
I haven't tried the exact same batch in v3 and v4, but I never had batch-related issues in v3. But I was manually grabbing the `taskID` and waiting for it in v3

**Comment by Haroenv** [comment]
Hmm, if the issue doesn't happen on v3 on the same index, then it's not related to the taskId being > 2^53, which is happening in some very high-frequency indices now unfortunately.

**Comment by pixelastic** [comment]
I'll try to rewrite the code with v3, see if the same batch works then. Could you try to run my repro repo on your end on your own app to check if it's something related to my account, or if the error can be reproduced reliably.

As for "high-frequency" index, what do you mean? I'm not making a lot of requests on this index, only this one batch request that fails reliably on my side.

How can we move forward? Downgrading to v3 is not really an option.

**Comment by Haroenv** [comment]
So I tried it out, and for me your snippet works, although I indeed tried on a smaller index, do you think you could give personification access so I can try out yours?

**Comment by pixelastic** [comment]
You should already have access to my account, can you confirm?

What do you mean by smaller index? I do clear the `gamemaster_minipainting_manifest_tmp` index each time before trying to run the batch, so the index should be empty. Is the total size of all indices on my app relevant here?

**Comment by pixelastic** [comment]
I tried the code with the v3 client, and it fails as well: https://github.com/pixelastic/algolia-batch-issue/blob/v3/run.js

Here is the relevant code:

```js
const appId = 'O3F8QXYK6R';
const apiKey = process.env.ALGOLIA_API_KEY;

const client = algoliasearch(appId, apiKey);
const batchContent = await readJson('./input.json');
const indexName = "gamemaster_minipainting_manifest_tmp"
const index = client.initIndex(indexName)

const response = await client.batch(batchContent);
console.info(response);
const taskID = response.taskID[indexName]
console.info(taskID);
await index.waitTask(taskID);
```

I'm not even getting past the `client.batch` call (it throw an error), meaning that I never get a taskID to wait for.

Considering that it's failing on both v3 and v4 for me but working for you, I would be inclined to think it has to do with the account.

**Comment by pixelastic** [comment]
@Haroenv If it's related to the taskID overflowing, do you know of any workaround? I have no idea how to move forward from here.

**Comment by Haroenv** [comment]
Unfortunately we don't have a workaround right now, except _not_ using waitTask, since the task is not representable in JavaScript. We are working on a solution to return the taskID as a string, but that needs work on the engine-side.

Alternatively I guess it would be possible to write a custom requester which transforms taskID to a string _before_ deserialising the JSON, but that would not be straightforward, and likely inefficient.

**Comment by pixelastic** [comment]
I see, thanks for the information. I'll wait for the API to be fixed I guess, I don't think I can reliably skip the `waitTask` part in `algolia-indexing`

**Comment by Haroenv** [comment]
If we want to find a future-proof way of deserialising non-json, I think the relevant places would be:

https://github.com/algolia/algoliasearch-client-javascript/blob/217ba89e666d56aeead3848da23be215db18e65d/packages/transporter/src/concerns/retryableRequest.ts#L97

(and then walking all the way up to make that configurable):

https://github.com/algolia/algoliasearch-client-javascript/blob/217ba89e666d56aeead3848da23be215db18e65d/packages/transporter/src/concerns/retryableRequest.ts#L23-L28

https://github.com/algolia/algoliasearch-client-javascript/blob/075b9fa2eeb83b12700d7c9c402f0520ab04681c/packages/transporter/src/createTransporter.ts#L143-L148

https://github.com/algolia/algoliasearch-client-javascript/blob/075b9fa2eeb83b12700d7c9c402f0520ab04681c/packages/transporter/src/createTransporter.ts#L57-L62

Then allowing people to add something to transporter (their deserialise function)
https://github.com/algolia/algoliasearch-client-javascript/blob/075b9fa2eeb83b12700d7c9c402f0520ab04681c/packages/transporter/src/createTransporter.ts#L26

https://github.com/algolia/algoliasearch-client-javascript/blob/ef365fbd52ce479e902deaa6ac47969065cfcffd/packages/client-search/src/createSearchClient.ts#L25

This is slightly similar to #1173 to allow more customisation.

**Comment by pixelastic** [comment]
Do you think this int to string conversion is more likely to happen in the clients than on the API?

The fact that my code can randomly break because some taskID returned by the server will overflow seems like a major breaking issue to me, but I couldn't find any mention of it in issues, documentation or the community. Which makes me wonder if I just was very unlucky, or if I'm right to freak out? :)

**Comment by Haroenv** [comment]
It's a pretty big issue, but since not many people use waitTask in general, and it only happens on very full clusters (IIRC) and for people indexing in JS, it's not actually affecting that many people. 

Therefore it might still take a bit before this will be fully fixed in the engine, I'll definitely keep you updated though

**Comment by pixelastic** [comment]
Oh I see, thanks. The trio JS + waitTask + old cluster is actually very much every project I do, though, so I'm eagerly waiting for any update on that. Thanks!

**Comment by Haroenv** [comment]
taskIDs now will be < 2^40 on the engine in all cases, thanks for reporting and pushing this to the top of the queue :)

**Comment by pixelastic** [comment]
Yay \o/ always here to find weird engine bugs!

Please, send my thanks to all the people involved in the fix

**Comment by cmgchess** [comment]
Hi, I'm also getting the same error on the console even though all records have been added to the index successfully. I'm also sending data in small batches (30 records/batch). I'm using `"algoliasearch": "^4.11.0"` . 
Any idea what's causing this?
![algoliaerr](https://user-images.githubusercontent.com/61736812/148689775-2e2a613f-3b3b-4d7f-8729-4955131bea68.PNG)
