### ISSUE TITLE
search parameters query not working anymore

### ISSUE THREAD

**Issue by fnfilho** [algolia/algoliasearch-client-javascript#1187]
Hi there,

so we were using the following code to search:
`await index.search({ query: inputValue,  hitsPerPage: 5 });`

But this is not working anymore after we rebuild it in Node 14. We had to change all use cases for
`await index.search(inputValue, { hitsPerPage: 5 });`

**Comment by Haroenv** [comment]
You probably updated to `algoliasearch` v4 at the same time as updating to node v14. You can see the migration guide here: https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/javascript/#upgrading-from-3351-to-4x

**Comment by fnfilho** [comment]
Got it! Thanks
