### ISSUE TITLE
Add module entry point to algoliasearch package.json

### ISSUE THREAD

**Issue by janosh** [algolia/algoliasearch-client-javascript#1266]
Trying to import `algoliasearch` in a node script inside a project whose `package.json` is `"type": "module"` throws

```
node src/utils/algolia.js
(node:93538) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/janosh/Repos/afara/node_modules/svelte-algolia/src/main.js:2
import algoliasearch from 'algoliasearch'
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Can this be fixed by defining a `module` in `package.json`?

https://github.com/algolia/algoliasearch-client-javascript/blob/cd39284a204a8bf2f6a99220bf96f0298b12c9c5/packages/algoliasearch/package.json#L10-L16

**Comment by Haroenv** [comment]
I've made a demo application here that shows it works: https://github.com/Haroenv/algoliasearch-node-demo

Is it possible you're using Yarn 2? https://github.com/yarnpkg/berry/issues/638

**Comment by janosh** [comment]
@Haroenv Thanks a lot for creating the demo! It must be a problem with how I setup `package.json` in [`svelte-algolia`](https://github.com/janosh/svelte-algolia) then as it's the one that does the [`import algoliasearch from 'algoliasearch'`](https://github.com/janosh/svelte-algolia/blob/2c107d639054085f2bb9e12ebdab2cd26089cd41/src/main.js#L2). Will try to investigate over the weekend.

I'm not using Yarn v2. Still on v1.22.10.

**Comment by janosh** [comment]
Like I said, there was likely an issue in how I setup [`svelte-algolia`](https://github.com/janosh/svelte-algolia) + maybe some rough edges in the `svelte-kit` beta and `adapter-static`. Didn't want to go too deep in researching this as I hate the whole CJS + ESM duality. My solution was to just drop CJS entirely and setup everything for ESM only. Works for me. 😄 

@Haroenv Thanks again for your response.
