### ISSUE TITLE
Which npm package to use?

### ISSUE THREAD

**Issue by dimaqq** [algolia/algoliasearch-client-javascript#1274]
Both of these package point to this github repo:
* https://www.npmjs.com/package/@algolia/client-search
* https://www.npmjs.com/package/algoliasearch

Are they both actually from algolia, is one of them an impostor?

**Comment by Haroenv** [comment]
they are both from algolia, with `algoliasearch` having a slightly simpler API:

```
import algoliaserach from 'algoliasearch/lite' // for browser contexts

algoliasearch('appId', 'apiKey')
```

```
import { createSearchClient, multipleQueries } from '@algolia/client-search';

createSearchClient({ appId, apiKey, methods: { search: multipleQueries }) // etc.
```

Only the algoliasearch API is documented, but it uses client-search internally.

Hope that's clear!
