### ISSUE TITLE
Random 404 errors using index.getObject

### ISSUE THREAD

**Issue by arzola** [algolia/algoliasearch-client-javascript#1277]
Hello

I have been struggling with the following code:

It happens on v3 and v4 libraries

```javascript
books.forEach((book)=>{
try { 
const currentAlgoliaAttrs = await index.getObject(book.objectID)
}catch(e) {
//AlgoliaSearchError: ObjectID does not exist
}
});
```

I got random AlgoliaSearchError: ObjectID does not exist, **even though the object exists**, the call is not idempotent, I got really random 404 errors, do you have a clue or suggestion?

I tried too with promises based code instead of async await and it's the same thing, I read the entire docs and I can't find something related, maybe API throttling?

**Comment by Haroenv** [comment]
Is this something you can reproduce in a sandboxed environment? We have some credentials and basic setup here: https://codesandbox.io/s/github/algolia/create-instantsearch-app/tree/templates/javascript-client

Hope to get to the bottom of this!

**Comment by arzola** [comment]
Thank you for your time, When I do a Sandbox test I discovered it was a race condition on my code, sorry for bother you with this :)

**Comment by Haroenv** [comment]
Glad that it's resolved!
