### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by kamami** [algolia/algoliasearch-client-javascript#1285]
Client can not be installed via: "npm install algoliasearch".
It throws following error:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@algolia%2fclient-personalization - Not found
npm ERR! 404  '@algolia/client-personalization@4.10.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'algoliasearch'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Haroenv** [comment]
Please clear your cache and try again, this happened because client-personalization was a new package that got published at the same time as algoliasearch 4.10.0

If you can still reproduce after that, please leave a comment with a repository that reproduces the issue. I've just tried on a fresh folder, and the install worked

**Comment by kamami** [comment]
I cleared the cache, but still the same error:

PS C:\Users\...\project_ssr> npm cache clean --force
PS C:\Users\...\project_ssr>
PS C:\Users\...\project_ssr> npm cache verify
Cache verified and compressed (~\AppData\Roaming\npm-cache\_cacache):
Content verified: 0 (0 bytes)
Index entries: 0
Finished in 0.014s
PS C:\Users\...\project_ssr>
PS C:\Users\...\project_ssr> npm install algoliasearch
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@algolia%2fclient-personalization - Not found
npm ERR! 404
npm ERR! 404  '@algolia/client-personalization@4.10.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'algoliasearch'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Haroenv** [comment]
Sorry for the misunderstanding here, npm was saying things were public even if they were actually private (and package was explicitly marked as private: false

final resolving of the issue is in https://github.com/algolia/algoliasearch-client-javascript/issues/1286
