### ISSUE TITLE
componentWillMount and componentWillReceiveProps warnings

### ISSUE THREAD

**Issue by ElGecko76** [algolia/algoliasearch-client-javascript#1296]
Hi,

I use the last version of the lib (4.10.3) and there are these warnings which appear in the console.

>   Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move code with side effects to componentDidMount, and set initial state in the constructor.
> * Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: %s AlgoliaConfigure(UnknownComponent), AlgoliaInfiniteHits(InfiniteHits), AlgoliaSearchBox(SearchBox)

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: %s AlgoliaConfigure(UnknownComponent), AlgoliaInfiniteHits(InfiniteHits), AlgoliaSearchBox(SearchBox), CreateInstantSearch, InstantSearch

![image](https://user-images.githubusercontent.com/19478137/125482382-9ab6a5e0-8f7a-496d-a00a-953cdc1f6231.png)

The lib doesn't seem to use state hooks from the latest React versions, is it possible to fix this please?

**Comment by Haroenv** [comment]
This library doesn't use react at all, do you use the 4.10.3 of React InstantSearch instead of the latest (6.12.0) by chance?

**Comment by ElGecko76** [comment]
@Haroenv 

I use theses libs on React Native:

```
"algoliasearch": "^4.10.3",
"react-instantsearch-native": "5.7.0",
```

It's bad?

**Comment by ElGecko76** [comment]
Oops.. Sorry I use a very old version, I updated and my problem is solved

**Comment by Haroenv** [comment]
No problem!
