### ISSUE TITLE
Cannot find module:'@algolia/cache-common'"

### ISSUE THREAD

**Issue by danielkariti** [algolia/algoliasearch-client-javascript#1376]
I have a lambda function in AWS and when I run the server locally everything works perfectly, the usage of algolia is being made inside a service, which is in an endpoint inside my server.
I tried installing @algolia/cache-common and it didn't help either.
Every call that is made to the lambda crashes the entire app because of this error.
is there any way to fix it?
the error is the following:
```{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@algolia/cache-common'\nRequire stack:\n- /opt/nodejs/node_modules/algoliasearch/dist/algoliasearch.cjs.js\n- /opt/nodejs/node_modules/algoliasearch/index.js\n- /var/task/dist/api/v1/services/algolia.service.js\n- /var/task/dist/api/v1/handlers/jobs.handler.js\n- /var/task/dist/api/v1/controllers/jobs.controller.js\n- /var/task/dist/api/v1/v1.routes.js\n- /var/task/dist/api/routes.js\n- /var/task/dist/serverless.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@algolia/cache-common'",
        "Require stack:",
        "- /opt/nodejs/node_modules/algoliasearch/dist/algoliasearch.cjs.js",
        "- /opt/nodejs/node_modules/algoliasearch/index.js",
        "- /var/task/dist/api/v1/services/algolia.service.js",
        "- /var/task/dist/api/v1/handlers/jobs.handler.js",
        "- /var/task/dist/api/v1/controllers/jobs.controller.js",
        "- /var/task/dist/api/v1/v1.routes.js",
        "- /var/task/dist/api/routes.js",
        "- /var/task/dist/serverless.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"

    ]
}
 ```

the way I use the algolia is like the following: 

const applicationId: any = config.get("ALGOLIA.APPLICATION_ID");
const apiKey: any = config.get("ALGOLIA.ADMIN_API_KEY");
const client = algoliasearch(applicationId, apiKey);
const index = client.initIndex("my-actual-index");

note (tl:dr): everything works locally but not in lambda.

**Comment by Haroenv** [comment]
hmm, that module exists on npm, so I'm not sure what could cause the issue. Are you possibly mixing v3 and v4 of algoliasearch? Can you reproduce this issue in a standalone GitHub repo (without AWS), or does it only happen on a lambda?

**Comment by danielkariti** [comment]
It only happens on lambda

**Comment by Haroenv** [comment]
I wonder if this is a bug related to the zipping then, could you check if the module is available locally for you, and if it's also in the zip sent to lambda? some debugging tips: https://stackoverflow.com/questions/30678348/aws-lambda-cannot-find-module https://bobbyhadz.com/blog/aws-lambda-cannot-find-module

**Comment by danielkariti** [comment]
You are correct, I have uploaded the modules in a wrong way. missed the algolia dependencies.
