### ISSUE TITLE
getting 'Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.' but data getting ingested

### ISSUE THREAD

**Issue by cmgchess** [algolia/algoliasearch-client-javascript#1380]
Hi,
 I'm getting the error ` 'Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.' `on the console even though all records have been added to the index successfully it seems (the record count is same as in the `.json` data file). The `.json` file is not even 200KB with 220 records. I'm also sending data in small batches (30 records/batch).  
I'm using `"algoliasearch": "^4.11.0"` .
Any idea what's causing this?
Thanks.

![algoliaerr](https://user-images.githubusercontent.com/61736812/148718726-e31fb7f2-8c46-465f-85ea-4e6d2778a54d.PNG)

**Comment by Haroenv** [comment]
This error means that the servers could not be contacted, and usually is caused by a network problem. If you can reproduce that consistently, please contact support@algolia.com

**Comment by PedroS11** [comment]
I'm getting the same issue if I create my own algoliasearch client with a different requester (request-http-node) and I can't understand why
`const algoliasearch = algoliasearch(
   'YourApplicationID',
   'YourSearchOnlyAPIKey',
{
   requester: createBrowserXhrRequester()
});`

**Comment by bsubedi26** [comment]
Same issue here. We started receiving this error after updating from version `3.32.0` to `4.14.2`

The error message has an extra number suffixed to the application id - example below:

```
{
            "message": "Opening request to https://{app_id}-1.algolianet.com/1/indexes/{index}/query",
}
{
            "message": "Opening request to https://{app_id}-2.algolianet.com/1/indexes/{index}/query",
}
```

**Comment by bodinsamuel** [comment]
Unreachable hosts error is related to your network not the client itself
please see this ticket for resolution https://support.algolia.com/hc/en-us/articles/5473401113745

**Comment by kuwabararikuya** [comment]
@eagor 
I got the same issue, it's not Algolia's Issue but Next.js's issue.
We need to add NEXT_PUBLIC_ when using environment-variables from browser

https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser

**Comment by SilverFoxA** [comment]
```javascript
import algoliasearch from 'algoliasearch';
import {getMongoDb, mongoDb} from "../../config/mongoDb";
import {Promise} from "q";

const MongoClient = require('mongodb').MongoClient;

const _ = require('underscore')

const client = algoliasearch('...', '...');
const index = client.initIndex('products');


MongoClient.connect(mongoDb.url.production, {
    promiseLibrary: Promise,
    poolSize: 100,
    useNewUrlParser: true,
    useUnifiedTopology: true
}, async (err, db) => {
    if (err)
        throw err
    const oDb = db.db('backend');

    // Products
    let products = await oDb.collection("products").aggregate([
        {
            $match: {
                'status': true
            }
        }
    ]).toArray();

    console.log("Product ", products.length)

    let chunks = [];
    Promise.all(await products.map(p => {
        chunks.push(p);
        if (chunks.length > 500) {
            index.saveObjects(chunks, {autoGenerateObjectIDIfNotExist: true}).wait().then(i => {
                console.log("batch done")
            }).catch(reason => {
                console.log(reason)
            })
            chunks = [];
        }
    }))

    // last batch
    if (chunks.length > 0) {
        index.saveObjects(chunks, {autoGenerateObjectIDIfNotExist: true}).wait().then(x => {
            console.log("Done")
        }).catch(reason => {
            console.log(reason)
        })
    }
});
```

Please note that `app_id` and `admin_api_key` are correct and not interchanged.

The fact that I can connect and query my production server means the network certainly doesn't have any issues. Are we still labelling this as client side issue?

**Here's my console output**
![Screenshot 2023-05-18 at 9 44 47 AM](https://github.com/algolia/algoliasearch-client-javascript/assets/6983070/20049f4b-aead-4f63-82c6-1b00e09b68b3)

**Response from support**
![Screenshot 2023-05-18 at 9 46 40 AM](https://github.com/algolia/algoliasearch-client-javascript/assets/6983070/907f3a09-f843-44e3-896a-1b3b8c670945)

**Comment by laurajaime** [comment]
> You might want to check if your **Content Security Policy** is blocking algolia - That's what caused this issue for me.

you saved my day!!!
