### ISSUE TITLE
Retrieve `searchableAttributes` on client side to calculate `best match attribute`.

### ISSUE THREAD

**Issue by AbdallahAbis** [algolia/algoliasearch-client-javascript#1385]
The docs for `getRankingInfo` state: 
 - To determine which attribute within the list of searchableAttributes was the best match, you need to divide firstMatchedWord number by 1000.

Is there a way I can retrieve the list of `searchableAttributes` using `index.search` so I can calculate `best match attribute`, I have checked the docs but I don't see that it's possible.

**Comment by Haroenv** [comment]
You can't know the searchableAttributes in the search response, as that could expose parts of the index (settings), which aren't meant for public consumption using a search api key. However for debugging purposes you can use getSettings() to retrieve the searchable attributes.

If you are planning to use this for non-development/debug purposes, I'd recommend you do the getSettings call backend and embed the searchableAttributes in the html page, to avoid giving people complete settings access by exposing an non-search key.

I'll close this issue now however, as it's a more general question and not really related to the JS api client. Feel free to follow-up if I was unclear somehow

Hope that helps!
