### ISSUE TITLE
Install the algolisearch using yarn doesn't work

### ISSUE THREAD

**Issue by HubertRyanOfficial** [algolia/algoliasearch-client-javascript#1389]
Hey guys, I don't why, but I can't install the algoliasearch with yarn. I'm using the yarn to everything in my project, so I don't know what's going on?

❯ yarn add algoliasearch
yarn add v1.19.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: fetch --tags
Directory: C:\Users\Neander\AppData\Local\Yarn\Cache\v6\.tmp\9ee0a27027db93fad58e8dddb6592fbc
Output:
fatal: not a git repository (or any of the parent directories): .git
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
Neander@DESKTOP-TQA0A0B  ~\Desktop\Projetos\tapedin\App(Original)   feat/improvingSearc

**Comment by HubertRyanOfficial** [comment]
Hey guys, I resolved the problem cleaning up the yarn cache, just run `yarn cache clean`

**Comment by Haroenv** [comment]
This must have been a temporary problem, but glad it's resolved without our interaction.

Have a great time implementing Algolia!
