### ISSUE TITLE
is it possible to set `responseFields` with `algoliasearch(APP,KEY).search(requestsObject)`

### ISSUE THREAD

**Issue by cmgchess** [algolia/algoliasearch-client-javascript#1404]
https://codepen.io/cmgchess/pen/oNGmqWE

is it possible to set the response field via this setup. the `requests` is what is generated and sent from the algoliasearch-helper library
```javascript
const algoliasearch = require('algoliasearch');
const client = algoliasearch(ALGOLIA_APP,ALGOLIA_KEY);
const responseFields = ['hits','facets','nbHits','page','nbPages'];

//inside async function 
results = await client.search(requests,{responseFields}); //didn't work

```

the docs show it for the `initIndex` and then `search`  but not for the above setup in https://www.algolia.com/doc/api-reference/api-parameters/responseFields/

is there a way to set `responseFields` for the above setup or should i write my own logic to remove fields

**Comment by Haroenv** [comment]
responseFields is a search parameter, so it's part of `requests[number].params`. I don't know what your requests array is, but inside it you need to add `responseFields` to the params object.

```js
algoliasearch('','').search([{indexName, params: {responseFields: []}}])
```

**Comment by cmgchess** [comment]
ah so when i select filters then the requests array has multiple elements. (https://codepen.io/cmgchess/pen/oNGmqWE) so if i add the `responseFields` to each element it should work?
or is it enough to add it only to the 0th 

skeleton thats being send
```javscript
{
    "requests": [
        {
            "indexName": "bestbuy",
            "params": {
                "query": "apple",
                "hitsPerPage": 7,
                "maxValuesPerFacet": 3,
                "page": 0,
                "facets": [
                    "category"
                ],
                "tagFilters": "",
                "facetFilters": [
                    [
                        "category:Cell Phone Cases & Clips",
                        "category:iPad Cases, Covers & Sleeves"
                    ]
                ]
            }
        },
        {
            "indexName": "bestbuy",
            "params": {
                "query": "apple",
                "hitsPerPage": 1,
                "maxValuesPerFacet": 3,
                "page": 0,
                "attributesToRetrieve": [],
                "attributesToHighlight": [],
                "attributesToSnippet": [],
                "tagFilters": "",
                "analytics": false,
                "clickAnalytics": false,
                "facets": "category"
            }
        }
    ]
}
```

**Comment by Haroenv** [comment]
Every index in the requests array is its own "search query", so you indeed pass it to every query. If you want to set the responseFields globally, you can do that with an index setting too.

**Comment by cmgchess** [comment]
one last question 
any idea why it creates multiple queries with the helper when i add facets. since i can see every facet filter that is being set via the `facetFilters` of the 0th element
can i limit it to just 1 or is this how it behaves

**Comment by Haroenv** [comment]
When you use the helper and have a disjunctive refinement, it sends that second query to get the correct facet counts. If you look at the results of the first facet, you'll see that they are conjunctive (only the facets remaining in that result set), and not disjunctive as requested. That's what the second query is for.

**Comment by Haroenv** [comment]
As you're using the helper, you can also use `helper.setQueryParameter('responseFields', [...])` and don't need to patch the queries sent

**Comment by cmgchess** [comment]
thanks!
