### ISSUE TITLE
How to refresh the index quickly through APIID

### ISSUE THREAD

**Issue by Beacontownfc** [algolia/algoliasearch-client-javascript#1416]
This is from Apache Linkis, our website address is [https://linkis.apache.org](https://linkis.apache.org). Algolia service we applied for by email. Since the documents of our website often need to be update, we hope Algolia can update the index quickly, but we don't know how to make the index update faster.

**Comment by shortcuts** [comment]
Hey, this issue is related to [DocSearch](https://github.com/algolia/docsearch), please re-open it there, thanks!
