### ISSUE TITLE
API to get object ids from task id

### ISSUE THREAD

**Issue by nitinmagdumvista** [algolia/algoliasearch-client-javascript#1422]
https://github.com/algolia/algoliasearch-client-node/issues/29

**Comment by nitinmagdumvista** [comment]
@bodinsamuel @Haroenv

**Comment by nitinmagdumvista** [comment]
Hello I am using https://www.algolia.com/doc/rest-api/search/#get-a-tasks-status 

I am using this API to get the status of my task but in case if some tasks are completed means status is not completed then i want to update those objects present in that task ids

currently what i observed for around 1700 objects its created 2 task ids, and for 16K objects its creating 17 task ids
so if some of the tasks are not completed successfully i want to get objects from those tasks and update again

or instead of getting objects and updating them again is there a way to just retry using task id

or not sure if there is better way to achieve this, could you please assist here

**Comment by nitinmagdumvista** [comment]
Bsically what i am saying is when i got to know my task is not successful from status API then what is the next steps

either retry all update again
find objects from that failed taskid and only update that (so here is there API to get objectids from taskid)

**Comment by shortcuts** [comment]
Hey, in the snippet you shared you are calling [the `wait` method](https://www.algolia.com/doc/api-reference/api-methods/wait-task/), which means you are already waiting for these tasks to be considered as completed (published).

You also shouldn't have to handle the task retrying yourselves, the validation that matters to you happen at the API call time, any error will be reported there and you'd have to retry your call, but you don't have to interact with the queue other than making sure the task is `published` (which is the equivalent of completed)

**Comment by nitinmagdumvista** [comment]
@shortcuts Thanks for reply

I am using Wait yes but its just returning taskID its not telling its completed successfully or not
so the next step is using those taskId i am checking the status using published 

but what if the taskid returns status unpublished

**Comment by nitinmagdumvista** [comment]
@shortcuts Thanks

so you mean to say wait will return only if all tasks are successful and throws error if any task fails

**Comment by shortcuts** [comment]
> so you mean to say wait will return only if all tasks are successful and throws error if any task fails so no need to check the status of each taskid in case of success

Yes, and more exactly, `wait` will only stop fetching tasks status when they are all `published`. You can consider that once you API call gets through, all you have to do is call the `wait` method and not bother with anything else.

**Comment by shortcuts** [comment]
You can find the exact implementation here: https://github.com/algolia/algoliasearch-client-javascript/blob/master/packages/client-search/src/methods/index/waitTask.ts and the usage in the `saveObjects` file

**Comment by nitinmagdumvista** [comment]
@shortcuts Thanks
So waitTask internally taking care of retrying part so it makes sue that all tasks are completed.
so if i use .wait() i dont have to do error handling

**Comment by shortcuts** [comment]
> so if i use .wait() i dont have to do error handling

Not on the `task`, but keep a catch for any API calls anyway as you can encounter other issue :)

I'm closing this issue as `completed`, but in case you encounter any issue please re-open it!

**Comment by nitinmagdumvista** [comment]
@shortcuts how long the taskId maintained at algolia side
for example if i got a taskId after saveObject and after one month if i call get status API passing task Id can i get the status for same

Thanks,
