### ISSUE TITLE
multipleQueries should be in lite client

### ISSUE THREAD

**Issue by kopax-polyconseil** [algolia/algoliasearch-client-javascript#1424]
Hello,

We are using the search features and want to use the lite client, however, the `multipleQueries` method is not available in it while it is still a search feature.

How can we use the search lite client to optimize our bundle size, could the `multipleQueries` be added in it and how ?

Thanks in advance

Related issues: https://github.com/algolia/algoliasearch-client-javascript/issues/1421

**Comment by kopax-polyconseil** [comment]
It seems it is present in `algoliasearch-lite.esm.browser.js` ,  but the typing is wrong.

**Comment by Haroenv** [comment]
the method `search` exists, which is preferred over `multipleQueries`, does that solve your use case before the typings would be updated?

**Comment by kopax-polyconseil** [comment]
Hello, no we have to patch-package in order to solve our use case because:

- Typing for lite vesrion is wrong, the lite version include multipleQueries but not it's typing
- browser field use umd imports while our react-native is web ios and android, and can use ESM

This is our PR: https://github.com/pass-culture/pass-culture-app-native/pull/3523

The patch package consist of editing in node_modules those files :   

- node_modules/algoliasearch/lite.js
- node_modules/algoliasearch/index.js
- node_modules/algoliasearch/dist/algoliasearch.umd.js
- node_modules/algoliasearch/dist/algoliasearch.cjs.js
- node_modules/algoliasearch/dist/algoliasearch-lite.umd.js

With new content (with or without `dist` prefix depending on the file): 


```js
/* eslint-disable functional/immutable-data, import/no-commonjs */
const algoliasearch = require('./dist/algoliasearch-lite.esm.browser.js');

/**
 * The Common JS build is the default entry point for the Node environment. Keep in
 * in mind, that for the browser environment, we hint the bundler to use the UMD
 * build instead as specified on the key `browser` of our `package.json` file.
 */
module.exports = algoliasearch;

/**
 * In addition, we also set explicitly the default export below making
 * this Common JS module in compliance with es6 modules specification.
 */
module.exports.default = algoliasearch;
```

We haven't found another way to do so for both iOS Android and Web.

It was possible to fix the web only using Webpack `resolve.alias` configuration, because UMD file is bigger than ESM when builded, but this didn't solve the issue for the native app. 


I suggest to keep the issue open until this matter is resolved.

**Comment by shortcuts** [comment]
Hey, closing since this should be addressed in v5.
