### ISSUE TITLE
deleteObject losing ObjectID in internal APIs with 4.13.1

### ISSUE THREAD

**Issue by spiceee** [algolia/algoliasearch-client-javascript#1430]
We have a custom Contentful webhook that updates and deletes entries from an Algolia index, and the delete requests were 500ing. Looking at the search logs, I saw that with `algoliasearch` 4.13.1, something swiped the objectID from the POST payload. 

The update to 4.14.2 fixed this, but it does look like a bug in the Algolia API endpoint, so I thought I'd mention it. I can see in the logs retries are being made for failed 4.13.1 delete operations, and this could be stressing the service unnecessarily.

In 4.13.1:
<img width="558" alt="Screen Shot 2022-10-27 at 20 34 16" src="https://user-images.githubusercontent.com/12278/198418273-af5c6b0e-c040-467a-b44f-7529939cd57a.png">

in 4.14.2:
<img width="558" alt="Screen Shot 2022-10-27 at 20 35 09" src="https://user-images.githubusercontent.com/12278/198418314-159c6cec-aa8c-458f-a3dc-9d1d1d820086.png">

Thanks,

Fabio.

**Comment by Haroenv** [comment]
There has been no change related to any of those methods in the versions you mention. Are you sure the code is the same between those two trials? Can you reproduce this consistently?

**Comment by spiceee** [comment]
@Haroenv Sorry, on further investigation, it looks like the problem is with Contentful. It is logging a different payload than the one they are actually sending for some reason. Will close this.
