### ISSUE TITLE
getaddrinfo ENOTFOUND places-2.algolianet.com

### ISSUE THREAD

**Issue by sanpodd** [algolia/algoliasearch-client-javascript#1440]
While we are trying to integrate algolia, we are seeing following issue

AlgoliaSearchNetworkError: getaddrinfo ENOTFOUND places-2.algolianet.com\n    at ClientRequest.error (/exodus-service/development/node_modules/algoliasearch/src/server/builds/node.js:233:14)\n    at Object.onceWrapper (node:events:642:26)\n    at ClientRequest.emit (node:events:527:28)\n 

Currently we are using 
"algoliasearch": "^3.33.0"
"@types/algoliasearch": "^3.30.17"

Node version: v16.14.2

As per algolia lib, we see that the hosts are created as shown below
this.hosts.read = [this.applicationID + mainSuffix].concat(defaultHosts);
    this.hosts.write = [this.applicationID + '.algolia.net'].concat(defaultHosts);

But in our url - places-2.algolianet.com, "places" is not our application id, it is our index. So not sure why index is getting added instead of application id. Any help here would be appreciated.

Thank you

**Comment by Haroenv** [comment]
Hey @sanpodd, the places application no longer exists, as well as the places product. How do you instantiate algoliasearch?

**Comment by sanpodd** [comment]
@Haroenv Please look at below code on how we instantiate algoliasearch
`
import * as algoliasearch from 'algoliasearch';
const places = require('algoliasearch/src/places');
import { Client, ClientOptions } from 'algoliasearch';
import { Logger } from '@nestjs/common';

export interface PlaceInterface extends ReturnType<typeof algoliasearch.initPlaces> {
	setIPAddress(value?: string): void;
}

export function initPlaces(appId: string, apiKey: string): PlaceInterface {
	let client: Client;
	const customAlgoliasearch = (appId: string, apiKey: string, opts: ClientOptions) => {
		client = algoliasearch(appId, apiKey, opts);
		return client;
	};
	const initPlaces = places(customAlgoliasearch)(appId, apiKey);
	initPlaces.setIPAddress = (value: string = '') => {
		if (!client) {
			Logger.warn('Unable to set client header');
		}
		client.setExtraHeader('X-Forwarded-For', value);
	};
	return initPlaces;
}

`
Calling initPlaces with required parameters. Please let me know if you need more information.

Thank you,
Santhosh

**Comment by Haroenv** [comment]
Right, as mentioned, the places product no longer exists, which is why this doesn't work. You can find alternatives in https://www.algolia.com/blog/product/sunsetting-our-places-feature/
