### ISSUE TITLE
Documentation - Invalid object attributes: attributesForDistinct

### ISSUE THREAD

**Issue by callmekatootie** [algolia/algoliasearch-client-javascript#1447]
Hello,

On [this](https://www.algolia.com/doc/api-reference/api-parameters/distinct/) page, it mistakenly refers to the setting as `attributesForDistinct` (There is no 's'). It should be `attributeForDistinct`. The former gives an error

```
{
  name: 'ApiError',
  message: 'Invalid object attributes: attributesForDistinct near line:1 column:827',
  status: 400,
  transporterStackTrace: [
    {
      request: [Object],
      response: [Object],
      host: [Object],
      triesLeft: 3
    }
  ]
}
```

**Comment by Haroenv** [comment]
Thanks for this issue, there were indeed two places in the documentation that referred to the non-existing `attributesForDistinct`. I've made a PR and this issue will close automatically once it's merged.
