### ISSUE TITLE
Algolia Total Users X-Forwarded-For

### ISSUE THREAD

**Issue by davidgacc** [algolia/algoliasearch-client-javascript#1448]
hi people,

I am trying to add `headers: {'X-Forwarded-For': ip.toString() },` , in order to get the total users as total metric in algolia https://www.algolia.com/doc/guides/getting-analytics/search-analytics/out-of-the-box-analytics/how-to/specify-which-user-is-doing-the-search/?client=javascript#set-the-x-forwarded-for-header. However,I don't see any changes in total users in the dashboard.

I put logs..and i got the : ` ip: 10.101.53.4`, so i am receiving the ip from the request. 

this is the block code : 

```
async getProductForSKUs(hits: AlgoliaOutputDocument[], searchParams: searchParams, ip: any): Promise<Record<number, AlgoliaOutputDocument[]>> {

   const products = await index.search<AlgoliaOutputDocument>('', {
      headers: {'X-Forwarded-For': ip.toString() },
      filters: filtersString,
      distinct: false,
      hitsPerPage: 1000,
      numericFilters: numericFilters.length ? numericFilters : undefined,
      attributesToHighlight: [],
      attributesToRetrieve: ['*', '-sku.slug', '-sku.description', '-sku.created_at']
    });
 return products;
  
}
```

thank you for your help.

**Comment by Haroenv** [comment]
The code seems correct. Did you check the logs in the dashboard to see whether there are actually different ip adresses? maybe there's another layer between your search that's overriding the ip.

**Comment by davidgacc** [comment]
it was another layers overriding the ip. Thanks
