### ISSUE TITLE
Package does not seem to exist: npm install algoliasearch-lite

### ISSUE THREAD

**Issue by bkuhl** [algolia/algoliasearch-client-javascript#1489]
Following the directions in [this documentation](https://www.algolia.com/doc/api-client/getting-started/install/javascript/?client=javascript#install-via-npm-recommended) for installing the module, it seems like I should be able to run `npm install algoliasearch-lite`, however when I do the package doesn't seem to exist.  Is there a way to only install the lite version via npm?

```
$ npm install algoliasearch-lite                   
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/algoliasearch-lite - Not found
npm ERR! 404 
npm ERR! 404  'algoliasearch-lite@*' is not in this registry.
```

**Comment by shortcuts** [comment]
Hey, the `lite` package is not a standalone package but part of `algoliasearch`, you can do `npm install algoliasearch` and then `import 'algoliasearch/lite`

**Comment by shortcuts** [comment]
> Hey, the `lite` package is not a standalone package but part of `algoliasearch`, you can do `npm install algoliasearch` and then `import * from 'algoliasearch/lite'`

**Comment by bkuhl** [comment]
Gotcha, thanks for the quick response!
