### ISSUE TITLE
Error on add API key

### ISSUE THREAD

**Issue by googlicus** [algolia/algoliasearch-client-javascript#1492]
There is 403 error on add API key: 'algoliasearch.exceptions.RequestException: Invalid Application-ID or API key'
Used admin APi key to send request. Key was been regenerated - problem same.
Same situation for javascript ('algoliasearch' lib v4.20) and python (3.11) API.

Sample:
params = {
    'maxQueriesPerIPPerHour': 100,
}
acl = ['search']
res = client.add_api_key(acl, params)

**Comment by millotp** [comment]
From the documentation: `You can’t generate secured API keys from your Admin API key or from other secured API keys.`
https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/
