### ISSUE TITLE
Default export is not a function since `4.23.1`

### ISSUE THREAD

**Issue by peeterkask** [algolia/algoliasearch-client-javascript#1515]
Hi

We are getting an error since upgrading to `@algolia/recommend` version `4.23.1`. Previous version `4.23.0` seems to be ok.

Very basic client initialization fails:
```
import algoliarecommend from '@algolia/recommend';

const client = algoliarecommend(
  ...,
  ...
);
```

with error:
```
const client = algoliarecommend(
                               ^
TypeError: (0 , recommend_1.default) is not a function
```

**Comment by dhayab** [comment]
Thanks for your report @peeterkask. `@algolia/recommend@4.23.2` has just been released with a fix for this issue.
