### ISSUE TITLE
 Issue with Importing `algoliasearch` from `"algoliasearch/lite"` in v5

### ISSUE THREAD

**Issue by timotheeduran** [algolia/algoliasearch-client-javascript#1535]
Following the instructions in the [Upgrade the JavaScript API clients to v5](https://www.algolia.com/doc/libraries/javascript/v5/upgrade/) guide, I attempted to use the import statement:

```javascript
import { algoliasearch } from "algoliasearch/lite";
```

However, this resulted in the following TypeScript error:

```
Module '"algoliasearch/lite"' has no exported member 'algoliasearch'.ts(2305)
```

However, this works:

```javascript
import { algoliasearch } from "algoliasearch";
```

**Comment by christine927t** [comment]
Just ran into this same issue with version 5.0.0
@timotheeduran thanks for the fix, this worked for me too

**Comment by Haroenv** [comment]
I believe the actual solution is `import { liteClient as algoliasearch } from 'algoliasearch/lite';`, @shortcuts told me he's already updating the documentation :)

**Comment by christine927t** [comment]
@Haroenv Ah ok yes that import worked for me. thank you!

**Comment by shortcuts** [comment]
> I believe the actual solution is `import { liteClient as algoliasearch } from 'algoliasearch/lite';`, @shortcuts told me he's already updating the documentation and is waiting for the deploy :)

Indeed @Haroenv that's the correct way, the lite client is exported as `liteClient` from `algoliasearch/lite`

The READMEs (https://github.com/algolia/algoliasearch-client-javascript/tree/main/packages/algoliasearch) have been updated, we will update the docs asap!

**Comment by timotheeduran** [comment]
Thank you! That was quick 🤠
