### ISSUE TITLE
[bug]: v5.3.0 - search client instance type is not compatible with react-instant search v7.13.0

### ISSUE THREAD

**Issue by WavyWalk** [algolia/algoliasearch-client-javascript#1550]
### Description

on latest versions:
"react-instantsearch": "7.13.0"
"algoliasearch": "5.3.0"

when setting SearchClient on InstantSearch as prop, compiler complains that searchForFacetValues is wrong

example:
```typescript
import {InstantSearch} from "react-instantsearch";
import {SearchClient, algoliasearch} from "algoliasearch";

const searchClient: SearchClient = algoliasearch('appId', 'apiKey')

<InstantSearch
      indexName="indexName"
      searchClient={searchClient} // <--- compiler complains that face
/>
```

Repo with reproduction: https://github.com/WavyWalk/reproduce-algolia-v5/blob/typing-5-3-0/src/App.tsx

### Client

Search

### Version

5.3.0

### Relevant log output

```shell
TS2322: Type
{   transporter: Transporter;   appId: string;   clearCache(): Promise<void>;   readonly _ua: string;   addAlgoliaAgent(segment: string, version?: string | undefined): void;   ... 76 more ...;   updateApiKey({key, apiKey}: UpdateApiKeyProps, requestOptions?: RequestOptions | undefined): Promise<...>; }
is not assignable to type SearchClient
Types of property searchForFacetValues are incompatible.
Type
({indexName, facetName, searchForFacetValuesRequest}: SearchForFacetValuesProps, requestOptions?: RequestOptions | undefined) => Promise<SearchForFacetValuesResponse>
is not assignable to type undefined
```

**Comment by shortcuts** [comment]
cc @Haroenv maybe

**Comment by Haroenv** [comment]
`createLiteClient` works for sure as type, which is recommended in frontend usage anyway because it's much smaller. Will investigate if anything is wrong

**Comment by Haroenv** [comment]
This is happening because in 5.3.0 sffv is reintroduced, but with a different signature than before. I'll check what the differences are and see if we can make a type that works there too. In the mean time you can continue using the previous versions.

**Comment by Haroenv** [comment]
This will be fixed in the next version of InstantSearch: https://github.com/algolia/instantsearch/pull/6354
