### ISSUE TITLE
[bug]: 5.2.5+ breaks Parcel

### ISSUE THREAD

**Issue by BigGillyStyle** [algolia/algoliasearch-client-javascript#1551]
### Description

I have a fairly simple usage of `algoliasearch` (see repo at https://github.com/BigGillyStyle/bandsaws-react/). My repo is based off the `react-instantsearch` React examples ( [here](https://github.com/algolia/instantsearch/blob/master/examples/react/getting-started/package.json) ). I have found when using Parcel to bundle just like in the examples, that it works up to version 5.2.4. Starting at version 5.2.5 (through 5.4.0) of `algoliasearch` when I run `parcel build index.html` I see the following error:

```
> BABEL_ENV=parcel parcel build index.html --no-cache

🚨 Build failed.

@parcel/core: Failed to resolve '@algolia/requester-node-http' from './node_modules/algoliasearch/dist/lite/builds/node.cjs'

  /Users/apickler/projects/woodtoolsearch/bandsaws-react/node_modules/algoliasearch/dist/lite/builds/node.cjs:28:42
    27 | var import_client_common2 = require("@algolia/client-common");
  > 28 | var import_requester_node_http = require("@algolia/requester-node-http");
  >    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    29 |
    30 | // lite/src/liteClient.ts

@parcel/resolver-default: Cannot load file './index' from module '@algolia/requester-node-http'
```

I am guessing, based on the limited Changelog in 5.2.5, that this is like due to [this PR](https://github.com/algolia/api-clients-automation/pull/3640)

### Client

Search

### Version

5.2.5

### Relevant log output

```shell
> BABEL_ENV=parcel parcel build index.html --no-cache

🚨 Build failed.

@parcel/core: Failed to resolve '@algolia/requester-node-http' from './node_modules/algoliasearch/dist/lite/builds/node.cjs'

  /Users/apickler/projects/woodtoolsearch/bandsaws-react/node_modules/algoliasearch/dist/lite/builds/node.cjs:28:42
    27 | var import_client_common2 = require("@algolia/client-common");
  > 28 | var import_requester_node_http = require("@algolia/requester-node-http");
  >    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    29 |
    30 | // lite/src/liteClient.ts

@parcel/resolver-default: Cannot load file './index' from module '@algolia/requester-node-http'
```

**Comment by neehhaa06** [comment]
Hello ! @BigGillyStyle :)

fix: #1551


 To resolve the issue, first ensure `@algolia/requester-node-http` is installed by running `npm install @algolia/requester-node-http`. Clear Parcel’s cache with `parcel build index.html --no-cache` and verify compatibility between your dependencies. If the problem persists, consider downgrading `algoliasearch` to version 5.2.4 or upgrading Parcel to its latest version.

**Comment by shortcuts** [comment]
Hey @BigGillyStyle, it seems that exports resolution is opt-in on the parcel side for v2: https://github.com/parcel-bundler/parcel/issues/4155#issuecomment-2193642588

Once this is added to your package.json, it's seamless.

**Comment by BigGillyStyle** [comment]
Thanks @neehhaa06 for the very clear instructions.
