### ISSUE TITLE
Migration from v4 to v5: Issues with algoliasearch and AlgoliaSearchHelper

### ISSUE THREAD

**Issue by paulgrotzke** [algolia/algoliasearch-client-javascript#1553]
We're migrating from v4 to v5, using algoliasearch in combination with [AlgoliaSearchHelper](https://github.com/algolia/instantsearch/tree/master/packages/algoliasearch-helper)

Previously, we used it like this:
```typescript
import { algoliasearch } from 'algoliasearch'
import algoliasearchHelper from 'algoliasearch-helper'

const client = algoliasearch('id', 'apiKey', {
  headers: { 'X-Algolia-UserToken': 'token' }
})

const helper = algoliasearchHelper(client, 'index', { ...options })
  ```

We've encountered two problems:

**1) Setting headers during client creation**
Previously, we passed the headers directly when creating the client. Now, the TypeScript types indicate this might not be possible:
```typescript
Object literal may only specify known properties, and 'headers' does not exist in type 'Partial<Omit<CreateClientOptions, "apiKey" | "appId">>'.ts(2353)
```

Is this correct? If so, what's the recommended way to set headers?
We've only found this article on [Request Options](https://www.algolia.com/doc/libraries/javascript/v5/request-options/) which mentions setting headers via `searchSingleIndex`. However, we're not using that method in our case.

**2) Type incompatibility between Algoliasearch client and SearchClient**
The client created (`typeof Algoliasearch`) seems to be incompatible with the type that algoliasearchHelper expects (`typeof SearchClient`) 

``` ts 
const helper = algoliasearchHelper(client, 'index', { ...options })
//                                 ^
// Argument of type 'Algoliasearch' is not assignable to parameter of type 'SearchClient'.
// Types of property 'searchForFacetValues' are incompatible.
// Type '({ indexName, facetName, searchForFacetValuesRequest }: SearchForFacetValuesProps, requestOptions?: RequestOptions | undefined) => Promise<SearchForFacetValuesResponse>' is not assignable to type 'undefined'.
// ts(2345)
```

**Comment by shortcuts** [comment]
Hey!

The property is named `baseHeaders`, you can use it like this:

```js
const client = algoliasearch('foo', 'bar', { baseHeaders: { ... } });
```

**Comment by shortcuts** [comment]
> We've only found this article on [Request Options](https://www.algolia.com/doc/libraries/javascript/v5/request-options/) which mentions setting headers via searchSingleIndex. However, we're not using that method in our case.

`requestOptions` is available on every methods, as the last expected parameter

**Comment by shortcuts** [comment]
closing the issue as it should be answered, don't hesitate to ask more questions if you need!
