### ISSUE TITLE
[bug]: TypeError: algoliasearch is not a function

### ISSUE THREAD

**Issue by AdamBCo** [algolia/algoliasearch-client-javascript#1558]
### Description

When I include the following code in a .js file, I get the following RESULT

```
const algoliasearch = require("algoliasearch");
const algoliaClient = algoliasearch(
  process.env.ALGOLIA_APP_ID,
  process.env.ALGOLIA_APP_SECRET,
);
```

RESULT:
`TypeError: algoliasearch is not a function`

### Client

All

### Version

5.7.0

**Comment by millotp** [comment]
Hello,
If you look at the example in the [doc](https://www.algolia.com/doc/libraries/javascript/v5/#test-your-installation), you need to use:
```js
import { algoliasearch } from "algoliasearch";
```

or
```js
const { algoliasearch } = require("algoliasearch");
```
