### ISSUE TITLE
[bug]: NodeJs - Property 'replaceAll' does not exist on type 'string'.

### ISSUE THREAD

**Issue by risalfajar** [algolia/algoliasearch-client-javascript#1559]
### Description

I want to use Algolia library in my Firebase Cloud Functions project, but when I'm trying to deploy a function, it throws an error:
```io
node_modules/@algolia/client-common/src/transporter/helpers.ts:42:11 - error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.
```

So I add this to my tsconfig:
```json
{
    "compilerOptions": {
        "lib": [
          "ES2021.String"
        ]
    }
}
```

But then the error changed:
```io
node_modules/@algolia/client-common/src/cache/createBrowserLocalStorageCache.ts:10:41 - error TS2304: Cannot find name 'window'.
```

### Client

Search

### Version

5.7.0

### Relevant log output

```shell
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc && tsc-alias

node_modules/@algolia/client-common/src/transporter/helpers.ts:42:11 - error TS2550: Property 'replaceAll' does not exist on type 'string'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2021' or later.

42         ).replaceAll('+', '%20')}`,
             ~~~~~~~~~~


Found 1 error in node_modules/@algolia/client-common/src/transporter/helpers.ts:42


Error: functions predeploy error: Command terminated with non-zero exit code 2
```

**Comment by Haroenv** [comment]
Could it be that you're deploying to an old node version that doesn't have replaceAll? Earliest would be 15.

**Comment by risalfajar** [comment]
I'm using Node 20

**Comment by risalfajar** [comment]
I don't understand, why is this closed?

**Comment by Haroenv** [comment]
@shortcuts has created a pull request that removes the usage of replaceAll (in https://github.com/algolia/api-clients-automation/pull/3897). In the next version of the client this issue will be fixed

**Comment by shortcuts** [comment]
Hey, sorry I had an issue with the release, I'm fixing it right now and will schedule a release right

**Comment by shortcuts** [comment]
hey @risalfajar, in 5.8.0 `replaceAll` has been dropped in favor of `replace`, do you still have an issue?

**Comment by risalfajar** [comment]
I've upgraded to 5.8.0 and it works now. Thanks for the quick fix!
