### ISSUE TITLE
[bug]: Unable to use search client in cloudflare workers: Cannot bundle Node.js built-in "crypto" 

### ISSUE THREAD

**Issue by TorbjornHoltmon** [algolia/algoliasearch-client-javascript#1567]
### Description

Using version `5.10.2` we cannot bundle algolia search client for cloudflare workers since it uses Node built ins.

We tried updating from `5.2.1`, which still works fine.

### Client

All

### Version

5.10.2

**Comment by TorbjornHoltmon** [comment]
Its hard to point at any code in the repo since everything is generated.

Browsing the code in npm, the import is at:

`@algolia/client-search/dist/builds/fetch.js` line number 2294 in `5.10.2`

<img width="602" alt="image" src="https://github.com/user-attachments/assets/a47a1e68-ca50-43b9-a20b-9d259985459b">

**Comment by Haroenv** [comment]
In the source code I'm seeing node:crypto being used https://github.com/algolia/algoliasearch-client-javascript/blob/197056452660881835a9f15d8d4b8d68e6a90fca/packages/client-search/builds/fetch.ts#L30, but maybe that would also be problematic. I wonder if the global `crypto.subtle.importKey` and `crypto.subtle.sign` instead would work for this build?

As a workaround if you're not using that function, you can in the mean time remove the import of `createHmac` from `node:crypto` and your deploy likely works

**Comment by lassediercks** [comment]
Because we are thinking about levering the new method `browse` in order to ssr initial page views on cloudflare I was wondering if this is something algolia is planning on addressing

**Comment by lassediercks** [comment]
thanks for the answer @Haroenv 

I was actually able to use the `browse` method of the v5 js sdk on a cloudflare worker without any problems
