### ISSUE TITLE
V4 API

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-javascript#204]
While doing a bit of V4 JS client (#195), reading through all the current API methods I thought of another API to: ease the use, be more consistent and plan future evolutions.

Here's the current relevant API:

``` js
var client = algoliasearch();
var index = client.initIndex();

// global indexes actions
client.deleteIndex();
client.listIndexes();
client.moveIndex();
client.copyIndex();

// search
client.batch(); // multi index write
client.search(); // multi index search

// global keys
client.listUserKeys();
client.getUserKeyACL();
client.deleteUserKey();
client.addUserKey();
client.updateUserKey();

// index objects
index.addObject(); // Add or update
index.addObjects(); // Add or update
index.getObject();
index.getObjects();
index.partialUpdateObject();
index.partialUpdateObjects();
index.saveObject(); // add or update
index.saveObjects(); // add or update

// index keys
index.listUserKeys();
index.getUserKeyACL();
index.deleteUserKey();
index.addUserKey();
index.updateUserKey();

// index actions
index.waitTask();
index.search();
index.similarSearch();

// index settings
index.getSettings();
index.setSettings();

index.clearIndex();
```

For V4, I propose a new API where we introduce namespaces.

``` js
var client = algoliasearch();
var index = client.initIndex();

// multi indexes methods
client.batch(); // same
client.search(); // same

// global indexes methods
client.deleteIndex();
client.listIndexes();
client.copyIndex();
client.moveIndex();
client.clearIndex(); // was index.clearIndex()

// global keys
client.keys.get(); // was client.getUserKeyACL
client.keys.add(); // was client.addUserKey
client.keys.update(); // was client.updateUserKey();
client.keys.delete(); // was client.deleteUserKey();
client.keys.list(); // was client.listUserKeys();

// index search
index.search();
index.similarSearch();
index.browse();
index.browseFrom();

// index settings
index.settings.set(); // was index.setSettings;
index.settings.get(); // was index.getSettings;

// objects methods, all of them can take an object or an array or objects
index.objects.save(); // was index.addObject, index.addObjects, index.saveObject, index.saveObjects. There's no way to get a proper real ADD with the API, it's always create or update no matter what you do, you will never get "Object already exists"
index.objects.partialUpdate(); // was index.partialUpdateObject, index.partialUpdateObjects. Update only, should error if object does not exists (not sure this is feasible, API is permissive here)
index.objects.delete(); // was index.deleteObject, index.deleteObjects
index.objects.get(); // was index.getObject, index.getObjects

// index keys
index.keys.get(); // was index.getUserKeyACL
index.keys.add(); // was index.addUserKey
index.keys.update(); // was index.updateUserKey;
index.keys.delete(); // was index.deleteUserKey;
index.keys.list(); // was index.listUserKeys;
```

I believe this proposal should be easier to reason about (consistent) and help us in the future when we need to add methods, parameters.

What do you think?

**Comment by ElPicador** [comment]
I like it.

But why not do the same with `index` methods:
`client.deleteIndex()` =>  `client.index(name).delete()` ?

**Comment by Jerskouille** [comment]
:+1: with both the proposal and the comment of @ElPicador .
The issue is that we try to stay consistent across all of our clients, no?

**Comment by vvo** [comment]
> client.deleteIndex() => client.index(name).delete() ?

I hesitated on this one, this is not a very common API in JS I feel. It reads weirdly compared to descriptive "deleteIndex" no?

**Comment by ElPicador** [comment]
For the scala api, I did this `delete index "myIndex"`
But indeed it might be weird for JS

**Comment by vvo** [comment]
> The issue is that we try to stay consistent across all of our clients, no?

Yes that's a very good point. But I thought that at some point, if we want nice things, we break and move forward! :) And iteratively it will get better.

**Comment by maxiloc** [comment]
Couldn't we merge index.objects.add() and index.objects.update() ?

**Comment by vvo** [comment]
> Couldn't we merge index.objects.add() and index.objects.update() ?

I hesitated too on this. The thing is that I feel being magical can be bad for developers in the end. I prefer to state ADD is to ADD (and if you try to update with it, it will error), update is to UPDATE (and if you try to add with it, it should error).

Rather than a magical .save() that does everything. But this is open to more advices, thanks for feedback.

**Comment by vvo** [comment]
It's a bit like "mkdir", it's good that it does error if the directory exists by default, so you do not make mistakes without knowing it.. ?

**Comment by maxiloc** [comment]
But is it failing currently ? I am not sure. Because for me the difference between addObjects and saveObjects was just the need for an objectID in records that are being pushed, and no error coming from the api

**Comment by Jerskouille** [comment]
> I hesitated too on this. The thing is that I feel being magical can be bad for developers in the end. I prefer to state ADD is to ADD (and if you try to update with it, it will error), update is to UPDATE (and if you try to add with it, it should error).

I don't think the API is returning an error in these cases, how do you plan to check that?

**Comment by proudlygeek** [comment]
It's definitely more a more REST-ish / OO API client this way, but I kinda like the simplicity of the current one: namespaces feels really weird in JS because libraries usually prefer to have a flat hierarchy of methods. 

If it is for the sake of consistency then go for it :+1: , but apart from that I don't really see an improvement over the current version.

**Comment by vvo** [comment]
> But is it failing currently ?

It's not, currently both addObject and saveObject are doing the same exact thing.

**Comment by maxiloc** [comment]
So I would prefer having only a save method. Because if I understand correctly you could do everything with the update method. Right ?

**Comment by vvo** [comment]
> I don't think the API is returning an error in these cases, how do you plan to check that?

If it's not feasible then I will just merge add and update into a save method. Because those are doing exactly the same indeed.

**Comment by vvo** [comment]
> So I would prefer having only a save method. Because if I understand correctly you could do everything with the update method. Right ?

Yes, if the API is not able to send an error when you said "ADD" then I will merge update and add in save. Good point you had the same idea because it feels simpler (cc @redox)

**Comment by vvo** [comment]
> namespaces feels really weird in JS because libraries usually prefer to have a flat hierarchy of methods.

Agree. It really depends on the project, you can have namespaces in JS. It's not the most common pattern but here's on example of a github api client with namespaces: https://github.com/mikedeboer/node-github.

> If it is for the sake of consistency then go for it  , but apart from that I don't really see an improvement over the current version.

Some of this refactoring is for consistency, we have weird things like "userKeys", which are no more user keys but just keys in Algolia.

Namespaces can useful to avoid having to duplicate every function name to indicate "you can pass one thing" "you can pass multiple thing".

That way we can remove addObjects, saveObjects, getObjects, partialUpdateObjects because those are just objects.add, objects.save, objects.get usable with one or multiple things.

Flat API is nice yes but at some point when the number of methods grow then it becomes complex.

**Comment by vvo** [comment]
So it seems there's no way to get an error like "This object already exists" from the API, it means we can safely merge add and save into just save. It will avoid the users having to decide which one to use. Those are the same: dont have objectID? => create, have an objectID => create or udpdate

**Comment by vvo** [comment]
Basically there's no ADD in Algolia, it's always an ADD OR UPDATE that is being done. So we should reflect that in API clients.

**Comment by pixelastic** [comment]
I also have a few concerns that were already raised, but here are my feedbacks on the whole list:

> // global indexes methods
> client.deleteIndex();
> client.listIndexes();
> client.moveIndex();
> client.clearIndex(); // was index.clearIndex()

The `client`/`index` syntax tripped me up sometimes. I would like to be able to do `index.rename`, and `index.clear` directly from the index. I'm ok with keeping the top level `list` and the destructive `delete` on the parent `client`.

> // global keys
> client.keys.get(); // was client.getUserKeyACL
> client.keys.add(); // was client.addUserKey
> client.keys.update(); // was client.updateUserKey();
> client.keys.delete(); // was client.deleteUserKey();
> client.keys.list(); // was client.listUserKeys();

The namespace really feels weird to me. Not sure to see the value it adds. Having this kind of namespace would make me want to use `client.keys` as a list to iterate on, but this won't be possible as this is just an object namespace. 

I'd rather keep the previous methods, maybe with a bit of renaming, `getKey`, `addKey`, `updateKey`, `deleteKey` and `listKeys`.

> // index settings
> index.settings.set(); // was index.setSettings;
> index.settings.get(); // was index.getSettings;

I'd keep the previous `getSettings`/`setSettings`, especially because we use it in every other API client. If it would bring value to have it in a better JS way I would be ok with it, but I'm not sure I see what it brings here.

> // objects methods, all of them can take an object or an array or objects
> index.objects.add(); // was index.addObject, index.addObjects. Now ADD only (POST), should error if object exists. Easier to reason.
> index.objects.update(); // was index.saveObject, index.saveObjects. Update only, should error if object does not exists (not sure this is feasible, API is permissive here)
> index.objects.partialUpdate(); // was index.partialUpdateObject, index.partialUpdateObjects. Update only, should error if object does not exists (not sure this is feasible, API is permissive here)
> index.objects.delete(); // was index.deleteObject, index.deleteObjects
index.objects.get(); // was index.getObject, index.getObjects

First, I wonder about the name _object_. Across our documentation we often use _object_, _record_ or _item_. Maybe it would be a good time to bring consistency here?

As we all our `adds` actually do a _and or update_, maybe we could just use `saveObjects`/`saveObject` instead of the add and update methods? And an `updateObject` to do the `partialUpdate`? The naming actually make more sense to me, but considering the SDK history I'm unsure it is worth changing.

> // index keys
> index.keys.get(); // was index.getUserKeyACL
> index.keys.add(); // was index.addUserKey
> index.keys.update(); // was index.updateUserKey;
> index.keys.delete(); // was index.deleteUserKey;
> index.keys.list(); // was index.listUserKeys;

I would keep the same naming than I suggested for the client-level keys

**Comment by vvo** [comment]
> The client/index syntax tripped me up sometimes. I would like to be able to do index.rename, and index.clear directly from the index. I'm ok with keeping the top level list and the destructive delete on the parent client.

Yep we could do that but if we do it we should do it for every methods. It would bring again more inconsistency to have index methods being distributed between client and index objects with no real decision but making it harder to find "deleteIndex" on purpose.

> client.keys as a list to iterate on, but this won't be possible as this is just an object namespace.

Yes good point, that's a bold choice to make because if we keep .getKeys, .addKey, .updateKey then there's no more need to namespaces at all and we should not make .objects too.

> I'd keep the previous getSettings/setSettings,

Same concern than keys.*, clearIndex, deleteIndex, if we do not use namespaces everywhere then it will look weird and not consistent.

> First, I wonder about the name object.

I think it's ok, the whole Algolia records/objects are driven by "objectID" attribute, so having an object namespace feels consistent with the API.

> As we all our adds actually do a and or update, maybe we could just use saveObjects/saveObject instead of the add and update methods?

Yes I removed add and save to only provide save(). Algolia is only ADD OR UPDATE on objects. The automatic objectID creation being only triggered when there's no objectID provided (= ADD).

> And an updateObject to do the partialUpdate?

I like partialUpdate because it's descriptive that it's a partialUpdate, otherwise how to tell the difference between save() and update()? You will have to look at the documentation.

**Comment by vvo** [comment]
So I believe client.[move|delete|copy]Index are set on the client because once you use them you do not want to query the index again.

So index.move() won't work because you would have to then stop using the index object (it will fail). We could fix it, but it won't be a good idea.

**Comment by vvo** [comment]
This is not the API we will provide, was still nice to think about it.
