### ISSUE TITLE
Can "params" be disabled in the server response?

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-javascript#282]
The server response from Algolia includes a `params` attribute that contains the specific parameters that were sent to Algolia and used to generate the results. I would like to prevent this parameter from being sent back in the response from the server, for the following reasons:

1) It's not needed
2) It often represents 50% or more of the returned data
3) It could represent a security risk as since clients may see internal data that they otherwise should not

Would this be possible to do?

-Kyle

**Comment by vvo** [comment]
Hi @kylegibson, we understand your concern about that param and we will most probably add an option to disable it in the future.

This requires some changes on the API side, we will update that issue accordingly when done.

**Comment by Haroenv** [comment]
Hey @kylegibson, sorry for getting back to you this late, but I just found this issue again. You can use the `responseFields` parameter to leave out certain parameters: 

see the [documentation](https://www.algolia.com/doc/api-reference/api-parameters/responseFields/?language=javascript#responsefields) on that parameter. 

Let me know if it's working

**Comment by kylegibson** [comment]
Hello, that's great to hear! When I created this issue, I recall that `params` was always sent, regardless of how `responseFields` was set. I eventually submitted this as a request to my support contact directly, and a few months later, the API change was made. We started using the new feature immediately. It's been great! Thanks again!

**Comment by Haroenv** [comment]
Aha, that makes perfect sense
