### ISSUE TITLE
#Fail to install algoliasearch#

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [algolia/algoliasearch-client-javascript#295]
I want to use algoliasearch in my project. But when I use npm to install, there is an error!
npm ERR! **No compatible version found: debug-ms-fix-yui-compressor@2.2.2-future-reserved-word-fix-ms**
npm ERR! Valid install targets:
npm ERR! 2.2.0-future-reserved-word-fix-ms
I check the package of debug-ms-fix-ui-compressor, the latest version is @2.2.0. Why the dependency of algoliasearch is 'debug-ms-fix-yui-compressor': '2.2.2-future-reserved-word-fix-ms'?
I don't know how to fix this problem. Please help! Thanks

**Comment by vvo** [comment]
Hi @ZhiXingHeYiApple, I just did an `npm install algoliasearch` without any issue. Are you using the central npm repository or maybe a different one?

Thanks

**Comment by henryhuang** [comment]
@ZhiXingHeYiApple , I guest you use the no-official registry, such as taobao,  you could use following command to install (which fixed my problem like you):

``` shell
npm --registry https://registry.npmjs.org install algoliasearch --save
```
