### ISSUE TITLE
Add a note about the helper project in the Readme

### ISSUE THREAD

**Issue by vvo** [algolia/algoliasearch-client-javascript#340]
We need to talk about the helper in the JavaScript client documentation, a lot of people are still missing it and are building frontends only with the client.

**Comment by bobylito** [comment]
Love that! :)

**Comment by vvo** [comment]
This should be done in the doc project of Algolia

**Comment by Haroenv** [comment]
We should rather talk about InstantSearch though

**Comment by bobylito** [comment]
Why not both? I mean if you're using the client, you may want more control but not a UI library.

**Comment by Haroenv** [comment]
Yeah, that was my point, we should mention both enough.

**Comment by nunomaduro** [comment]
This should be tackled in this next coming days, as we are working in a new `shared` readme between all api clients.

**Comment by nunomaduro** [comment]
Done.
