### ISSUE TITLE
travis encrypt/secure variables

### ISSUE THREAD

**Issue by DevSide** [algolia/algoliasearch-client-javascript#356]
I looks like travis doesn't decode properly the secured variables. 
https://github.com/algolia/algoliasearch-client-js/blob/master/.travis.yml#L25

https://travis-ci.org/algolia/algoliasearch-client-js/builds/174771236#L2364

**Comment by vvo** [comment]
Hello! Travis is not decoding secured variables from outside of organizations forks: for security reasons. No big deal we will test it. There's no easy solution for that, some of our keys are really private
