### ISSUE TITLE
TypeScript Typings issue (Angular 2)

### ISSUE THREAD

**Issue by matthewjsummers** [algolia/algoliasearch-client-javascript#358]
It seems that there is a mismatch between the Typings file provided by @types/algoliasearch-client-js and the algoliasearch library itself.  Is anyone aware of this? We are struggling to import the algoliasearch function from the typings file into a TypeScript component - is the module definition correct?

**Comment by vvo** [comment]
cc @CBaptiste any idea? I did update the library at some point since the typings

**Comment by CBaptiste** [comment]
Hello @matthewjsummers !
What mismatch are you facing ? What error do you have ?

Let me know :)

**Comment by jsanchezgarcia** [comment]
Not sure if this is the same that @matthewjsummers is experiencing, but it seems that there's a mismatch between the AlgoliaClient.search interface in the typings file and the algoliasearch js file.

The js file search function takes an array of queries, but the typings takes a single query object.

**Comment by CBaptiste** [comment]
There is 2 search methods, one at index level that takes a query object, another one at client level that takes an array of object (to target several indices), which one are you talking about @jsanchezgarcia ? let me know :)

**Comment by mitchlloyd** [comment]
@CBaptiste I think this is the type in question where `queries` is defined as an object rather than an array: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/algoliasearch/index.d.ts#L66

And the code requiring an array is here: https://github.com/algolia/algoliasearch-client-javascript/blob/master/src/AlgoliaSearchCore.js#L505

Be aware that I'm just getting started with TypeScript so my diagnosis should be taken with a grain of salt.

**Comment by vvo** [comment]
Do we need any action on this right now?

**Comment by redox** [comment]
> Do we need any action on this right now?

The latest typings we've released are for the `3.18.0` version. We should release new typings with every single release.

**Comment by CBaptiste** [comment]
Ok I'll work on an automation script - I think it is possible

**Comment by ericzon** [comment]
Hi, I think there's another miss in @types/algoliasearch. I've installed all the nodejs + ts dependencies today and reading on the documentation I've found this:
[search-parameters](https://www.algolia.com/doc/api-client/javascript/search/#search-parameters)

If I try the second parameter using Typescript import, it claims about this, if I use old require, it works ok.

Thanks for your efforts

**Comment by davidallyoung** [comment]
Hi there, currently the latest typings file is 3.18.1 https://github.com/DefinitelyTyped/DefinitelyTyped/blob/10313510109698aff89860406b5f55d47122f59b/types/algoliasearch/index.d.ts#L1, which is leaving out some newer method definitions. Can we get a rebuild of the typings file?

Thanks!

**Comment by Haroenv** [comment]
I updated the typings, sorry for the wait 😄 see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20627

**Comment by davidallyoung** [comment]
Thanks @Haroenv !

**Comment by Haroenv** [comment]
Merged now, please open a new issue with any problems that occur
