### ISSUE TITLE
ttAdapter missing param in latest version?

### ISSUE THREAD

**Issue by mixergtz** [algolia/algoliasearch-client-javascript#361]
Hi @vvo 

I'm using algolia's `3.19.1`  along with typeahead `0.10.1`. After looking at the code I realized `ttAdapter` method is returning just:

`cb(content.hits);`

instead of: 

`cb(content.hits, content.nbHits);`

Is there any reason for leaving out the `nbHits` param?

Thanks! and great job with the library :)

**Comment by vvo** [comment]
Hi @mixergtz I do not remember we called `cb` with more than the hits in a previous version of this library. Can you provide me more context about "instead of: cb(content.hits, content.nbHits);"? Thanks

**Comment by mixergtz** [comment]
Sure, we were using a pretty old version of the library -> `2.5.1` 
This is the code for `ttAdapter` in that version:
```
        /*
         * Get a Typeahead.js adapter
         * @param searchParams contains an object with query parameters (see search for details)
         */
        ttAdapter: function(params) {
            var self = this;
            return function(query, cb) {
                self.search(query, function(success, content) {
                    if (success) {
                        cb(content.hits, content.nbHits);
                    }
                }, params);
            };
        },
```
`nbHits` provides the number of results of that query and passes it to this function in typeahead (`0.10.1`)
```
function renderIfQueryIsSame(suggestions, nbHits) {
  query === that.query && that._render(query, suggestions, nbHits);
}
```
And then it can be used in typeahead
``` 
return {
    source: index.ttAdapter(hitsPerPage: hitsPerPage)
    displayKey: "name"
    templates:
      header: (query) ->
        nbHits = query.nbHits
        if nbHits == 1
          message = "1 match"
        else
          message = nbHits + " matches"
        "<li class='search-object-header'>" + headerTitle + " (" + message + ") </li>"
      suggestion: (hit) ->
        template.render hit
    }
```
But if the `ttAdapter` function only returns ` cb(content.hits)`, in the typeahead code `query.nbHits` will return `null`

However the `renderIfQueryIsSame` function in typeahead doesn't seem to exist in the latest version so I don't know if adding the `nbHits` params affects something.

Maybe is there a different way of getting the `nbHits` (number of results) in the latest version of _algoliasearch_ in the `ttAdapter` function that I'm missing? or maybe should I update typeahead with the latest version?

Thanks again!!

**Comment by vvo** [comment]
Hi @mixergtz for now I would advise you to just code your own ttAdapter, like this for typeahead 0.10.

```js
var client = algoliasearch(...);
var ttAdapter = createTtAdapter(client);
var typeaheadSource = ttAdapter('indexName', params);

// now use typeaheadSource;

function createTtAdapter(algoliaClient) {
  return function(indexName) {
    var index = algoliaClient.initIndex(indexName);
    return function(query, cb) {
      index.search(query, params, function(err, results) {
        if(err) {
          console.error(err);
          cb(err);
          return;
        }

        cb(results.hits, results); // here we send all hits and the results
      });
    }
  }
}
```

I would not recommend you to switch to typeahead 0.11, it's not maintained and has many issues.

We also have https://github.com/algolia/autocomplete.js for you, a "better" more Algolia typeahead.

Let me know how it goes.

**Comment by Haroenv** [comment]
ttAdapter will be removed in v4. Please use `autocomplete.js` or open an issue for using v3 and you're having an error.
