### ISSUE TITLE
Unable to find algoliasearch typings

### ISSUE THREAD

**Issue by jsanchezgarcia** [algolia/algoliasearch-client-javascript#379]
When trying to install the typings according to the docs, they're not in the expected route. See error below
```
$ typings install dt~algoliasearch-client-javascript --save --global
typings ERR! message Unable to find "algoliasearch-client-javascript" ("dt") in the registry.
typings ERR! message We could use your help adding these typings to the registry: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/dt/algoliasearch-client-javascript/versions/latest responded with 404, expected it to equal 200
typings ERR!
typings ERR! cwd /Users/juansanchezgarcia/Projects/baro/baroapp-ionic
typings ERR! system Darwin 16.3.0
typings ERR! command "/usr/local/bin/node" "/usr/local/bin/typings" "install" "dt~algoliasearch-client-javascript" "--save" "--global"
typings ERR! node -v v6.9.1
typings ERR! typings -v 2.0.0
typings ERR!
typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

**Comment by vvo** [comment]
@CBaptiste Can you help on the typescript typings? Thanks

**Comment by snstarosciak** [comment]
I'm also having this issue. Any thoughts?

**Comment by jsanchezgarcia** [comment]
I was able to install using ``` typings install dt~algoliasearch --save ```. Although now I'm having problems using it in my Ionic 2 project

**Comment by snstarosciak** [comment]
Heh, I'm using this in my Ionic 2 project as well. Would you be able to show me how you're importing algolia into your project? Do you have it imported as a module in `app.module.ts`?

**Comment by CBaptiste** [comment]
Hey thx for reporting the issue, I ll update it hopefully by tomorow !

Baptiste

**Comment by CBaptiste** [comment]
Ok, apparently, a batch was run on several definition folders in the DT repo : https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12892

I ll investigate why tomorow but you should typings install `dt~algoliasearch --save`from now on @jsanchezgarcia @snstarosciak 

For the Ionic issue, what do you mean by "you are having problems" @jsanchezgarcia  ?

Let me know and I ll help :)

Baptiste

**Comment by snstarosciak** [comment]
@CBaptiste I appreciate the quick responses. I'm actually a bit of an impasse as I'm not sure how I should be integrating this npm module into my Ionic 2 application.

To try to get this to work, here's what I've done:

1. `npm install algoliasearch --save`
2. `typings install dt~algoliasearch --save`
3. I'm using Ionic 2, which utilizes webpack, so in my app.module file, I have tried to import the AlgoliaSearch module from Algolia, like so:
    `import { AlgoliaSearch } from 'algoliasearch';` - this gives me a typescript error saying that this has no exported member "AlgoliaSearch" - perhaps I'm doing something wrong here?
4. Assuming #3 works, I was planning on putting the following code in my `app.module.ts` file as well, to test to see if it even could run properly
   ```let client = AlgoliaSearch('<app-id>', '<api-key>');
    this.client = client;
    this.index  = this.client.initIndex('users');
    this.index.search('Cody', function searchDone(err, content) {
      console.log(err, content);
    })```

However, I'm stuck on #3. Is there anything else I can do?

**Comment by CBaptiste** [comment]
ok, that s weird, something must have broken somewhere after this PR.
I will reinspect/test the integration tomorow and I ll let you know !

**Comment by snstarosciak** [comment]
Awesome, thankyou so much :) But does it look like what I'm doing is correct, otherwise?

**Comment by CBaptiste** [comment]
yes you should only need to import it ! it is supposed to be a globals def

**Comment by snstarosciak** [comment]
Interesting. Well what's weird is that `node_modules/algolia-search/AlgoliaSearch.js` does export AlgoliaSearch, so I'm not sure why my import statement would say it's not an exported member. Could that be an issue related to typescript and the ts definitions for algoliasearch?

**Comment by snstarosciak** [comment]
@jsanchezgarcia Heh, I'm glad we're in this together :) It looks like we're running into issues very similar, at the very least. Are you including algolia in your project the way I am, as well?

**Comment by jsanchezgarcia** [comment]
yes, doing the same as you

**Comment by jsanchezgarcia** [comment]
Interesting. Just to make sure my error wasn't caused by something else in my ionic2 project, I just started a blank angular2 project from the cli, installed algoliasearch and its typings (as explained above), and when I try to ```import { AlgoliaSearch } from 'algoliasearch';``` I get a different error:
```[ts] Cannot find module 'algoliasearch'. ```

**Comment by jsanchezgarcia** [comment]
A bit more info about this. I'm able to do something like import { AlgoliaClient } from algoliasearch. I'm not familiar at all with typing files (yet), but it seems like we're importing the namespace algoliasearch with all the interfaces (AlgoliaClient, AlgoliaIndex, etc) but not the algoliasearch function

**Comment by CBaptiste** [comment]
Ok so, I haven't looked into Ionic yet but just for a general import
1. `typings install dt~algoliasearch --save`
2. `import algoliasearch = require('algoliasearch')`
I just quickly tested and it works fine

I am going to look specifically for Ionic now

**Comment by CBaptiste** [comment]
Ok indeed there is an issue with Ionic, I am on it

**Comment by CBaptiste** [comment]
Ok I got to import everything in a Ionic project.
1. instead of the typings command, just `npm install --save @types/algoliasearch` and that s it.
2. `import * as algoliasearch from 'algoliasearch'`

and then it compiles.

I am going to update the README right now, thx for reporting this guys

**Comment by snstarosciak** [comment]
Hey there @CBaptiste, thanks for looking into this. I've reproduced the steps that you outlined and now when I try to integrate the following code into my component, I get an error in my Ionic console:

`[10:10:20]  bundle failed: Cannot call a namespace ('algoliasearch')`

In my component, I have the following the code:

`import * as algoliasearch from 'algoliasearch'`

```
constructor(
  ) {

    /**
     *  Algolia searching
  */
    let client = algoliasearch('<app-id>', '<api-key>');
    this.client = client;
    this.index  = this.client.initIndex('users');
    this.index.search('Cody', function searchDone(err, content) {
      console.log(err, content);
    });
  }
```

I've also removed the `import { AlgoliaSearch } from 'algoliasearch';` related code from my @NgModule file. 

Outside of compiling, have you been able to actually call the service with an API key and what not? I'm excited to be able to get this to work and I'm sure I'm close :)

**Comment by CBaptiste** [comment]
Looking into it :)

**Comment by CBaptiste** [comment]
So yes, I can query.
For info, I used https://github.com/marcoturi/ionic2-boilerplate.

You said you were using webpack right ? what is your config ?

**Comment by CBaptiste** [comment]
ok so apparently it is a bundling process rollup issue when using the wildcard '*', it will make algoliasearch the module itself.
Try without it : `import algoliasearch from 'algoliasearch';`

Let me know !

**Comment by jsanchezgarcia** [comment]
I just tried @CBaptiste method  (with and without wildcard *) in a blank ionic project build with their cli, and even though I don't get compilation errors I get: ``` Runtime Error
Cannot read property 'prototype' of undefined ``` when trying to call algoliasearch as following ```let client = algoliasearch('SYO3YSE2C0', '6771017566787240e34ac840b6af9e3f');```

**Comment by snstarosciak** [comment]
Hm, when I try that, I'm getting this error now: 

```Uncaught ReferenceError: module is not defined
    at inherits_browser.js:3
    at algoliasearch.js:6

inherits_browser.js:3
```

When I refresh, I get a slightly different error:

```
Uncaught ReferenceError: module is not defined
    at inherits_browser.js:3
    at main.dev.ts:5
```

Ya know, one thing I may need to do is update my Ionic project. I actually based my project off of this one from a month and a half ago: https://github.com/driftyco/ionic-conference-app

Perhaps I need to start over with the ionic2-boilerplate project and then go from there? I'd say I'd get quite a few upgrades alongside of it right? I'm currently using the following in my package.json:

```
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "0.6.2",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "2.0.0",
    "@ionic/storage": "1.0.3",
    "ionic-angular": "2.0.0-rc.1",
    "ionic-native": "2.2.3",
```

**Comment by CBaptiste** [comment]
first @snstarosciak, I checked out the repo, and did what I did  before (`npm install --save @types/algoliasearch` and `import algoliasearch from 'algoliasearch';` in app.component.ts) and I was able to call algolia's service. I think it is linked to your dev environment ? What did you change, architecture wise between this repo and teh current state of your repo ?

**Comment by CBaptiste** [comment]
@jsanchezgarcia It looks like the file are not bundled/concatenated in the right order ? Would it be possible ?

**Comment by snstarosciak** [comment]
@CBaptiste hah no kidding, I did the same with that project and it works fine. In terms of architecture change, what do you mean exactly? It most likely is linked to my dev environment, though I'm not quite sure where to start nailing down the major differences. 

The major stuff I did was change some commonjs stuff in the rollup.config.js file, as well as pretty much gut the entirety of the app folder and replace it with components and pages that weren't based on the conference ones anymore.

**Comment by jsanchezgarcia** [comment]
Well, I was able to import and create the client using ionic2-boilerplate. I'll have to review what's different between that and my project. 

How are you guys making queries? When I try to 
```
let client = algoliasearch(xxx,xxxxx);
let search = client.search({indexName: 'items', query: 'xbox', options: {}}, (err, res) =>console.log(res)); ```

I get the following error: 
```Runtime Error
Usage: client.search(arrayOfQueries[, callback])```

And looking at the js file, it seems like search is supposed to take and array of queries, but in the typings file search just takes an object like the one I'm using above. Thoughts?

**Comment by vvo** [comment]
@jsanchezgarcia Can you open a different issue than this one? It's harder to follow discussion when we are mixing issues. As for a quick response, you need to provide an array of queries: [{}] and not {}.

Read more in the docs: https://github.com/algolia/algoliasearch-client-javascript#search-in-an-index---search

**Comment by vvo** [comment]
@snstarosciak Can you open a different issue maybe on the ionic or rollup repo? Maybe you'll get more help here. Right now this module works well but if you find a critical bug in using algoliasearch with a module bundler then dig it a bit and let us know what's wrong. Thanks!

**Comment by snstarosciak** [comment]
Hey guys, I ended up taking the ionic-conference-app repo and merging my current project into that one. With it, I'm able to successfully query against Algolia. I'm not sure what was wrong with my current build, but I was looking to upgrade my project to the latest Ionic 2 version, so we know that works, at least :)
