### ISSUE TITLE
Error when executing a simple request with Algolia 3.20.2

### ISSUE THREAD

**Issue by templth** [algolia/algoliasearch-client-javascript#391]
**Do you want to request a *feature* or report a *bug*?**

I think that it's a bug...

I try to use Algolia JS client 3.20.2 with Angular2 Universal (server rendering) and Express 4.14.0.

The versions of tools I use:

```
universal-cli: 1.0.0-alpha.universal.2-2
angular-cli: 1.0.0-beta.20-1
node: 6.9.2
os: linux x64
```

**What is the current behavior?**

When trying to execute the following code:

```
import * as algolia from 'algoliasearch';

const { appId, apiKey } = algoliaConfig;

const client = algolia(appId, apiKey).initIndex('indexName');

client.search('test').then(res => {
  console.log('res = ', res);
});
```

I have the following error:

```
TypeError: Cannot read property 'once' of undefined
    at ClientRequest.response (/../node_modules/algoliasearch/src/server/builds/node.js:180:9)
    at ClientRequest.g (events.js:291:16)
    at ZoneDelegate.invokeTask (/../node_modules/zone.js/dist/zone-node.js:265:35)
    at Zone.runTask (/../node_modules/zone.js/dist/zone-node.js:154:47)
    at ClientRequest.ZoneTask.invoke (/../node_modules/zone.js/dist/zone-node.js:335:33)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:474:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:363:20)
```

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

**Comment by vvo** [comment]
@templth I am unable to reproduce this and our integration testing passed for Node 6 (like Node 0.10 and 0.12 4 5 6 7): https://travis-ci.org/algolia/algoliasearch-client-javascript/builds/185027919#L366-L375

Could you dig this further and maybe provide a simple reproducible repository for me to test? Thanks

**Comment by templth** [comment]
@vvo thanks very much for your answer! I made some tests. It also works for me with Node only. In fact, I use Angular2 Universal and I think that the problem is linked to Zone that instruments code.

I have a look at the source code and changing the following code in the file `src/server/builds/node.js`:

```
    function response(res) {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(onCompleteTimeout, opts.timeouts.complete);
      var chunks = [];
      var originalRes = res;

      // save headers and statusCode BEFORE treating the response as zlib, otherwise
      // we lose them
      var headers = res.headers;
      var statusCode = res.statusCode;

      // Algolia answers should be gzip when asked for it,
      // but a proxy might uncompress Algolia response
      // So we handle both compressed and uncompressed
      if (headers['content-encoding'] === 'gzip' ||
          headers['content-encoding'] === 'deflate') {
        res = res.pipe(zlib.createUnzip());
      }

      res
        .on('data', onData)
        .once('end', onEnd);
```

to

```
    function response(res) {
      clearTimeout(timeoutId);
      timeoutId = setTimeout(onCompleteTimeout, opts.timeouts.complete);
      var chunks = [];
      var originalRes = res;

      // save headers and statusCode BEFORE treating the response as zlib, otherwise
      // we lose them
      var headers = res.headers;
      var statusCode = res.statusCode;

      // Algolia answers should be gzip when asked for it,
      // but a proxy might uncompress Algolia response
      // So we handle both compressed and uncompressed
      if (headers['content-encoding'] === 'gzip' ||
          headers['content-encoding'] === 'deflate') {
        res = res.pipe(zlib.createUnzip());
      }

      res
        .on('data', onData)
      res // <--------------
        .once('end', onEnd);
```

makes things work!

**Comment by vvo** [comment]
Ok then this is a "Zone" bug as I feared when I read your first stacktrace. Do you think you can forward/create this bug in the correct repo and link it here?

**Comment by vvo** [comment]
zone.js has many issues right now it seems: https://github.com/angular/zone.js (only fact, no judgement)

**Comment by templth** [comment]
I downgraded to version 0.6.21 of zone.js in my application and this fixed the problem ;-)

See this discussion as a reference: https://github.com/angular/universal-starter/issues/172#issuecomment-248515265. FYI version 0.6.26 doesn't fix the problem...

Thanks very much for your help!

**Comment by templth** [comment]
Closing my issue since it's not related to the Algolia client itself...

**Comment by vvo** [comment]
Nice!
