### ISSUE TITLE
docs(places): Missing documentation for `initPlaces`

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-javascript#394]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The documentation does not mention how to use Algolia Places with the JS Client.

**What is the expected behavior?**
There should be some documentation about the `initPlaces` method. Algolia Places needs special treatment as the API can be accessed without apiKey nor indexName.

Here is a sample code on how to use it:

```javascript
var algoliasearch = require('algoliasearch');
var places = algoliasearch.initPlaces(/*appId, apiKey*/);
places.search();
```

**Comment by vvo** [comment]
@maxiloc How could I add a specific section in Advanced of the JS client about Algolia Places usage?
