### ISSUE TITLE
forwardToReplicas should be used instead of forwardToSlaves

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-javascript#395]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The current API of `saveSynonym` expect a `forwardToSlaves` parameters. In regards to our internal renaming, it should now be reflected as `forwardToReplicas`. The change is already available on the REST API.

**What is the expected behavior?**
`forwardToSlaves` should be renamed to `forwardToReplicas` and the documentation should advocate for using `forwardToReplicas`. `forwardToSlaves` should still work as an alias but should display a deprecation warning.

**Comment by vvo** [comment]
done
