### ISSUE TITLE
Trying to getObjects on a list with one unauthorized object fails strangely

### ISSUE THREAD

**Issue by vincentwoo** [algolia/algoliasearch-client-javascript#472]
If you attempt to do `index.getObjects` on a list of object IDs, and the requesting client is not authorized to view one of those objects, but is okay to view the rest, the JS client throws:

`Method not allowed with this API key (nbObjects > hitsPerPage)`

which is very cryptic and took me a while to track down. Can we change the behavior to just return as many objects as are allowed, or barring that, at least make the message more helpful? There's no way to route around damage besides just trying to query each object individually currently.

**Comment by vvo** [comment]
Hi @vincentwoo this message is not actually coming from the JS client but from the actual API. Could you send a support request to Algolia so an API engineer can have a look? Thanks!
