### ISSUE TITLE
TypeError: initialOpts.callback is not a function

### ISSUE THREAD

**Issue by lommaj** [algolia/algoliasearch-client-javascript#489]
I am using algolia search client on a google cloud function in a pretty basic way.

```javascript
return new Promise(function(resolve, reject) {
    index.saveObject({
      objectID: user.uid,
      displayName: user.displayName,
      photoUrl: user.photoUrl
    }, 'myID', function(err, content) {
      if(err){
        reject(err);
      }else{
        resolve(content.objectID);
      }
    });
  });
```

The logs in algolia seem fine, its returning 200 and the data is being updated.

However the logs for the server are reporting the following:
`TypeError: initialOpts.callback is not a function
    at Timeout._onTimeout (/user_code/node_modules/algoliasearch/src/AlgoliaSearchCore.js:429:21)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)`

I realize I cant offer much info, there is no local debug environment for the particular system im using, but perhaps on that line we can do something like:

```javascript
if (typeof(initialOpts.callback)==="function") {
```

**Comment by vvo** [comment]
Hi @lommaj, indeed the signature of saveObject is:

```js
index.saveObject(object[, callback]) => Promise
```

So you should call:
```js
index.saveObject({objectID: ...}).then();
```

Rather than

```js
index.saveObject({objectID: ...}, 'myID').then();
```

Also all our methods are returning Promises when you do not pass a callback, so there's never a need to wrap around new Promise when using the module with Promises.

```js
return  index.saveObject({
      objectID: user.uid,
      displayName: user.displayName,
      photoUrl: user.photoUrl
    }).then(function(res) {
      return res.objectID;
    }).catch(function(err) {
      console.error(err);
    });
```

**Comment by vvo** [comment]
Let me know if the usage you tried to use was referenced somewhere so we can update the documentation.

**Comment by lommaj** [comment]
Thanks, I must have gotten it from some old docs, if I come across them again I will let you know!
