### ISSUE TITLE
Let the user specify a custom user-agent when a request is triggered

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-javascript#493]
Currently the only way to add a new user agent is by using the method `addAlgoliaAgent` on the client instance. However autocomplete.js does not have access to the client but only to an index instance. To solve this, it would be perfect if we could set the user agent directly when the request is sent.

For now this is only required for searching (autocomplete.js)

## Proposal

Since it's only required for search and the ability not documented, we could implement a new method (to limit the complexity of the signature of the function):

```js
var maybeResults  = index.searchWithAlgoliaAgent('my new fancy agent', 'query');

index.searchWithAlgoliaAgent('my new fancy agent', 'query', (err, results) => {console.log(err, results);});
```

WDYT?

**Comment by bobylito** [comment]
Alt. proposal, use `x-algolia-agent` in params. Right now, it's ignored but we can append its content to the ua. (seen with @vvo)

**Comment by Haroenv** [comment]
now part of requestOptions: #590

**Comment by Haroenv** [comment]
```js
index.search(
  {
    query: "...",
  },
  {
    requestOptions: {
      userAgent: 'InstantSearch for dogs (v1)',
    },
  }
);
```

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we took into consideration all those points.
