### ISSUE TITLE
Requiring algoliasearch.parse.js breaks gulp-istanbul test coverage.

### ISSUE THREAD

**Issue by majidhassan** [algolia/algoliasearch-client-javascript#494]
Hello,

I'm using Algolia search with parse-server. I've added tests using gulp-mocha and gulp-istanbul. Istanbul is a tool that keeps track of test coverage, everything worked fine until I added a module, that requires the algoliasearch.parse.js model. Ever since I can't seem to get any coverage on my files. Any ideas how I could fix this?

Environment
Ubuntu 14.04.5 LTS on DigitalOcean
Parse-Server 2.3.2
Algolia Parse Client 3.18.1
gulp@3.9.1
gulp-mocha@3.0.1
gulp-istanbul@1.1.1

**Comment by vvo** [comment]
Hello @majidhassan I have very little to no-knowledge of parse-server related issues unfortunately.

This is the parse related code we have: https://github.com/algolia/algoliasearch-client-javascript/blob/3cf5304d120d894afb88980f597da097df17a830/src/server/builds/parse.js

If I understand well, as soon as you include our algoliasearch.parse.js your code coverage does not reports anymore coverage?

If so what you could do is comment some code in algoliasearch.parse.js and then see what can go wrong. Thanks!

**Comment by majidhassan** [comment]
Hey @vvo thanks for replying.

The problem is indeed with adding the Algolia model. Is there any code in particular that I should comment out in the algoliasearch.parse.js file, that you think might be causing this problem?

I don't think I will be able to easily pinpoint which function - if any - might be causing this by going over 3K+ lines of code. Hence, pointing me in any direction could be helpful.

**Comment by majidhassan** [comment]
@vvo I narrowed it down to 4 functions, that might be causing this issue. Meaning, that the coverage works well when removing these 4 functions, of course the Algolia model itself doesn't work that way, but at least I get some coverage.

Could you look at them and check, if there's an obvious issue causing these?

Function 0: https://github.com/algolia/algoliasearch-client-javascript/blob/master/dist/algoliasearch.parse.js#L45

Function 1: https://github.com/algolia/algoliasearch-client-javascript/blob/master/dist/algoliasearch.parse.js#L187

Function 6: https://github.com/algolia/algoliasearch-client-javascript/blob/master/dist/algoliasearch.parse.js#L844

Function 7: https://github.com/algolia/algoliasearch-client-javascript/blob/master/dist/algoliasearch.parse.js#L1308

Let me know, if there's anything else I could do.

**Comment by majidhassan** [comment]
Hey @vvo I dug deeper into each of those functions and found that [this line ](https://github.com/algolia/algoliasearch-client-javascript/blob/master/dist/algoliasearch.parse.js#L63)causes the error. Seems gulp-istanbul doesn't like the Algolia model overriding the globals. Let me know if commenting out that line is enough, or if there's another way to do it.

**Comment by vvo** [comment]
> or if there's another way to do it.

Yes I think we should try to detect the presence of the "global" keyword, if preset and has a value: keep it, otherwise, create it.

**Comment by vvo** [comment]
I will do an update, in the meantime you can remove this line from your file, works?

**Comment by majidhassan** [comment]
@vvo Yeah, I guess that would work. If "global" exists just add to it, if not create it. Meanwhile, it does pass while commenting out that line. I will still check if everything Algolia related still works in my code.

**Comment by vvo** [comment]
Can you try:

```js
global = global || {};
```

Let me know if this works.

**Comment by majidhassan** [comment]
Yep, this works!

**Comment by vvo** [comment]
Ok pushed this to the repo, will be released this week as there will be a new JS client version. In the meantime you are safe doing it on your side. Thanks a lot for feedback!

**Comment by majidhassan** [comment]
Great! Thanks for handling this quickly!
