### ISSUE TITLE
Add a note about the CSP in the Readme

### ISSUE THREAD

**Issue by HZ-labs** [algolia/algoliasearch-client-javascript#502]
What Content Security Policy we should use for Algolia js client?

**Comment by vvo** [comment]
Hi @HZ-labs, I did not get exactly what you were asking for, are you having any issue with using Algolia and the JavaScript client right now?

If so can you give me some code samples you are using that are not working? Thanks.

**Comment by asurak** [comment]
The XHR whitelist is:
```
connect-src https://*.algolia.net https://*.algolianet.com;
```

**Comment by HZ-labs** [comment]
@asurak Thanks! It would be useful to include the rules into documentation
