### ISSUE TITLE
Algolia backend - If number is stored as string it still reads as number

### ISSUE THREAD

**Issue by dealharris** [algolia/algoliasearch-client-javascript#526]
If a number is stored as string in your backend it still reads as a number. 

I found this out because my disjunctivefilters dont work.

**Comment by vvo** [comment]
Hi @dealharris thanks for reporting this, could you give us a more detailed bug report by maybe creating a small jsFiddle that will demonstrate what is the issue you are facing with Algolia and the JavaScript client?

Thanks

https://jsfiddle.net/

**Comment by Haroenv** [comment]
Hey, I'm cleaning up the issues, and closing this because there hasn't been any activity in over 6 months. Feel free to reopen with more information!
