### ISSUE TITLE
Reduce module size

### ISSUE THREAD

**Issue by kievechua** [algolia/algoliasearch-client-javascript#527]
When checking module size, found out 1 gif file taken almost 1mb.
/examples/instantsearch.gif
![screen shot 2017-03-02 at 10 25 12 am](https://cloud.githubusercontent.com/assets/275206/23490456/b0534da2-ff33-11e6-9737-176e8218ed96.png)

Can we optimize or exclude it from npm?

**Comment by vvo** [comment]
Need to also keep LICENSE, README, CHANGELOG and bower.json (not sure but let's not break anything).

**Comment by Haroenv** [comment]
LICENSE, README, CHANGELOG are kept by default, bower.json not, so I just added it

**Comment by vvo** [comment]
> LICENSE, README, CHANGELOG

Did not know that, thx

**Comment by Haroenv** [comment]
reference: https://docs.npmjs.com/files/package.json#files
