### ISSUE TITLE
algoliasearch/lite is 300b bigger than algoliasearch

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#529]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Happens on https://github.com/algolia/yarnpkg-website/pull/8

the vendor.hash.js file is 300b bigger when `import algoliasearch from 'algoliasearch/lite'` is used than when `import algoliasearch from 'algoliasearch'` is

**What is the expected behavior?**

it to be a significant amount smaller

**ideas**

Maybe we can add a `module` field (although the `browser` field takes precedence, so need to think about that) like we'll do in https://github.com/algolia/instantsearch.js/issues/1725#issuecomment-283088858

cc @vvo

**Comment by vvo** [comment]
This is because you are duplicating the search client (one is inside instantsearch, other one is added by you). I have no solution for this, but 300b out of 100Kb is OK I guess.

**Comment by Haroenv** [comment]
Since this can't be fixed at this level, closing.
