### ISSUE TITLE
index.addObjects isn't working for large array objects

### ISSUE THREAD

**Issue by Dev-Dipesh** [algolia/algoliasearch-client-javascript#532]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
We've to index a large number of array objects as a batch to Algolia. `index.addObjects` fails when I tried to add **33k+** records.

**What is the expected behavior?**
The best way for this will be to provide a streaming support, but for that, you have to change both library and backend APIs, so here is a simpler and much more reliable solution that you can use instead of current for loop in your batch upload:

```js
const Promise = require('bluebird');
const _ = require('lodash');
const data = require('./data.json');

const chunkSize = 500;
const maxConcurrency = parseFloat(process.argv[2] || "Infinity");

const chunks = _.map(data, (chunk, index) => {
  return index % chunkSize === 0 ? data.slice(index, index + chunkSize) : null; 
})
.filter(chunk => {
  return chunk; 
});

console.time(`Batch indexing!`);
Promise.resolve(chunks).map((chunk, index, length) => {
  console.log(`CHUNK | INDEX | LENGTH\n`);
  console.log(chunk, index, length);
  console.log(`\n================================\n`)
  return null;
}, { concurrency: maxConcurrency })
.then(() => {
  console.timeEnd(`Batch indexing!`);
})
.catch(e => {
  console.log(e);
});
```

It inserts in bulks using chunks of size **500** each with concurrency. I've tested this with **33K+** records on concurrency **1** and it took **1.4`s`** to index all the records. You can change the concurrency or chunk size as per your server.

**Comment by vvo** [comment]
Perfect! Thanks! That's the way to go indeed, chuking and controlling concurrency. We could do this internally maybe at some point. Not yet planned.

**Comment by iam4x** [comment]
@Dev-Dipesh fyi you have [_.chunk](https://lodash.com/docs/4.17.4#chunk) directly implemented into lodash 👍

**Comment by Dev-Dipesh** [comment]
@iam4x yup totally missed that :sweat_smile:
