### ISSUE TITLE
Option to have every facet returned, even if results for that facet are 0

### ISSUE THREAD

**Issue by jasonbarry** [algolia/algoliasearch-client-javascript#541]
It would be useful to specify an option in algoliasearch where all available facets would return, even if there were 0 in the matching result set. The non-matched keys would also be present in the `facets` key in the response, too.

**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Imagine the following fruit category is faceted: 

- [ ] Apples (18)
- [ ] Bananas (7)
- [ ] Cherries (20)

Assuming that each record only had one fruit in it, clicking on "Apples" would result in the following checklist: 

- [x] Apples (18)

**What is the expected behavior?**

My feature request would have the checklist result as the following: 

- [x] Apples (18)
- [ ] Bananas (0)
- [ ] Cherries (0)

**Comment by seafoox** [comment]
👍 Doing that it would then be possible to disable click event on those with count == 0, but still display those.

**Comment by vvo** [comment]
@jasonbarry We are currently discussing this internally, it requires new API features but we are investigating it. Thanks for very detailed feedback!

**Comment by cgcullen** [comment]
Also asked for on Discourse: https://discourse.algolia.com/t/option-to-keep-all-options-while-refining-lists-and-menus/8752

**Comment by Haroenv** [comment]
Here’s two workarounds: 

https://codesandbox.io/s/instantsearchjs-facets-with-count-of-0-pk62m

https://codesandbox.io/embed/instantsearchjs-facets-with-count-of-0-nmijp?codemirror=1

And it’s in the docs too:

https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/

Cc @francoischalifour

**Comment by nunomaduro** [comment]
Nothing to be done on the API Client side. Seems that may be something todo on the engine or at the instantsearch level.

**Comment by seafoox** [comment]
Here is a customWidget @tvweinstock created last year https://codesandbox.io/s/jl3ykyqrw3
![image](https://user-images.githubusercontent.com/1101220/73638124-1ae64e00-466a-11ea-989c-9bc7d7302c31.png)

It's been used by a few customers, incl. Nintendo on their web portal, but we never added it to the InstantSearchLabs https://github.com/algolia/instantsearch-labs. Might be the next step we want to take so it can be more accessible to more users.

Interested in hearing your thoughts.

**Comment by francoischalifour** [comment]
@seafoox We recently wrote guides about ["Display facets with no matches"](https://www.algolia.com/doc/guides/building-search-ui/widgets/customize-an-existing-widget/js/#display-facets-with-no-matches). Your feedback on those would be valuable.
