### ISSUE TITLE
Flow type definitions

### ISSUE THREAD

**Issue by SamyPesse** [algolia/algoliasearch-client-javascript#542]
By default, [Flow](https://flowtype.org/) will ignore the libraries with missing type definitions leaving them untyped. As a result, Flow can't give errors if we accidentally mis-use the library (nor will it be able to auto-complete the library).

It'd be awesome to have type definitions for `algoliasearch` added to [`flowtype/flow-typed`](https://github.com/flowtype/flow-typed).

Since we are using both Flow and Algolia for a special project at GitBook, we've added in our repository **very basic** type definitions for `algoliasearch`: https://gist.github.com/jpreynat/79628251790c014c349867f63583d927#file-algoliasearch-js

**Comment by vvo** [comment]
We also have the same need for TypeScript, my main struggle being how do we automatically maintain those files with the code. I'd rather not have to manually update multiple type definitions when they are updated. Right now I do not know how to do it.

**Comment by Haroenv** [comment]
v4 will have flow definitions.

**Comment by vvo** [comment]
... and typescript? :D

**Comment by Haroenv** [comment]
Will not be automatic, but the ones that exist will be updated

**Comment by nunomaduro** [comment]
The v4 is developed in typescript.
