### ISSUE TITLE
How to send multiple query strings to Algolia for search in multiple fields

### ISSUE THREAD

**Issue by kati-frantz** [algolia/algoliasearch-client-javascript#547]
I don't know if this is already possible with algolia, but the docs didn't help. Can I make queries , specifying multiple search queries for different fields in my objects ? For example, I want my users to type in a pickup address, and a drop off address . Can I ask algolia to search for the records where pickup address match with query string for pickup , and the drop off address matches the query string for drop off ? Is this possible ? Thank you for an enlightenment !

**Comment by vvo** [comment]
Hi @kati-frantz, this is not a particular issue of the JavaScript client but more of a generic question on how to use Algolia to do X.

I would advise you to post this question, with a bit more context on what you are building and what you would want to use Algolia for, on our discourse forum: https://discourse.algolia.com/c/development

Thanks a lot!
