### ISSUE TITLE
Parameters not being used?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [algolia/algoliasearch-client-javascript#548]
I'm doing

```js
  return algolia.search([
    {indexName: 'index1', query:'something', getRankingInfo:true},
    {indexName: 'index2', query'something', getRankingInfo:true},
  ])
```

And the hits are not coming back with _rankingInfo. Are the params properly being sent in multi-mode? Am I doing anything else wrong?

**Comment by vvo** [comment]
Sorry that's a little bit odd to do that right now, we did a 1:1 mapping with the REST API in term of parameters:

```js
  return algolia.search([
    {indexName: 'index1', params: {query:'something', getRankingInfo:true}},
    {indexName: 'index2', params: {query:'something', getRankingInfo:true}},
  ])
```

Let me know if that works.

Ref: https://www.algolia.com/doc/api-client/javascript/search/#search-multiple-indices

**Comment by GeoffreyPlitt** [comment]
That worked, thanks!
