### ISSUE TITLE
Discrepancy in iOS callbacks and Javascript callbacks search

### ISSUE THREAD

**Issue by arpit2438735** [algolia/algoliasearch-client-javascript#553]
Hi Folks,

I am creating nativescript-algolia. While I am developing the plugin.I found the callback are returning in different signature for iOS and Javascript.

For iOS the callback is 
```
index.search(Query(query: "jimmie"), completionHandler: { (content, error) -> Void in
	if error == nil {
		print("Result: \(content)")
	}
})
```

and for javascript is 

```
index.search('jimmie', function(err, content) {
  console.log(content.hits);
});
```
Can we have same signature of callback across both libraries.It's just a suggestion

**Comment by Haroenv** [comment]
In JavaScript this order was specifically switched to be more consistent a long time ago. This might be a nice feature request for the iOS library, which you better ask there. 

Thanks a LOT for your work on nativescript. It's an area where we're missing some integration right now

**Comment by vvo** [comment]
@arpit2438735 We did it this way in JavaScript because that's also the way Node.JS APIs are made. It's not a standard only the most common way to do it.

If the one in iOS is different and not the one the community will expect then let us know.

**Comment by arpit2438735** [comment]
@vvo Sure, yeah you are right Node.JS API does work like that.I posted question/suggestion in wrong repo

**Comment by Haroenv** [comment]
Good luck making your project, and don’t hesitate to reach out if you need any more help!

**Comment by vvo** [comment]
Yes @arpit2438735 ultimately we WANT to support nativescript, multiple people have been trying to do it/asking for native script support. The truth is that our JavaScript client SHOULD be compatible but native script is missing some parts that react native have that makes it harder to have native script support.

Ultimately we would be very happy to host that nativescript client on algolia/ and document it and make it a project between you and us.

If you need any help, review, let us know. Where's the repo?

**Comment by arpit2438735** [comment]
Thanks for your help.
Here's the repo link https://github.com/arpit2438735/nativescript-algolia
Right now it's very basic. I am adding more functionality and documentation,I am also  try to expose function convention same as Javascript so I adding a sort of layer on top of Algolia Swift for iOS as a first cut then will move to Android.If you want to contribute I will be more happy and can add in algolia itself

**Comment by arpit2438735** [comment]
Hi @vvo I added basic search functionality for both iOS and Android device.Do you want to host the repo in `angolia` itself so that every can contribute?

**Comment by arpit2438735** [comment]
Hi @vvo @Haroenv Any update or decision on moving the repo or shall I go ahead and push to `npm` registry?

Do you guys have any credentials for testing the api's, as my free credentials has been expired?

**Comment by Haroenv** [comment]
hey, could you send an email to support+js@algolia.com so we can handle that? Have a great day!
