### ISSUE TITLE
i want to use lazy load code instead of pagination.

### ISSUE THREAD

**Issue by mdsaif786** [algolia/algoliasearch-client-javascript#554]
Hi Algolia Team Member,
1) I want to use lazy load code front end but I am unable to find lazy load code.
2) i need image fixed height and width.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

**Comment by Haroenv** [comment]
Did you try [infinite hits](https://community.algolia.com/instantsearch.js/documentation/#infinite-hits) in InstantSearch.js or [React InstantSearch](https://community.algolia.com/react-instantsearch/widgets/InfiniteHits.html)? 

You can look at the implementation of infinite hits there, if you prefer doing it manually.

**Comment by vvo** [comment]
Hi @mdsaif786 thanks for feedback and question.

This repository is to open feedback and issues on the Algolia JavaScript API client.

If you have issues building your search UI with instantsearch.js, ask on stackoverflow or on our discourse forum: https://discourse.algolia.com/c/q-and-a

**Comment by mdsaif786** [comment]
No.I want to implement in javaScript....that why i asking here.

**Comment by vvo** [comment]
@mdsaif786 If you want to implement infinit loading of hits using JavaScript, can you re-ask your question on the discourse forum? https://discourse.algolia.com/c/q-and-a

This repository is really to open bugs or feature request, while you have a more generic question on how to do X with Algolia. That's completely fine but you need to use the discourse forum or even StackOverflow.

Do not hesitate to be as descriptive as possible in term of what you want to achieve and what you tried, right now it's too blurry to be able to help you.

Thanks.
