### ISSUE TITLE
Remove es6-promise dependency

### ISSUE THREAD

**Issue by gajus** [algolia/algoliasearch-client-javascript#555]
https://github.com/algolia/algoliasearch-client-javascript/blob/a7513621e04c855768f9bb42bdab7ddd7dd36d6a/package.json#L63

It is not your (as a library) responsibility to polyfill browser features. If you must use promises, document the requirement and require that the consumer of the library polyfills the feature.

**Comment by gajus** [comment]
As a workaround, a webpack consumer can define an alias that resolves to an empty module, e.g. `{alias: {'es6-promise': 'empty-module'}}` (and install `empty-module` module).

**Comment by vvo** [comment]
@gajus You are totally right. [When we built the new version of the JavaScript client](https://blog.algolia.com/modern-javascript-libraries-the-isomorphic-way/), not a single environement was supporting Promises by default.

But we still wanted to push that API to consumers without having them to Polyfill Promises that we knew would be available at some point.

We have many ideas on how to again do a modern-pass on the JavaScript client and will keep you updated when this is done.

**Comment by daniel-nagy** [comment]
Came here to say the same thing. Ending up with two promise libraries in my application bundle.

**Comment by lukeed** [comment]
I'd love to see the `"engines.node": ">= 0.8"` being addressed as well. That was marked stable back in 2012-2013. And Node 0.10.x moved _out of_ LTS and _into_ "End of Life" status in 2016. I can't even find when 0.8.x was terminated. 

This may be the most-used and most all-encompassing lib I've found 😆So much room/opportunity to slim down this awesome sdk

**Comment by Haroenv** [comment]
Don't worry, we are currently working on making a brand new version, which of course won't support node 0.8. We've historically been very careful with breaking support for older engines in this library, and therefore didn't have the major version chance of changing support.

This is going to change once that is completely rethought (there's a lot of assumptions in this library that need to be considered), but until then the best option is to indeed just alias it for an empty module.

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we took into consideration all those points.
