### ISSUE TITLE
Do not hardcode a specific version of debug

### ISSUE THREAD

**Issue by gajus** [algolia/algoliasearch-client-javascript#556]
https://github.com/algolia/algoliasearch-client-javascript/blob/a7513621e04c855768f9bb42bdab7ddd7dd36d6a/package.json#L61

This results in duplicate "debug" package across the entire codebase. Just target `^2`.

**Comment by Haroenv** [comment]
Thanks for your continued investigation, this seems like an obvious change. Feel free to do a pull request for this. 

Is there a specific reason for this pinned version @vvo ?

**Comment by vvo** [comment]
At some point this failed in react native because of debug. I believe now this should be solved. Let's try
