### ISSUE TITLE
prepareHost is being called with an array; results in t.toLowerCase is not a function error

### ISSUE THREAD

**Issue by gajus** [algolia/algoliasearch-client-javascript#560]
I am not able to consistently reproduce the issue. However, somehow this part of the code:

https://github.com/algolia/algoliasearch-client-javascript/blob/ebac7544d6994997191c56002b8cdff53c8f3cbb/src/AlgoliaSearchCore.js#L726-L730

gets called with an array instead of a string.

I have added `console.log`:

```js
function prepareHost(protocol) {
  return function prepare(host) {
    console.log('host', host);
    return protocol + '//' + host.toLowerCase();
  };
}

```

I can the first invocation:

```js
host 07QFUIN3KT-dsn.algolia.net

```

followed by:

```js
host (3) ["07QFUIN3KT-3.algolianet.com", "07QFUIN3KT-2.algolianet.com", "07QFUIN3KT-1.algolianet.com"]

```

Weirdly, this is happening only in a webpack bundle thats minified using Babili (which makes it near impossible to debug).

**Comment by gajus** [comment]
Upon closer inspection, the problem is that [here](https://github.com/algolia/algoliasearch-client-javascript/blob/ebac7544d6994997191c56002b8cdff53c8f3cbb/src/AlgoliaSearchCore.js#L109), the value of `this.hosts.read` and `this.hosts.write` is:

```js
this.hosts.read (2) ["07QFUIN3KT-dsn.algolia.net", Array(3)]
this.hosts.write (2) ["07QFUIN3KT.algolia.net", Array(3)]

```

whereas it is clear from the rest of the code that it should be a flat list.

**Comment by gajus** [comment]
Turns out it is Babili issue.

Here is the relevant bug report:

https://github.com/babel/babili/issues/583

**Comment by vvo** [comment]
Wow thanks for the bug inspection, minifiers are tricky :)

**Comment by Haroenv** [comment]
After reading that Babili issue, it’s not clear to me if that fix is already released, and upgrading helped you or are now not using babel anymore @gajus

**Comment by gajus** [comment]
It is not fixed. You need to disable "evaluate" plugin. See:

https://github.com/babel/babili/tree/master/packages/babel-preset-babili#options

If you are using Babili via webpack, you can disable it as such:

```js
new BabiliPlugin({
  // @see https://github.com/algolia/algoliasearch-client-javascript/issues/560
  evaluate: false
}),

```
