### ISSUE TITLE
Use fetch over XHR

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-javascript#561]
Looking at PWA specs, it seems that XHR's won't be supported. If we want to be to some extent compatible, we should use it by default and fallback when needed. This will only be necessary for search queries.

 - [ ] check the API of fetch and the compatibility with XHR one
 - [ ] implement on search operations

This could be done when making the minimal client (one that has only a few functions for search)

**Comment by vvo** [comment]
Definitely something to look at, thanks !

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we took into consideration all those points. We decided to keep `XHR`.

**Comment by richtera** [comment]
Argh that means the library is not usable in many scenarios. Hmmm.

**Comment by Haroenv** [comment]
We have a fetch requester available now as well @richtera: https://github.com/algolia/algoliasearch-client-javascript/tree/master/packages/requester-fetch

the reason we stayed with xhr is that there's still a decent amount of supported platforms at the time of release of v4 that wouldn't work with only fetch

**Comment by Haroenv** [comment]
Yes you can @richtera, you can use the fetch requester I linked :)

**Comment by richtera** [comment]
NICE, that what I ended up doing. I just used the REST api. Very cool.

**Comment by Haroenv** [comment]
All right, just so you know, you can use the fetch requester without using the REST API like this:

```js
import { createFetchRequester } from '@algolia/requester-fetch'
import algoliasearch from 'algoliasearch'

const client = algoliasearch('', '', { requester: createFetchRequester() })
```

as documented here: https://www.algolia.com/doc/api-client/getting-started/customize/javascript/?client=javascript#changing-http-request-methods

**Comment by richtera** [comment]
That's great!

**Comment by lcnogueira** [comment]
Thanks for taking the time to give such detailed answers, @Haroenv . Just helped to solve the issue on my client project.
