### ISSUE TITLE
warning react-instantsearch > algoliasearch > isarray@2.0.1: Just use Array.isArray directly

### ISSUE THREAD

**Issue by khrome83** [algolia/algoliasearch-client-javascript#565]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When install `react-instantsearch`, this node module is installed, which provides the following warning.

warning react-instantsearch > algoliasearch > isarray@2.0.1: Just use Array.isArray directly

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

Create repo with `algoliasearch` or `react-instantsearch` as a dependency in package.json
Run `yarn install`.
> `npm install` may not show as good of feedback

**What is the expected behavior?**

Should see no warning about the array behavior. Just switch from using `isarray` package to `Array.isArray` native. This will remove the warning.

**Comment by khrome83** [comment]
I did search for the issue, but it was not showing for me. I am guessing because it was in a closed PR.  #546 

I caught up with the state of things. I understand the IE8 support, but I agree with the MR that a simple polyfill would be ideal over a external dependency.

The reason this hurts, is because this library is a dependency of `react-instantsearch` which is suppose to be pretty new codebase. Seems strange to have IE8 legacy code along for the ride in this other library. 

Leaving this open so I get see the state of things with this issue, and how the dev team feels. Please close once you comment. =)

**Comment by Haroenv** [comment]
We're doing a rewrite of this library in this quarter, which will take care of this. Closing in favour of #195 

Have a great day 😄

**Comment by khrome83** [comment]
ok sounds good. Thank you so much @Haroenv
