### ISSUE TITLE
README broken link

### ISSUE THREAD

**Issue by bondarewicz** [algolia/algoliasearch-client-javascript#568]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When user clicks on 500 contacts link within [Push data](https://github.com/algolia/algoliasearch-client-javascript/blob/master/README.md#push-data) section, no content is displayed

**What is the expected behavior?**
When user clicks on 500 contacts link within Push data section he/she should be presented with `contacts.json` file contents

**Comment by Haroenv** [comment]
Thanks for noticing that, the current link is https://github.com/algolia/datasets-public/blob/master/contacts.json

**Comment by Haroenv** [comment]
By the way, don't forget to also check out [react-instantsearch](http://community.algolia.com/react-instantsearch/) or [instantsearch.js](http://community.algolia.com/instantsearch.js/v2)!
