### ISSUE TITLE
406 - Client browser does not accept the MIME type of the requested page.

### ISSUE THREAD

**Issue by fephil** [algolia/algoliasearch-client-javascript#574]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a hybrid Cordova app and I am getting occasional error reports from Sentry.JS when a user performs a query. The error is "AlgoliaSearchUnparsableJSONError" and in the error data I'm getting the 406 error as seen in the title. It's very sporadic, maybe 1 in 100 and I've seen it on Chrome 59, the latest Android WebView version.

See attached screenshot for a partial copy of the debug data.

![image](https://user-images.githubusercontent.com/1689044/28419024-b8f39cd8-6d55-11e7-88b3-6c90f500315f.png)

If this is too vague, happy to try and help clarify further.

Thanks.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

**Comment by Haroenv** [comment]
This seems odd, can you add some code to replicate it? It's definitely not an Algolia response I've seen before, our errors are JSON, not html

**Comment by fephil** [comment]
Hi. In short, no. We've had many many successful queries in Algolia so it might be even be 1 in 1000 this has happened. The error log was from an Android 5.0.1 device with Chrome 59. It could be an internal WebView error which is why HTML has appeared in the debug logs.

I'm happy to mark this as a weird fringe issue but I wondered if you had experienced anything like this before.

**Comment by Haroenv** [comment]
Arg, that's annoying. Not even a stack trace or something, to know which part of the client of your setup is relevant for this issue? 

A web view should behave like other environments, so I'm not sure what that does

**Comment by fephil** [comment]
I can provide more information but not publicly as there is user data involved. Should I raise this as a support ticket and link to this GitHub issue?

**Comment by vvo** [comment]
Yes, please give us more data on the actual android device/browser used that would help.

**Comment by Haroenv** [comment]
Feel free to reopen if this is reproducible!

**Comment by fephil** [comment]
Hi @Haroenv, I believe I may have an explanation for this. 

My app checks to see if it is connected to the internet. If the check passes then an Algolia query is performed. However, if a user is connected to a public wifi hotspot but hasn't authenticated properly, the app will perform the query but can't connect to Algolia, hence the strange message.

This appeared in one of the error reports (truncated as there is sensitive data in the response): 
![image](https://user-images.githubusercontent.com/1689044/29024190-c7812e16-7b68-11e7-8225-4648a991a34e.png)

The Cloud is a proper public wifi service in the United Kingdom.

So as a final point, I don't believe this is an Algolia issue. Sorry to waste your time on this but it's been so vague and frustrating to debug!

**Comment by Haroenv** [comment]
Awesome, I'm glad to hear that it's something which we don't control. This should only be possible if the user is requesting over http, I'm wondering how that's possible. Is your app serving as http (and not https)?

**Comment by fephil** [comment]
Good point. It uses the default settings. Should I enforce HTTPS? I'm not actually sure what the default settings are in Algolia for a Hyrbid App

**Comment by Haroenv** [comment]
For legacy reasons in the current version of the client, we're taking the same protocol as you're serving from. I'm not sure if Cordova is "serving" from http or https, or maybe it's recognised as http by our client. 

In the next version (upcoming months) we'll use https always, so that shouldn't be an issue anymore

**Comment by fephil** [comment]
Android serves from file:// and IOS serves from http://

Thanks for the info, I'll dig into this more.

**Comment by Haroenv** [comment]
Thanks, that is the cause of the issue.

**Comment by fephil** [comment]
Sorry for contacting you again @Haroenv. 

I can't find the documentation for enforcing https in the javascript SDK. I'm sure I saw it a few months ago but can't seem to find it now. Any help would be appreciated.

**Comment by Haroenv** [comment]
```js
const algoliasearch = require("algoliasearch");

const client = algoliasearch(appId, apiKey, { protocol: 'https:' });
```
