### ISSUE TITLE
AlgoliaSearchNetworkError without more information is thrown when appId or apiKey is wrong

### ISSUE THREAD

**Issue by Chiamaka** [algolia/algoliasearch-client-javascript#587]
Hey guys, awesome work with this JS client. I'm having an issue using this in React Native. 

**What is the current behavior?**
Currently, It presents me with an `AlgoliaSearchNetworkError`. I have gone through the code, looked at the [hn react native sample app](https://github.com/algolia/hn-reactnative-sample) and still, I'm unable to move past the error.

[Here is a JSBin of my code](https://jsbin.com/ceweyozibi/edit?js,output)
and a screenshot of the error
<img width="629" alt="screen shot 2017-08-24 at 9 30 04 pm" src="https://user-images.githubusercontent.com/2737103/29715738-15574660-8998-11e7-8b5d-b1c53d1b3ff7.png">
 
Versions
"algoliasearch": "^3.24.3",
"react": "16.0.0-alpha.12",
"react-native": "0.46.4"

Any help would be appreciated. Thanks
_If you need any more info from me, please let me know_

PS: I have also had a look at this [issue](https://github.com/algolia/algoliasearch-client-javascript/issues/162) but it doesn't help

**Comment by iam4x** [comment]
Hello @Chiamaka 

What is the error into the `more` object, I think it could help?

For your information, we also have a dedicated library to React and which is supporting react-native out of the box: https://github.com/algolia/react-instantsearch

**Comment by Chiamaka** [comment]
@iam4x thanks for the reply. Here is a screenshot of the more object
<img width="629" alt="screen shot 2017-08-25 at 1 44 10 pm" src="https://user-images.githubusercontent.com/2737103/29716638-9c144c2c-899b-11e7-9141-bc5bdd38a6e0.png">

**Comment by Chiamaka** [comment]
Phew! I've been able to fix this issue. For anyone else having the same issue as me, double check your application ID and API Key. 

This could have been avoided if the error message was clearer about where the error was. i.e. with the application credentials. This cost me two painful days of work, and i would hate to see anybody else go through a similar thing. Is there a way to do this check?. I can work on a PR for this.

**Comment by Haroenv** [comment]
PRs are definitely welcome. Usually the error for wrong credentials are different though, I wonder what exactly was wrong here.

**Comment by vvo** [comment]
The reason is that the appid is actually used to create the $appid-dsn.algolia.net domain name to call. So when the appid is bad we are basically trying to resolve a dns that does not exists. Thus the very generic error message, I wonder if it's possible nowadays to distinguish a wrong DNS resolution from a regular no network issue.

When you do not have network, you cannot resolve, but unsure you can make the distinction.

We could still on those network errors put some more details in the message

**Comment by nunomaduro** [comment]
This is no longer an issue on the `v4` - the customer was the complete stack trace on the console, and the following human readable message in the end: `Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com.`.

**Comment by Phakeme** [comment]
> Phew! I've been able to fix this issue. For anyone else having the same issue as me, double check your application ID and API Key.
> 
> This could have been avoided if the error message was clearer about where the error was. i.e. with the application credentials. This cost me two painful days of work, and i would hate to see anybody else go through a similar thing. Is there a way to do this check?. I can work on a PR for this.

> The reason is that the appid is actually used to create the $appid-dsn.algolia.net domain name to call. So when the appid is bad we are basically trying to resolve a dns that does not exists. Thus the very generic error message, I wonder if it's possible nowadays to distinguish a wrong DNS resolution from a regular no network issue.
> 
> When you do not have network, you cannot resolve, but unsure you can make the distinction.
> 
> We could still on those network errors put some more details in the message

Thanks

**Comment by sonuPrasas010** [comment]
Still getting error 

> Unreachable hosts - your application id may be incorrect. If the error persists, contact support@algolia.com
though I have all keys correct.

**Comment by Haroenv** [comment]
please contact support with the credentials you used and a live site @sonuPrasas010

**Comment by hessel-bb** [comment]
For anyone with this issue in the future, you first have to put your APP ID and then your API key like so: 

```
// ❌  wrong
let searchClient;
searchClient = algoliasearch('api_key', 'app_id');
```

```
// ✅  correct
let searchClient;
searchClient = algoliasearch('app_id', 'api_key');
```

**Comment by WardaHaider** [comment]
My App ID and API Key both are correct, have also placed them in the correct order, but still I am facing this error. I am using a free account. Does it require a paid account.

**Comment by Haroenv** [comment]
@WardaHaider, if you can consistently reproduce, please contact support@algolia.com with reproduction, because it should work

**Comment by WardaHaider** [comment]
Application ID: NII9VBHAKK
Index Name: [sdks-stage](https://www.algolia.com/apps/NII9VBHAKK/explorer/browse/sdks-stage?)
Business Impact Level: P2
![image](https://user-images.githubusercontent.com/75788216/170486980-d5e8adcc-97a5-441f-abba-1bbdc5239537.png)
Hosts unreachable: NII9VBHAKK-dsn.algolia.net=An error occurred while sending the request., NII9VBHAKK-1.algolianet.com=An error occurred while sending the request., NII9VBHAKK-2.algolianet.com=An error occurred while sending the request., NII9VBHAKK-3.algolianet.com=An error occurred while sending the request.'

**Comment by WardaHaider** [comment]
Kindly assist me to resolve this issue

**Comment by WardaHaider** [comment]
I am using Algolia 3.1.1 in Dot Net

**Comment by WardaHaider** [comment]
The sample code of Algolia is working fine in my one application but it is giving error on another dot net application.

**Comment by Haroenv** [comment]
please contact support@algolia.com @WardaHaider, this isn't the right platform for a question like the one you have
