### ISSUE TITLE
implement requestOptions

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#590]
1. List all requestOptions (ask api team)
    - forwardToReplicas
    - forwardedFor
    - userId
    - extraHeaders
    - context (for QR)
    - ...

1. Map options to header / qs / json body

    - Ask API team which ones can be used in (headers, url, json body)

**Comment by nunomaduro** [comment]
This `v4.0` is in progress, and we took into consideration all those points.
