### ISSUE TITLE
Release script

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#600]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Manual process to follow when releasing, needing to be admin, because of pushes to master. 

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

```
$ yarn release
new version (patch: X.X.__X__, minor: X.__X__.0, major: __X__.0.0): # accept words (change with --beta)
... running tests
... making changelog
... changing package.json
... making new branch
... open https://github.com/algolia/algoliasearch-client-javascript/pull/1000
wait for the tests on travis, and then you can merge this ✨
```
 

The release PR would be tagged separately, and once merged, will automatically release to npm and jsDeliver

**Comment by Haroenv** [comment]
Once this works here, we should abstract this script into a separate project, together with eslint and jest, allow it to be configurable enough for our projects, and publish it on npm for easier work in other projects. See also [this article](http://tinyletter.com/kentcdodds/letters/automation-without-config) for more info

**Comment by Haroenv** [comment]
Existing scripts: 

- [semantic-release](https://yarn.pm/semantic-release)
- [bumped](https://yarn.pm/bumped)

**Comment by nunomaduro** [comment]
I am sure we can improve, but we have one now: https://github.com/algolia/algoliasearch-client-javascript/blob/master/scripts/release.sh.
