### ISSUE TITLE
Rethink query caching

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#601]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Not completely defined

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

If you do a search and the cache is enabled, if this exact query is done again, it should be cached (if within the caching time). 

If the search is a multi query search, it should take the cache from each search index specifically. 

cc @bobylito

**Comment by redox** [comment]
> If the search is a multi query search, it should take the cache from each search index specifically.

I don't think we need to go that far. The idea behind the caching is "mostly/only" to be able to have a fast answer while pressing backspace. keeping a simple map of `request url+body` => `json answer` is way enough.

**Comment by Haroenv** [comment]
This was a suggestion from @bobylito, but just keeping the same behaviour as existing now seems okay too

**Comment by Haroenv** [comment]
Something that we can do: have an item create a cache key as soon as the request starts, subsequent identical requests can also listen for that Promise, which will make duplicated queries a 0-operation.

**Comment by vvo** [comment]
> Something that we can do: have an item create a cache key as soon as the request starts, subsequent identical requests can also listen for that Promise, which will make duplicated queries a 0-operation.

I think we should do that but hide it behind a flag. That is too much magic to make it the default behaviour of the API client, but a good low level implementation.

This would most probably fit in the helper I would say but then we could say the same for the cache, so in the client it fits too.

**Comment by Haroenv** [comment]
I just realised that this was done in https://github.com/algolia/algoliasearch-client-javascript/pull/694 by @samouss, thanks ❤️. `algoliasearch(..., ..., { _useRequestCache: true })`

**Comment by vvo** [comment]
FWIW @redox we have seen that a lot of UI related bugs (double request at launch) can be easily solved by implementing a request based cache instead of response based cache (what @samouss implemented).

Because most UI frameworks have their own lifecycle micro scheduling semantics (sometime timers, requestAnimationFrame, ..) it's super hard to solve that double request bug so we are solving it at the client level.

We will see how it goes live and ultimately yes we must master the full lifecycle but we are not yet there.

**Comment by vvo** [comment]
Amazed @Haroenv that you had the right idea so long ago already. Nice!

**Comment by iam4x** [comment]
Hi!

I have been running into multiple requests with react-instantsearch + controlled state + custom search client.

In order to "fix" theses I had to make myself a simple caching strategy:

```js
// @flow
import qs from 'qs';
import apiClient from './api-client';

type createSearchClient$Params = {
  endpoint: string,
  afterSearch?: (data: Object) => void
};

const cache = {};

// clear cache every 3 minutes
setInterval(
  () => Object.keys(cache).forEach(key => delete cache[key]),
  3 * 60 * 1000
);

export default function createSearchClient({
  endpoint,
  afterSearch
}: createSearchClient$Params) {
  return {
    search: async (requests: { params: Object[] }) => {
      const cacheKey = qs.stringify(requests);

      if (cache[cacheKey]) {
        const data = JSON.parse(cache[cacheKey]);
        if (afterSearch) afterSearch(data);

        return data;
      }

      const { data } = await apiClient().post(endpoint, requests);

      if (afterSearch) afterSearch(data);

      return data;
    }
  };
}
```

(Might be related to https://github.com/algolia/react-instantsearch/issues/355)

**Comment by Haroenv** [comment]
With a custom search client we don't automatically apply the `_useRequestCache` option in the js client because it's done at initialisation. Does the problem get solved with that option @iam4x? :)

**Comment by samouss** [comment]
@Haroenv since it's a custom search client the option `_useRequestCache` is useless. This option only applied to our own API Client. The issue that refers @iam4x is not linked to the client but to the internal issues of React InstantSearch.

**Comment by Haroenv** [comment]
@samouss I meant that he doesn’t add this option to his `algoliasearch` and React InstantSearch also doesn’t add it because a search client is passed
