### ISSUE TITLE
Delay for partial updates

### ISSUE THREAD

**Issue by ChrisEee** [algolia/algoliasearch-client-javascript#604]
I am finding there to be a significant delay from the time records are updated and the time I complete a partial update request.

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I am using partialUpdateObject() within a promise to update _tags attribute on one or more records selected on a table in our React based UI. After the promise is complete, I do another search query, then the state is updated with unchanged data from the Algolia index. The new data is visible if I set a timeout. At first I was able to get consistent results setting the timeout to 5 seconds, but trying again at about 30 minutes later I had to set the timeout for longer. At 12 seconds I got the updated records to appear 8 out of 10 times.

**What is the expected behavior?**

I expect to be able to perform a search query after a partial update and retrieve records containing the updated attributes. That way I could update the state with the updated records and reflect the new data correctly in the table.

**Comment by Haroenv** [comment]
Hey @ChrisEee, this doesn't seem to be an issue of the API client, could you send an email to support@algolia.com with your appId and relevant settings. 

We'll get back to you there
