### ISSUE TITLE
waitTask behavior missing documentation

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-javascript#605]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The behavior of `waitTask` has been confusing to me, especially because the documentation about it is very terse. I managed to use it correctly, but it raised a few questions about its implementation and how one should use it. You'll find below the various questions I asked myself and could not find any answer in the documentation.

1. Will this promise ever be rejected or will it wait indefinitely until it is resolved?
2. What will it be resolved to? From my tests, I only see `{ status: 'published', pendingTask: true }` but I could not find any documentation about those fields and their meaning. The `pendingTask: true` is especially confusing as, at that point, I would expect my task to not be queued anymore.
3. When doing a `client.moveIndex('old', 'new')`, it seems that I'm supposed to do the `waitTask` on the old index but doing it on the client or the new index would have seem equally logical.

**What is the expected behavior?**
1. From reading other issues it seems that there is a cap at 5s for the method. We should document that in the readme.
2. The format of the answer should be documented in our online documentation. A search for `pendingTask`, `status` or `published` does not yield any relevant results today. I could find it documented [here](https://www.algolia.com/doc/rest-api/search/#get-a-tasks-status), though. We should add a link from the waitTask documentation page to this REST API page.
3. As tasks are per-index, we cannot add a client.waitTask, but we could document in moveIndex that the task will be on the initial index maybe?

Overall, the code is correct, I managed to make it work correctly, but it created some FUD that required me digging into REST API endpoints to understand what was going on.

**Comment by vvo** [comment]
Before I dig in details, can you also maybe what was the situation you were in that confused you afterwards. Were you just curious about waitTask? I ask because in all the situations I used waitTask, I just use it blindly without thinking too much how it works.

> The format of the answer should be documented in our online documentation. A search for pendingTask, status or published does not yield any relevant results today. I could find it documented here, though. We should add a link from the waitTask documentation page to this REST API page.

https://www.algolia.com/doc/rest-api/search/?language=php#get-a-tasks-status

Maybe not well indexed, still here, we can open relevant issue on algolia.com/doc

> From reading other issues it seems that there is a cap at 5s for the method. We should document that in the readme.

We do not really document that, the same we do not really document the full retry algorithm of our clients. Current behaviour of waitTask from the code: it will try to ge the task ID every 100ms, 400ms, 900ms, 1600ms up to 5000ms. After that we will cap at 5000ms and we will ALWAYS retry, never reject (but if servers fails or bad task ID). We can document just what I wrote if we want to, you can open the PR on the algolia doc repo I believe.

We can change the behaviour, that's maybe another discussion.

> As tasks are per-index, we cannot add a client.waitTask, but we could document in moveIndex that the task will be on the initial index maybe?

This is something global to Algolia not a JS client specific but still true, can be done on Algolia doc repo.

**Comment by pixelastic** [comment]
I was actually implementing an atomic indexing like this:

```javascript
algoliaIndexTmp.addObjects(records)
   .then(() => {
     algoliaClient.moveIndex(indexNameTmp, indexName);
  })
  .then(() => {
    process.exit(0);
  });
```

But this sometimes resulted in missing records in my main index and a zombie `_tmp` index left over in my app. That's when I remember I have to wait until all the records are pushed until I actually do the `moveIndex`.

I started re-implementing the above logic, adding `waitTask` between the calls:

```javascript
algoliaIndexTmp.addObjects(records);
  .then(response => algoliaIndexTmp.waitTask(response.taskID))
  .then(() => {
    return algoliaClient.moveIndex(indexNameTmp, indexName);
  })
  .then(response => algoliaIndexTmp.waitTask(response.taskID))
  .then(() => {
    process.exit(0);
  })
```

That's when I started looking at what `waitTask` was resolving to, and wondered if I needed to `catch` the potential errors of `waitTask`.


In the Ruby API Client, we have `set_settings` and `set_settings!`. The final `!` denote that the method will wait until the completion of the internal `wait_task`. Do you think we could have something similar in JS? The `!` is a convention in Ruby, but I don't know if there is a convention we could use to denote an `addObjects` and an `addObjectAndWaitUntilWaitTaskIsOver` :)

**Comment by Haroenv** [comment]
Yes, we are probably adding that as a request option in v4, like addObjects({}, { waitForCompletion: true});  it’s not implemented yet, but seems like a good feature based on other languages implementation

**Comment by redox** [comment]
> That's when I remember I have to wait until all the records are pushed until I actually do the moveIndex.

Hmmm, wait: this is wrong. You can safely send `addObjects` and `moveIndex` sequentially without any `waitTask` -> actually you should never use `waitTask` but for testing purposes.

Bug is probably somewhere else.

**Comment by pixelastic** [comment]
Hmm that's weird. I've been waiting for completion on atomic pushes in Ruby
in every demo I built in the past years, I think it's even part of the
jekyll code.

If I don't do it I sometimes end up with a ghost temp index. Maybe I'm
wrong and the cause is somewhere else. I'll stop waiting and see if it
happens again.

**Comment by redox** [comment]
> Hmm that's weird. I've been waiting for completion on atomic pushes in Ruby
> in every demo I built in the past years, I think it's even part of the
> jekyll code.
> 
> If I don't do it I sometimes end up with a ghost temp index. Maybe I'm
> wrong and the cause is somewhere else. I'll stop waiting and see if it
> happens again.

Nope, something else must be wrong. WaitTask is never required. You can read https://blog.algolia.com/keeping-data-in-your-search-engine-up-to-date/ or https://www.algolia.com/doc/guides/indexing/updates-strategy/#atomic-reindexing

**Comment by nunomaduro** [comment]
On the `v4`, we provide methods such as `replaceAllObjects` that encapsulate all the `waitTask` operations. Also, we have extensive documentation about when the customer should (or not) use the `waitTask`: https://www.algolia.com/doc/guides/sending-and-managing-data/send-and-update-your-data/in-depth/asynchronicity-and-when-to-wait-for-tasks/.
