### ISSUE TITLE
How to set up build and test pipeline

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#607]
so we have multiple packages, all es modules with flow. We should be able to build the different projects in umd, commonjs and es modules (no es2015+ code inside) in a single command in the main repository. 

We should also make sure that jest runs the build process before running the tests I guess, since the requester depends on the universal-store 🤔

**Comment by vvo** [comment]
> We should also make sure that jest runs the build process before running the tests I guess, since the requester depends on the universal-store

I don't quite get why we would need to build packages before launching tests. I saw that the jest repo does that, they have a build/watch for the code to be able to test it (dunno why).

> We should be able to build the different projects in umd, commonjs and es modules (no es2015+ code inside) in a single command in the main repository.

We can tackle that at the very end but still interesting to dig it and possible solutions, any idea?

**Comment by Haroenv** [comment]
Rollup, lerna and bolt are probably good options.

**Comment by nunomaduro** [comment]
This exists on the `v4`.
