### ISSUE TITLE
deleteBy - how to delete all?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [algolia/algoliasearch-client-javascript#612]
I want to delete all objects in an index. I had been doing ```deleteByQuery('')```.

I see the deprecation message, so I'm trying ```deleteBy({query:''})``` and it fails with:
```
{ AlgoliaSearchError: DeleteByQuery endpoint only supports tagFilters, facetFilters, numericFilters and geoQuery condition
    at success (/Users/giro/stardust-backend/node_modules/algoliasearch/src/AlgoliaSearchCore.js:351:32)
    at process._tickCallback (internal/process/next_tick.js:103:7)
  name: 'AlgoliaSearchError',
  message: 'DeleteByQuery endpoint only supports tagFilters, facetFilters, numericFilters and geoQuery condition',
  debugData: 
   [ { currentHost: 'https://hlt622c8vc.algolia.net',
       headers: [Object],
       content: '{"params":""}',
       contentLength: 13,
       method: 'POST',
       timeouts: [Object],
       url: '/1/indexes/tv_eps/deleteByQuery',
       startTime: 2017-10-25T00:26:50.609Z,
       endTime: 2017-10-25T00:26:50.933Z,
       duration: 324,
       statusCode: 400 } ],
  statusCode: 400 }
```
So how do I delete all objects now?

**Comment by Haroenv** [comment]
To delete all objects in an index, you should use `clearIndex`:

```js
index.clearIndex();
```

this will also be a lot faster! 😄

**Comment by Haroenv** [comment]
Sorry for the confusion that happened here by the way; the deleteByQuery --> deleteBy migration hadn't been done in all API clients yet; and thus wasn't documented on the website. I updated the wiki with your information!

**Comment by rayrutjes** [comment]
I think the issue here was that the `query` was used. However the `query` is no longer an option of the new `deleteBy` method.

**Comment by Haroenv** [comment]
Yep, deleteBy doesn’t accept query. If the whole index should be cleared, clearIndex is more logical to use

**Comment by GeoffreyPlitt** [comment]
Thanks!
