### ISSUE TITLE
Typescript Typings AlgoliaClient.setExtraHeaders

### ISSUE THREAD

**Issue by davidallyoung** [algolia/algoliasearch-client-javascript#615]
**Do you want to request a *feature* or report a *bug*?**
Missing Typing

**What is the current behavior?**
I'm currently running the typings for 3.24.5 and cannot locate a defined method for AlgoliaClient.setExtraHeaders. Am I simply overlooking this or has it not yet been included in the typings file? 

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
`npm install --save @types/algoliasearch`
No definiton for AlgoliaClient.setExtraHeaders

**What is the expected behavior?**
I am currently working through getting our application MCM ready and need to be able to setExtraHeaders for routing the search request appropriately as described here: https://www.algolia.com/doc/tutorials/infra/multi-clusters/multi-clusters/ .

The method I'm looking to be able to hit is defined here in the javascript client: https://github.com/algolia/algoliasearch-client-javascript/blob/master/src/AlgoliaSearchCore.js#L144

**Comment by Haroenv** [comment]
Good call, forgot to type those, feel free to make a PR to definitelyTyped if we don't get around to it fast 👍 

```js
client.setExtraHeader('name', 'value');
client.getExtraHeader('name');
client.unsetExtraHeader('name');
```

Thanks!

**Comment by Haroenv** [comment]
done: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21227

**Comment by Haroenv** [comment]
You're welcome, don't hesitate to let any feedback you have know
