### ISSUE TITLE
Usage of localStorage & GDPR

### ISSUE THREAD

**Issue by ehd** [algolia/algoliasearch-client-javascript#616]
Hey, I would like to ask about the library’s usage of localStorage in light of upcoming [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) regulations that affect using cookies as well as localStorage and other persistent storage mechanisms to store any data.

When using the alogliasearch JavaScript client library to perform a search query it sets a value in localStorage in this module https://github.com/algolia/algoliasearch-client-javascript/blob/87f8b6954be25b213aaf66ed81fdf94b5de9f7f8/src/store.js

Would it be possible to disable this setting? I know it sounds stupid, and it’s early, and nobody *really* knows how to implement GDPR stuff, but I’ve been wondering whether setting this is really necessary. Since all I’m doing is querying my other option would be just using `fetch` to do the search and not using the dependency which would also be fine since we don’t need it for anything else.

Thanks!

**Comment by Haroenv** [comment]
Hey @ehd, I'm running this through people more up to date in GDPR, but the data we set in localStorage is simply which hosts are up and which timeout to use. No personal data is stored. 

Data stored is for example (this is on Algolia.com which has multiple searches): 

```json
{
  "BH4D9OD16A": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      3,
      1,
      2
    ],
    "lastChange": 1510147694253
  },
  "B1G2GM9NG0": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      2,
      1,
      3
    ],
    "lastChange": 1510147694255
  },
  "sylvain": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      3,
      1,
      2
    ],
    "lastChange": 1510149290581
  },
  "T2ZX9HO66V": {
    "hostIndexes": {
      "read": 0,
      "write": 2
    },
    "timeoutMultiplier": 4,
    "shuffleResult": [
      2,
      3,
      1
    ],
    "lastChange": 1510132981349
  },
  "OFCNCOG2CU": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      1,
      3,
      2
    ],
    "lastChange": 1510135705721
  },
  "1LFL2RS6YM": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      2,
      1,
      3
    ],
    "lastChange": 1509964462466
  },
  "testingLDUTUO3DEU": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      1,
      2,
      3
    ],
    "lastChange": 1510149335486
  },
  "1AWHE68HXJ": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      1,
      2,
      3
    ],
    "lastChange": 1510048348600
  },
  "latency": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      1,
      3,
      2
    ],
    "lastChange": 1510149313186
  },
  "HXQH62TCI4": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      2,
      1,
      3
    ],
    "lastChange": 1510149313191
  },
  "RYG7374TP2": {
    "hostIndexes": {
      "read": 0,
      "write": 0
    },
    "timeoutMultiplier": 1,
    "shuffleResult": [
      1,
      2,
      3
    ],
    "lastChange": 1510149313197
  }
}
```

I could look how to disable this, but I don't think it should be an issue

**Comment by ehd** [comment]
@Haroenv Thanks so much, I really appreciate the super quick response!

From googling and talking to a company’s legal department I wasn’t sure whether there still is this distinction between functional and personally-identifiable information. I really hope this distinction still exists in the new regulation, because functional, non-tracking cookies are really hard to delay until after consent (session cookies, authentication cookies, load balancing cookies, user preferences, caching, etc).

**Comment by Haroenv** [comment]
Thank you @ehd for raising the issue. We will definitely be compliant to GDPR, but right now there are a lot of questions to be answered, and it's very early to say for sure what the ramifications are. If I understood it correctly, GDPR is more about giving users their privacy, not against things like caching.

I'll keep this issue open until I have some more definite information though

**Comment by ehd** [comment]
@Haroenv Thanks again! Looking forward to what we can learn in these early days 😄

**Comment by Haroenv** [comment]
There should no issue over here in terms of privacy and working with GDPR. The data never leaves the browser (1) and it does not contain anything related to the user (2).

Thanks for bringing up the question, but I’ll close this issue since no action is needed. Have a nice day!

**Comment by ehd** [comment]
@Haroenv Great, thank you for clearing that up! Wish you a nice day, too 😄
