### ISSUE TITLE
Add request options to the getSettings method

### ISSUE THREAD

**Issue by seafoox** [algolia/algoliasearch-client-javascript#637]
The method `getSettings ` is missing a way to pass request options along with the callback

https://github.com/algolia/algoliasearch-client-javascript/blob/fa9506a81fb6ba065024b980d5f8ed17163132ad/src/Index.js#L604-L619

Because of that it's not possible to pass "advanced=1;

**Comment by Haroenv** [comment]
RequestOptions aren’t implemented, because they were all headers and possible with “setExtraHeader”, however advanced should be possible here. Perfect issue 👌
