### ISSUE TITLE
Nodejs: calling getApiKey() with callback causes `Invalid Application-ID or API key` error

### ISSUE THREAD

**Issue by adrienjoly** [algolia/algoliasearch-client-javascript#639]
BUG: Getting `Invalid Application-ID or API key` error while running that code from nodejs. (node v8.9.3, algoliasearch v3.24.7)

```javascript
const algoliasearch = require('algoliasearch');
const creds = {
  appId: '***',
  apiKey: '***', // this is a valid admin api key
};
const client = algoliasearch(creds.appId, creds.apiKey);

// following the javascript example proposed at https://www.algolia.com/doc/api-reference/api-methods/get-api-key/
client.getApiKey(creds.apiKey, (err, content) => {
  console.log(err || content); // => error: Invalid Application-ID or API key
});
```

Whereas this works:

```javascript
// call using promises
client
  .getApiKey(creds.apiKey)
  .then(console.log) // => works as expected
  .catch(console.err);
```

It's ok to have the nodejs client only accept promises. But in that case, shouldn't we mention that in the endpoint doc page?

**Comment by Haroenv** [comment]
Thanks for opening the issue, it should definitely still accept callbacks for now. in v4 there will be no more callbacks though, only promises 😄

**Comment by Haroenv** [comment]
issue was laying somewhere with the api keys
