### ISSUE TITLE
Implement MCM endpoints

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#642]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

the methods at [MultiClusters API Client](https://www.algolia.com/doc/api-client/multi-cluster/) are not available on the JS api client

**What is the expected behavior?**

| API Method | Description | JavaScript name |
|---|---|---|
| [Assign or Move userID](https://algolia.com/doc/api-reference/api-methods/assign-user-id/) | Assign or Move a userID to a cluster | `assignUserID` |
| [Get top userID](https://algolia.com/doc/api-reference/api-methods/get-top-user-id/) | Get userID with highest number of records per cluster | `getTopUserID` |
| [Get userID](https://algolia.com/doc/api-reference/api-methods/get-user-id/) | Returns the userID data stored in the mapping | `getUserID` |
| [List clusters](https://algolia.com/doc/api-reference/api-methods/list-clusters/) | List the clusters available in a multi-clusters setup for a single appID | `listClusters` |
| [List userID](https://algolia.com/doc/api-reference/api-methods/list-user-id/) | List the userIDs assigned to a multi-clusters appID | `listUserIDs` |
| [Remove userID](https://algolia.com/doc/api-reference/api-methods/remove-user-id/) | Remove a userID and associated data from the multi-clusters | `removeUserID` |
| [Search userID](https://algolia.com/doc/api-reference/api-methods/search-user-id/) | Search for userIDs | `searchUserIDs` |

**Comment by Haroenv** [comment]
closed in #643

**Comment by vvo** [comment]
GG
