### ISSUE TITLE
Batch type signature does not accept an array of actions

### ISSUE THREAD

**Issue by 0x80** [algolia/algoliasearch-client-javascript#646]
According to the [API reference](https://www.algolia.com/doc/api-reference/api-methods/batch/) `client.batch()` accepts an array of actions. 

The types only declare a single action parameters:

```typescript
 /**
     * Perform multiple operations with one API call to reduce latency
     * @param action
     * @param cb(err, res)
     * https://github.com/algolia/algoliasearch-client-js#custom-batch---batch
     */
    batch(action: AlgoliaAction, cb: (err: Error, res: any) => void): void;
    /**
     * Perform multiple operations with one API call to reduce latency
     * @param action
     * return {Promise}
     * https://github.com/algolia/algoliasearch-client-js#custom-batch---batch
     */
    batch(action: AlgoliaAction): Promise<any>;
```

**Comment by Haroenv** [comment]
Hey @0x80, that's correct, feel free to add `[]` on the DefinitelyTyped repository, if you want to make a pull request. Thanks for noticing!

**Comment by Haroenv** [comment]
By the way, which custom batch are you writing? 😄

**Comment by 0x80** [comment]
@Haroenv Thanks for making the PR! I was too swamped with stuff to look into it.

What do you mean by "which custom batch"? Are you asking me what use-case I have for it?

**Comment by Haroenv** [comment]
Yep, I was wondering which use case wasn't covered by the methods we already have, to see if it's a common use case we're missing

By the way, until they merge it upstream in DT, you should update it manually in node_modules, and TypeScript will comply

**Comment by 0x80** [comment]
Thanks. I think the // @ts-ignore comment will do just fine for now 🙂 

I am importing data from some external API's to do auto-complete on. It is data that doesn't change often (like city names and locations), so I'm importing that in batches and using an atomic move to replace the active index.

**Comment by Haroenv** [comment]
sounds legit, thanks for using Algolia. This issue will auto-close when the PR is merged in DefinitelyTyped, don't hesitate to reach out if you have any other questions 😄

**Comment by Haroenv** [comment]
Merged in DT
