### ISSUE TITLE
Search generating too long URLs for large API keys

### ISSUE THREAD

**Issue by BootsByDre** [algolia/algoliasearch-client-javascript#647]
__Note: This problem seems to be specific to the most recent release, 3.24.8. Less recent versions, including 3.24.7, don't seem to have this behavior. See below comment__

We've found what appears to be a bug with the current release version. In cases where an API key is considerably long, performing a search will include it in the URL and cause Algolia's DSN server to throw a 414.

This seems to be very similar to an issue that was patched before: https://github.com/algolia/algoliasearch-client-javascript/issues/319

While the JS client code seems to be doing a POST and putting our API key in the body, for some reason it is still including it as a query parameter as well, which is what causes the 414. Simply replaying the url and removing the API key from the query works fine (tested by copying as cURL command from Chrome's network tab).

It's also worth noting that this appears to have happened after release __3.22.1__. We were able to get this older version of your vended JS by requesting the un-minified version for a time (`<script src="//cdn.jsdelivr.net/algoliasearch/3/algoliasearch.js"></script>`) and confirmed it did not have the problem we are seeing. I took some screenshots of my Chrome dev tools to help show this.

__Version 3.22.1__

_Sources_

![3-22-1-sources](https://user-images.githubusercontent.com/11689986/34420287-9dbc8cf4-ebbd-11e7-9c7d-c52139dcd860.png)

_Network_

![3-22-1-networktab1](https://user-images.githubusercontent.com/11689986/34420290-a2d37e8c-ebbd-11e7-8a86-f89f1ba4cdbc.png)
![3-22-1-networktab2](https://user-images.githubusercontent.com/11689986/34420666-aae7545c-ebbf-11e7-96dd-4861ebbfa00b.png)

__Version 3.24.8__

_Sources_

![3-24-8-sources](https://user-images.githubusercontent.com/11689986/34420330-d233284e-ebbd-11e7-8c37-e14c32f75960.png)

_Network_

![3-24-8-networktab1](https://user-images.githubusercontent.com/11689986/34420331-d7f1207e-ebbd-11e7-80d1-04a95060b5e1.png)
![3-24-8-networktab2](https://user-images.githubusercontent.com/11689986/34420335-dd4da0c4-ebbd-11e7-8689-bf880c5cfb94.png)
![3-24-8-networktab3](https://user-images.githubusercontent.com/11689986/34420338-df4e1692-ebbd-11e7-8e1b-06e9245ae97b.png)

**Comment by BootsByDre** [comment]
Quick update on this, we tried playing around with different versions of `algoliasearch.min.js` and it appears to be an issue specific to 3.24.8. Reverting to 3.24.7 fixes this for us:
`<script src="//cdn.jsdelivr.net/algoliasearch/3.24.7/algoliasearch.min.js"></script>`

**Comment by Haroenv** [comment]
Thanks for reporting this, I’ll try to find the origin

**Comment by Haroenv** [comment]
This is fixed in 3.24.9, thanks again!

**Comment by BootsByDre** [comment]
@Haroenv Thanks for the quick turn around! Really appreciate it.

Given this issue has cropped up before as well, is there any way we could add testing around having long API keys in the url, or just long urls in general?

**Comment by Haroenv** [comment]
Yes, I’ll add tests early next year, but was more concerned about making sure this shipped now, there was a lot of plumbing needed to allow for a test like that in the current test setup

**Comment by BootsByDre** [comment]
Understood, thanks again!
