### ISSUE TITLE
Vague index settings error

### ISSUE THREAD

**Issue by 0x80** [algolia/algoliasearch-client-javascript#655]
I'm trying to call setSettings on an index, and I'm getting a vague error:

> AlgoliaSearchError: Invalid object attributes: settings near line:1 column:11
>     at success (/Users/me/myproject/node_modules/algoliasearch/src/AlgoliaSearchCore.js:361:32)

Below are the settings I'm using. I've tried `attributesToIndex`, which I should use according to the outdated type definition, and also `searchableAttributes`. Both versions give me this same error.

```typescript
const settings: AlgoliaIndexSettings = {
  // @ts-ignore
  searchableAttributes: ["id", "city", "name", "country", "countryCode"],
  minWordSizefor2Typos: 8,
  hitsPerPage: 5,
  optionalWords: ["airport"],
  attributesToHighlight: ["city", "name"],
  disableTypoToleranceOnAttributes: ["id", "countryCode"],
  ranking: [
    "typo",
    "custom",
    "words",
    "filters",
    "proximity",
    "attribute",
    "exact",
    "geo"
  ],
  customRanking: ["asc(classification)"],
  removeWordsIfNoResults: "allOptional"
};
```
Do you see anything wrong with this?

It would of course be very helpful if the error pointed out what's wrong.

**Comment by 0x80** [comment]
O never mind! I was passing the settings in the wrong way to `setSettings` 🙈

**Comment by Haroenv** [comment]
Hey Thijs, nice that you found what was wrong, what did you pass that gave that error? 

```js
index.setSettings(settings)
```

This should be the correct way to do it

**Comment by 0x80** [comment]
It was a left over from some previous logic that let to this `index.setSettings({settings})` :)

**Comment by Haroenv** [comment]
Hmm, that’s hard to catch. Since you are using typescript it’s odd that you didn’t get a type warning for that. Are objects open in TS?

**Comment by 0x80** [comment]
Good point! Typescript should catch this. I tried it again with index.setSettings({settings}) and it gave me an error. So I was wrong about that. The code must have been different, although I can't figure out what it was...😕 Now I am starting to doubt my conclusion. Maybe it was something else that triggered the error.... I'll let you know if I ever figure it out.
