### ISSUE TITLE
Cannot use insideBoundingBox or insidePolygon

### ISSUE THREAD

**Issue by Samox** [algolia/algoliasearch-client-javascript#657]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
I'm coding with typescript and the interface AlgoliaQueryParameters.
The code: https://jsfiddle.net/6qv7vx89/1/
The interface expects the insideBoundingBox to be number[][], which I use, then I get a 400
```
AlgoliaSearchError: Invalid value for "insideBoundingBox" parameter, expected list of float with nb element = 4 + 4 * X
```

So the API expect (according to the error and the documentation) insideBoundingBox to be number[].

When I use it this way : https://jsfiddle.net/6qv7vx89/ I have another 400 error:
```
AlgoliaSearchError: Invalid value for "insideBoundingBox" parameter, expected float
```

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
even if it cannot be used, I tried this code in my project
First bug: https://jsfiddle.net/6qv7vx89/
second bug: https://jsfiddle.net/6qv7vx89/1/

**What is the expected behavior?**
When I use the parameter insideBoundingBox, the response is 200

Thanks :D 🔥

**Comment by Samox** [comment]
omg my bad I just understood it was [[lat,lng,lat,lng]]... 
<3

**Comment by Haroenv** [comment]
All right, have a great day!
