### ISSUE TITLE
exportRules() throws ⚡️ `Cannot read property '_jsonRequest' of undefined`

### ISSUE THREAD

**Issue by adrienjoly** [algolia/algoliasearch-client-javascript#660]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

After loading https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js (v3.24.9), the JavaScript code below throws `TypeError: Cannot read property '_jsonRequest' of undefined`

```
const fromClient = algoliasearch(fromAppId, fromApiKey);
const fromIndex = fromClient.initIndex(fromIdxName);
fromIndex.exportRules(100, console.log);
```

Tested on both nodejs (back-end) and in jsfiddle (front-end) with the same version.

I relied on the following documentation: https://www.algolia.com/doc/api-reference/api-methods/rules-export/?language=javascript#examples

**What is the expected behavior?**

I expected to have a list query rules printed to my javascript console.

**Comment by Haroenv** [comment]
Whoow that’s an error. I think it’s because the context is wrong, we might need to bind something there. I’ll take a look 👀

**Comment by adrienjoly** [comment]
What's up @Haroenv ?

I need to use that function now. Is there anything I can do to help / speed up the solving of this issue?

**Comment by vvo** [comment]
Yes everytime we do this https://github.com/algolia/algoliasearch-client-javascript/blob/58a4b2dbe6258769a869e2668d0d66367359504c/src/Index.js#L801-L803

It should be exportData(this.searchRules.bind(this)).
But there are multiple calls like that, were those tested somehow?

**Comment by Haroenv** [comment]
@vvo, they are tested in the integration tests, `exportRules` and `exportSynonyms` were both made in the same manner, a PR with maybe an even more integration test would be great

**Comment by vvo** [comment]
Here's an online test case: https://codesandbox.io/s/93lr68qyq4

This is broken for now.

Even if there seems to be integration tests, it might works only because either those ones are not run OR because we somehow bind the context in a forced way via bindAll? :)

Maybe add some unit test on top of that.
