### ISSUE TITLE
setTimeout console alerts on Chrome

### ISSUE THREAD

**Issue by samouss** [algolia/algoliasearch-client-javascript#661]
> Duplicate on the issue open on React InstantSearch https://github.com/algolia/react-instantsearch/issues/904

Hi folks, I am seeing the following console messages pop up in Chrome Canary when I have my log level include 'Verbose'. I wasn't sure if this is a problem (says 'Violation') but wanted to make sure it was known.

This is in Chrome 64 (Mac).
<img width="769" alt="screen shot 2018-01-25 at 8 04 58 pm" src="https://user-images.githubusercontent.com/9633371/35424874-811b08aa-020b-11e8-83a5-575e0102bfe6.png">

Thanks!

**Comment by Haroenv** [comment]
I think the line number is wrong: https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/AlgoliaSearchCore.js#L445

cc @oceanuy

**Comment by Haroenv** [comment]
correct line would be https://github.com/algolia/algoliasearch-client-javascript/blob/4bbfa376077b5925f893485baa7231bac934e9d3/src/browser/createAlgoliasearch.js#L75

**Comment by vvo** [comment]
I dont understand those messages, tried to have a quick look on what they meant online but without finding the exact root cause/solution

**Comment by nunomaduro** [comment]
This is no longer an issue on the `v4`. You can test it out here: https://www.algolia.com/doc/.
