### ISSUE TITLE
Consider doing runtime type checking for indexing methods

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#674]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

there are no checks for the correct type, which can lead to bugs when things are type coerced (see https://github.com/algolia/algoliasearch-client-javascript/issues/673)

**What is the expected behavior?**

Errors to be thrown when people use the wrong type. Let's check if we can do this with something Flow in runtime for v4, or if we should write our own function

**Comment by nunomaduro** [comment]
You still maintain your opinion on this @Haroenv ?

**Comment by Haroenv** [comment]
I think methods which are potentially destructive (add / delete / move / settings) should have a quick argument type check indeed (for people not using typescript). Especially in those which will behave differently because e.g. the index name is in the URL

**Comment by nunomaduro** [comment]
Got it. Let's keep this open while I double check if we are doing defensive programming on those destructive actions.

**Comment by nunomaduro** [comment]
On the `v4` we have defensive programming on destructive actions only.
