### ISSUE TITLE
Add an option to disable DSN

### ISSUE THREAD

**Issue by Haroenv** [algolia/algoliasearch-client-javascript#675]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

If you have DSNs around the world, but are also doing backend search, some providers aren't able to resolve the correct DSN to route to, and thus round-robin all over the world.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**

You should be able to disable DSN in certain cases.

Proposed option for this:

```js
algoliasearch(appId, apiKey, { dsn: false });
```

This option will make sure that the first read host is `appId.algolia.net`, and not the default `appId-dsn.algolia.net`.

**Comment by vvo** [comment]
LGTM and very clear explanation of the problem at stake, thanks!
