### ISSUE TITLE
setUserToken not in @types/algoliasearch

### ISSUE THREAD

**Issue by laughinghan** [algolia/algoliasearch-client-javascript#693]
I can't find it in the official documentation but it was mentioned in [this blogpost](https://blog.algolia.com/handle-security-realtime-search/) and we use it in production, with v3.27.0 of `algoliasearch`. Is it deprecated?

Let me know if I should open this ticket in DefinitelyTyped instead.

**Comment by Haroenv** [comment]
Feel free to do a PR on definitelytyped indeed; the typescript definitions aren’t automatically generated and thus can indeed miss some parameters which are less frequently used. 

Thanks for noticing!

**Comment by Haroenv** [comment]
Just adding to this issue for myself `camelCaseAttributes: string[]` also needs to be added

**Comment by Haroenv** [comment]
I misread which parameter you are talking about. The correct way of doing it is this: https://www.algolia.com/doc/api-reference/api-methods/generate-secured-api-key/?language=javascript#generate-a-secured-api-key-with-a-rate-limiting-applied-per-user
