### ISSUE TITLE
Update deprecation note for deleteByQuery

### ISSUE THREAD

**Issue by mlbrgl** [algolia/algoliasearch-client-javascript#697]
Hi,

The deprecation note for deleteByQuery on https://github.com/algolia/algoliasearch-client-javascript/wiki/Deprecated#indexdeletebyquery is misleading as it mentions a "query" parameter for deleteBy that is not accepted (https://www.algolia.com/doc/api-reference/api-methods/delete-by/) and returns the following message: 
`DeleteByQuery endpoint only supports tagFilters, facetFilters, numericFilters and geoQuery condition`

It seems like https://github.com/algolia/algoliasearch-client-javascript/issues/612 ran into the same issue.

**Comment by vvo** [comment]
Updating this, thanks a lot!
