### ISSUE TITLE
Advice for moving away from deleteByQuery 

### ISSUE THREAD

**Issue by mlbrgl** [algolia/algoliasearch-client-javascript#698]
Hi,

Following the deprecation of `deleteByQuery`, I am looking  for alternatives for this [implementation](https://github.com/mlbrgl/ghost-algolia/blob/8c2215ca352e0ad99a1f42157eb48658ff1a408f/lib/indexFactory.js#L36).
The idea is to remove paragraphs of an article in case of an update or a deletion of that article (to avoid duplicates in the index). Each paragraph references the parent article through the `post_uuid` attribute, which I was targeting in my previous `deleteByQuery`.

I am considering the two following alternatives:

### Pros
- Small amount of moving parts, clean code.
```
index.deleteBy({
  filters: 'post_uuid:' + post.attributes.uuid
});
```
- cheap (for now at least) as it only requires one operation to delete all records (paragraphs of an article).

### Cons
- requires adding `post_uuid` to the `attributesForFaceting`. I'm concerned about people going for default UI implementations (InstantSearch?) in which that facet could be exposed. Please bear in mind that this is just a hunch, and I would love to hear some reassuring arguments (like "the only way the facet could be exposed is by programmatically and voluntarily exposing it in the UI implementation. By default, no facets are exposed in any UI implementation, regardless of what's set up in the dashboard" ... or equivalent :))  
- requires granting what looks like an irrelevant (to that operation) and permissive permission: `deleteIndex`. Why isn't `deleteObject` sufficient?

### Pros
- no fiddling around with extra dashboard settings: a search with `restrictSearchableAttributes` does the job without having to grant any more permissions or introduce / pollute facets
### Cons
- expensive: 1 operation for `search` + as many operations as paragraphs for `deleteObjects`
- more moving parts, less direct (code wise)
```
index.search({
  query: post.attributes.uuid,
  restrictSearchableAttributes: 'post_uuid',
  attributesToRetrieve: 'objectID'
}).then((res) => {
  let objectIDs = res.hits.map(hit => hit.objectID)
  return index.deleteObjects(objectIDs)
});
```

I'd love to hear your take on this and any recommendation you might have, thanks!

**Comment by Haroenv** [comment]
Just for a  bit more info, 

>the only way the facet could be exposed is by programmatically and voluntarily exposing it in the UI implementation. By default, no facets are exposed in any UI implementation, regardless of what's set up in the dashboard

Yes, that's how it is with any of the InstantSearch implementation, you'd have to specifically say which facets to display. It's also possible to make that faceting dynamic, but that's not officially supported yet, and could definitely be adjusted to exclude post_uuid. To save a tiny bit of space on the index, you could make it `filterOnly(post_uuid)`. That way you can only filter on it, but we wouldn't bother keeping the specific values and how many filters there are possible.

--- 
> requires granting what looks like an irrelevant (to that operation) and permissive permission: deleteIndex. Why isn't deleteObject sufficient?

Maybe sounds a bit like a bug, I'll ask the API team to see if that was an oversight or has a reason I didn't think of.

--- 

Regarding your second possible solution, you'd have to use `browseAll` in case there are more objects than fit on a "page" and you'd have to iterate.

--- 

Thanks for maintaining ghost-algolia by the way!

**Comment by Haroenv** [comment]
I just asked, and the reason we give it the `deleteIndex` ACL is because it's quite possible to write a filter that matches all objects, and like `clearIndex` it thus is more risky than a simple `deleteObjects`.  Does that make sense?

**Comment by mlbrgl** [comment]
@Haroenv thanks for your insights, that's helpful. 
That `deleteIndex` permission feels more like a psychological deterrent then, but yes I get the idea :)

About `filterOnly(post_uuid)`, is there a way to enable it through the dashboard? The plugin does not have a place for these one-off programmatic settings.

**Comment by Haroenv** [comment]
you can write it yourself as "attributes for faceting", it won't autocomplete it, but it will work. You can also do it in `setSettings`:

```js
index.setSettings({
  attributesForFaceting: ["filterOnly(post_uuid)"],
});
```

**Comment by mlbrgl** [comment]
Ah cool, thanks! I think I've got all I need for now, I'll go ahead and close that thread. Thanks again.

**Comment by Haroenv** [comment]
All right, don't hesitate to reach back out with any questions at all
