### ISSUE TITLE
 Firefox addon  Promise rejection value is a non-unwrappable cross-compartment wrapper

### ISSUE THREAD

**Issue by Zitle-Nancy** [algolia/algoliasearch-client-javascript#703]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a problem when I want to use algoliasearch-client-javascript in my firefox addon, because I can´t get Hits 
This is the show up in my console when I debug the code:

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
`uncaught exception: AlgoliaSearchNetworkError: Network issue, see err.more for details  main.js:2:253575
uncaught exception: AlgoliaSearchUnknownError: Promise rejection value is a non-unwrappable cross-compartment wrapper.`

**What is the expected behavior?**
Get the hits from algolia search

**Comment by Haroenv** [comment]
Hey @Zitle-Nancy, could you make a GitHub repository we can try this out on, this seems like a very particular issue that we haven't had in other use cases yet. Thanks!

Seeing some bugs in FF related to this: https://bugzilla.mozilla.org/show_bug.cgi?id=1368436

**Comment by Haroenv** [comment]
@Zitle-Nancy have you found the time to make a reproduction or is this fixed ? 🤔

**Comment by Haroenv** [comment]
Please reopen if this happens again 🙂
