### ISSUE TITLE
DeleteObject returns successful response, doesn't actually delete the object.

### ISSUE THREAD

**Issue by rbrand21** [algolia/algoliasearch-client-javascript#704]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I issue index.deleteObject(objectId) from cloud function.
It returns successfully. Object still exists in Algolia dashboard.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
1) Initialize cloud functions
2) Setup a firestore db
3) Write the cloud function:
```
exports.unindexBill = functions.firestore
  .document('bills/{billId}')
  .onDelete((snap, context) => {
    const objectId = snap.data.id;

    console.log("Removing bill from Algolia with id: "+ objectId);

    // Delete an ID from the index
    return index.deleteObject(objectId, function (err, content) {
      if(err) throw err;
      console.log(content)
    });
  });
```
4) firebase deploy --only functions
5) Add item to firestore, add same item to Algolia
6) Delete item from Firestore (ensure cloud function runs)
7) Observe results

**What is the expected behavior?**
Object should be deleted in Algolia dashboard.
This is the log statement that gets printed even though my item is not removed:
{ deletedAt: '2018-06-12T05:22:50.633Z', taskID: 1099223692, objectID: 'rtgrstyrgd' }
I can still see an object with that exact id inside the dashboard.

**Comment by vvo** [comment]
@rbrand21 Algolia indexing is asynchronous, which means it takes some time (seconds) for Algolia to process this deletion.

You can use `waitTask` to know when it's fully done: https://www.algolia.com/doc/api-reference/api-methods/wait-task/

But if you delete an object, and then see it again in your dashboard, even days after, then it means somewhere in your code, it was re-added or you deleted a different object or you are looking at a different index.

If this continues, please contact support@algolia.com so we can have a closer look

**Comment by rbrand21** [comment]
Still doesn't work, thanks for the suggestions. I'll keep digging and/or contact support.
