### ISSUE TITLE
Missing `multiple_get_objects` method

### ISSUE THREAD

**Issue by Zlitus** [algolia/algoliasearch-client-javascript#710]
Hi,

Algolia REST API [support retrieving multiple objects by ID from multiple indexes](https://www.algolia.com/doc/rest-api/search/?language=javascript#retrieve-multiple-objects), however the AlgoliaSearch Javascript client does not offer this feature. At this moment, if I want retrieve 3 objects from 2 different indexes with AlgoliaSearch.js, I need to do 2 requests.

Here what I want to do:

```
client.getObjects([
	{"objectID": "book1", "indexName": "books"},
	{"objectID": "book2", "indexName": "books"},
	{"objectID": "author1", "indexName": "authors"}
]);
```

Here what I have to do today:

```
client.initIndex("books").getObjects(["book1", "book2"]);
client.initIndex("authors").getObjects(["author1"]);
```

Do we have any way to do multiple get objects in one single request?
Thank you,
Arnaud.

**Comment by Haroenv** [comment]
Good call, cc @julienbourdeau. I think you could use client.batch for this, can you confirm?

**Comment by Haroenv** [comment]
What’s the practical use case you had for this?

**Comment by Zlitus** [comment]
Well, on my company, we index a lot of different information (Companies reports, news, etc) and we store that in different Algolia's indexes. A user can “bookmark” any information on his personal account, and to retrieve all his “bookmarked items” at this moment we have to do many requests (One by indexe).

But really, I think we have millions of user cases for a “generic” client.getObjects(); it's definitely not specific to this current website, on others projets this feature can help me a lot too.

**Comment by nunomaduro** [comment]
The `client.batch` method doesn't support the `getObjects` operation.

**Comment by nunomaduro** [comment]
You can now use the `client.multipleGetObjects` on the `v4`.
