### ISSUE TITLE
clearCache safe while multiple queries are in flight?

### ISSUE THREAD

**Issue by joelgetaction** [algolia/algoliasearch-client-javascript#711]
**Do you want to request a *feature* or report a *bug*?**
Report a documentation bug

**What is the current behavior?**
Documentation on whether it is safe to invoke clearCache while multiple queries are in flight is missing.

I am using algoliasearch within a ReactNative app.  It's fast and awesome, thanks!  :-)

However, I'm having issues where when I use an index just to provide ranked results (e.g. return the most recent posts from index `posts_most_recent` ordered by published time desc) then once I do the search once, the results get cached and the search never updates on the client.  The search has  no actual query, it's just "return results from this index according to its sort criteria", literally:
```javascript
const query = ...; // '' or undefined
client.search(
          {
            query,
            page,
            hitsPerPage: 20,
            attributesToHighlight: [],
          },
         ...
);
```
I am caching the client instance.  My question is, would it be safe to clear the cache just before invoking search if the page is zero?  As in:
```javascript
if (!page || page < 1) {
    console.log("clearing cache for page", page);
    client.clearCache();
}

const query = ...; // '' or undefined
client.search(
          {
            query,
            page,
            hitsPerPage: 20,
            attributesToHighlight: [],
          },
         ...
);
```

Will this be safe if client already has searches ongoing?  For example, if using the same client instance I do:
```
clear cache
start search 1 on query = ''
clear cache
start search 2 on query = '', same index as search1
search1 returns page 0
search2 returns page 0
clear cache
search1 returns page 1
...
```
In other words, does interspersing `clearCache` and `search` calls in any way cause race conditions in algoliasearch js client, or is it safe?

Or alternatively, is there any kind of cache-busting technique I can use like add some kind of `searchId: random-uuid` to make each query seem the different even if there actual `query` value is the same?

Or alternatively, could I just create a new algoliaseachclient instance for each search?  Is that expensive to new an instance for each search?  Are there any globals that might get stomped on?

Thanks!

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

**What is the expected behavior?**
Documentation on whether it is safe to invoke clearCache while multiple queries are in flight is missing.

**Comment by vvo** [comment]
Hi @joelgetaction and thanks for your very detailed question.

> In other words, does interspersing clearCache and search calls in any way cause race conditions in algoliasearch js client, or is it safe?

Yes it is safe, the call to clearCache is synchronous and very fast (it's actually just var cache = {}).

> Or alternatively, is there any kind of cache-busting technique I can use like add some kind of searchId: random-uuid to make each query seem the different even if there actual query value is the same?

There's no public option to disable the cache, you could try _useCache: false in client options but it's private for now. I think it's a good idea to make it public.

> Or alternatively, could I just create a new algoliaseachclient instance for each search? Is that expensive to new an instance for each search? Are there any globals that might get stomped on?

Yes that will work too.

For now I recommend just calling clearCache() before every search.

Thanks!
