### ISSUE TITLE
partiaUpdateObject: doesn't throw on unknown objectID and createIfNotExists set to `false`

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-javascript#712]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using partialUpdateObject with an unknown object with the flag `createIfNotExists` set to `false`, the client doesn't return an error.

```js
const algolia = require('algoliasearch');

const client = algolia('', ''); // credentials have been redacted

const index = client.initIndex('test-createIfNotExists');

index.partialUpdateObject({objectID: 'blah'}, false).then(res => {
  console.log({res});
}, err => {
  console.log({err})
})
```

We get the following message:

```js
{ res:
   { updatedAt: '2018-06-28T15:50:50.893Z',
     taskID: 10015357362,
     objectID: 'blah' } }
```

**What is the expected behavior?**

Based on the documentation, it should throw an error.

https://www.algolia.com/doc/api-reference/api-methods/partial-update-objects/?language=javascript

**Comment by Haroenv** [comment]
>When false, a partial update on a nonexistent object will be ignored (but no error will be sent back).

The object is not in the index, but it will not throw an error 👍 Something to consider in #help-search-api though 🤔

**Comment by bobylito** [comment]
> The object is not in the index, but it will not throw an error 👍 Something to consider in #help-search-api though 🤔

The docs says it should throw an error. Maybe the other API clients do so? Happy to fix the doc also.

**Comment by bobylito** [comment]
![](https://i.imgur.com/ypsHn6s.png)

**Comment by Haroenv** [comment]
![fba35ffe-fa96-4ece-809c-6fae1a800e36](https://user-images.githubusercontent.com/6270048/42122356-d8cd8a6e-7c40-11e8-9dcc-3416481f3d91.jpeg)

**Comment by bobylito** [comment]
Ok the doc is inconsistent then. Will make a PR over there.
