### ISSUE TITLE
[4.x] Header are not forwarded to the request in the React Native build

### ISSUE THREAD

**Issue by samouss** [algolia/algoliasearch-client-javascript#713]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

We can't set extra headers (e.g. `referer`) with the React Native build.

```js
client.setExtraHeader('referer', 'value');
```

The browser implementation inline the headers to avoid the CORS preflight request (with a Simple Request). But in a native environment (like React Native) [there is no concept of CORS](https://facebook.github.io/react-native/docs/network#using-other-networking-libraries) so we can set the headers directly on the request.

**Comment by nunomaduro** [comment]
Do you think you can find some time to test this with the latest `v4`?

**Comment by nunomaduro** [comment]
Going to close this, please re-open this issue if you think we may face this issue with the v4.
