### ISSUE TITLE
Import not working

### ISSUE THREAD

**Issue by brianmhunt** [algolia/algoliasearch-client-javascript#717]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Webpack with `import algoliasearch from 'algoliasearch'` errors with:

```
ERROR in ./node_modules/debug/src/node.js
Module not found: Error: Can't resolve 'net' in '/Users/bmh/Repos/[...ourproject...]/node_modules/debug/src'
 @ ./node_modules/debug/src/node.js 193:16-30
 @ ./node_modules/debug/src/index.js
 @ ./node_modules/algoliasearch/src/browser/createAlgoliasearch.js
 @ ./node_modules/algoliasearch/src/browser/builds/algoliasearch.js
 @ ./services/app/src/libs.js
 @ multi ./services/app/src/libs.js
```

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

I don't have time for this at the moment, but thought you should know; I figure this is a pretty simple fix *or* it's on your roadmap.

**What is the expected behavior?**

Webpack not to error.

**Comment by Haroenv** [comment]
Webpack always has worked when I try it, it the regular way to use it. We don’t directly depend on net, so I assume that somehow you set up webpack for node instead of browser. To be able to help you I’ll need a reproduction that will help us debug. Sorry for not being able to help just from this. Have a nice day!

**Comment by Haroenv** [comment]
Thanks, will reopen to see what the real issue is here :)

**Comment by smark090** [comment]
ok

**Comment by stephanschubert** [comment]
Any updates on this? It just popped up as I tried to [integrate `gatsby-plugin-algolia` and `react-instantsearch`](https://github.com/gatsbyjs/gatsby/blob/9fee379ec4f7d77e5bfc0a7167687a15090fde10/docs/docs/adding-search-with-algolia.md#frontend) into my Gatsby site.

**Comment by Haroenv** [comment]
Can you give a reproducible example @stephanschubert ?

**Comment by stephanschubert** [comment]
@Haroenv Hard to do because I have a big monorepo here, but I just noticed I had [`directory-named-webpack-plugin`](https://github.com/shaketbaby/directory-named-webpack-plugin) in my config too. Removing it resolves it.

**Comment by nunomaduro** [comment]
I’m closing this issue because it has been inactive for a few months. This probably means that it is not reproducible or it has been fixed in a newer version.

Thank you!

**Comment by sumitsingh1698** [comment]
Hello, 

  When I am trying to install algolia it can't able to install  and showing me

npm WARN saveError ENOENT: no such file or directory, open '/mnt/sda7/firebase/groceryapp/firebase-function/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/mnt/sda7/firebase/groceryapp/firebase-function/package.json'
npm WARN firebase-functions@3.8.0 requires a peer of firebase-admin@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN firebase-function No description
npm WARN firebase-function No repository field.
npm WARN firebase-function No README data
npm WARN firebase-function No license field.

+ algoliasearch@4.3.0
updated 1 package and audited 153 packages in 2.751s
found 0 `vulnerabilities`

**Comment by Haroenv** [comment]
those are warnings, not errors. Please open a new issue @sumitsingh1698
