### ISSUE TITLE
Not able to retrieve beyond the first 1000 results of a search

### ISSUE THREAD

**Issue by house92** [algolia/algoliasearch-client-javascript#718]
BUG

When passing the 1000 hits point using `index.search()` (e.g. when sending a request for page 3 of some index results when each page contains 500 results), we are instead receiving a response with `message` "you can only fetch the 1000 hits for this query. You can extend the number of hits returned via the paginationLimitedTo index parameter or use the browse method. You can read our FAQ for more details about browsing: https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index". We are not trying to retrieve all results, in which case we realise the `browse()` function would be appropriate, but rather we are paging through results, for which purpose the `page` parameter exists in your API.

This didn't happen previously, so we are wondering whether there has possibly been some update to the package to cause this behaviour.

**Comment by Haroenv** [comment]
Did you change the “paginationLimitedTo” setting? 1000 is the default though.

**Comment by Haroenv** [comment]
please reopen if this didn't solve your issue, have a nice day!
