### ISSUE TITLE
Strategy not working?

### ISSUE THREAD

**Issue by benbernard** [algolia/algoliasearch-client-javascript#719]
From my testing against my indexes, `stopIfEnoughMatches` is not working in the javascript client.  I found this change in the swift client that hints at the issue

https://github.com/algolia/algoliasearch-client-swift/pull/89/files

Basically, it looks like the strategy parameter is supposed to go in the request body params and not in the URL params.

**Comment by Haroenv** [comment]
Thanks for this, seems indeed like this isn't implemented how it should have been. I'm investigating now why it initially was like that (a mistake or a change in the api). I'll get back to you with the fix.

**Comment by Haroenv** [comment]
This has been released as `3.30.0` now
