### ISSUE TITLE
Improve pushData section (README.md)

### ISSUE THREAD

**Issue by Silver-birder** [algolia/algoliasearch-client-javascript#722]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

**environment**
```
⋊> ~/work npm -v
4.6.1
⋊> ~/work yarn -v
fish: Unknown command 'yarn'
```

**install npm package**
```
⋊> ~/work npm init 
⋊> ~/work npm install algoliasearch --save 
work@1.0.0 /Users/silver/work
└── algoliasearch@3.30.0

npm WARN work@1.0.0 No description
npm WARN work@1.0.0 No repository field.
```

**do**
```
⋊> ~/work cat index.js
var client = algoliasearch('****', '****'); # I use Search-Only API Key ...
var index = client.initIndex('contacts');

var contactsJSON = require('./contacts.json');
# https://github.com/algolia/datasets/blob/master/contacts/contacts.json

index.addObjects(contactsJSON, function(err, content) {
  if (err) {
    console.error(err);
  }
});

⋊> ~/work node index.js
AlgoliaSearchError: Not enough rights to add an object near line:1 column:332
```

I resolved if I use Admin API Key but not Search-Only API Key.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

no bug.

**What is the expected behavior?**

Please comment that use Admin API Key on pushData section ([here](https://github.com/algolia/algoliasearch-client-javascript#push-data))

**Comment by Haroenv** [comment]
Adding objects needs to be done with the admin API key, that should indeed be mentioned there.
