### ISSUE TITLE
Missing `err` in exportSynonyms and exportRules callback

### ISSUE THREAD

**Issue by sarahdayan** [algolia/algoliasearch-client-javascript#724]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

the `exportSynonyms` and `exportRules` methods use the underlying `exportData` function. The problem is this function [doesn’t seem to handle error cases](https://github.com/algolia/algoliasearch-client-javascript/blob/8702d1e4fca3b40bc330e20f97acf9f6786d694d/dist/algoliasearch.js#L5036).

As a result, the callback doesn’t work with the usual `(err, res)` parameters (because only a single param is ever returned), therefore you can’t handle error cases.

It can be fixed on the user end by only passing the `res` parameter, but if you have an error (e.g.: `index.exportSynonyms('100', res => {}`), you will get an `UnhandledPromiseRejectionWarning`.

It's the same behavior with promises (using `then/catch` or `try/catch` with `async/await`).

JSFiddle: https://jsfiddle.net/mzuLtreo/

**What is the expected behavior?**

We should be able to handle error cases with callbacks and promises, either with an `err` param or using the `catch` method with promises. Note that if people have implemented it like this as a workaround:

```js
index.exportSynonyms(100, res => {})
```

And they update, the bug fix will break their implementation.

**Comment by nunomaduro** [comment]
This is no longer an issue on the `v4`.
