### ISSUE TITLE
TypeScript Typings are missing Algolia Places definitions

### ISSUE THREAD

**Issue by JonathanMontane** [algolia/algoliasearch-client-javascript#738]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The `index.d.ts` that is generated seems to be missing the typings for `algoliasearch.initPlaces(...)`

**What is the expected behavior?**
The `index.d.ts` contains the definitions for Places methods.

**Comment by samouss** [comment]
We don't host the definition file on this project, it's on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/algoliasearch). PRs are welcome!

**Comment by JonathanMontane** [comment]
Thanks, I'll look into it 👍

**Comment by brendanmc6** [comment]
Am I mistaken or are the `.initPlaces` types not found on DefinitelyTyped either?

**Comment by Haroenv** [comment]
You’re correct @brendanmc6, they aren’t added yet
