### ISSUE TITLE
Typescript property/func/etc docs have old links

### ISSUE THREAD

**Issue by fenixsolorzano** [algolia/algoliasearch-client-javascript#739]
De typescript lib has outdated links like: 

https://github.com/algolia/algoliasearch-client-js#separatorstoindex
https://github.com/algolia/algoliasearch-client-js#disabletypotoleranceonattributes

And more... Would be great to have updated links

**Comment by antoinerousseau** [comment]
Open an issue (or better, a PR) here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues

**Comment by nunomaduro** [comment]
This is no longer an issue on the `v4`.
