### ISSUE TITLE
Typescript has `placeholders` property but there's no doc about it

### ISSUE THREAD

**Issue by fenixsolorzano** [algolia/algoliasearch-client-javascript#740]
What are placeholders? are they the same as [synonyms](https://www.algolia.com/doc/api-reference/api-parameters/synonyms/)?

**Comment by vvo** [comment]
Hi there, I believe you are speaking about: https://www.algolia.com/doc/guides/managing-results/optimize-search-results/adding-synonyms/?language=javascript#placeholders
