### ISSUE TITLE
Can't set removeStopWords from Typescript

### ISSUE THREAD

**Issue by fenixsolorzano** [algolia/algoliasearch-client-javascript#741]
I get the following error message when I add the `removeStopWords` to the json object:

<img width="530" alt="screen shot 2019-02-07 at 12 33 48 am" src="https://user-images.githubusercontent.com/15699775/52394614-7e966500-2a70-11e9-8b43-b8cc4a633c2d.png">

**Comment by Haroenv** [comment]
The source for TypeScript typing is on DefinitelyTyped; not this repository. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32850
