### ISSUE TITLE
`restoreAPIKey` feature request

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#742]
Hello team,

Here's a feature that needs to be implemented in the JavaScript client to be in sync with other clients:

 * Function: `client.restoreApiKey(key)`
 * Method: `POST`
 * Route: `/1/keys/<KEY>/restore`
 * Return value: `{key: string, createdAt: string}`
 * PHP example implementation: https://github.com/algolia/algoliasearch-client-php/pull/502/files

Let me know if you need any other information to implement it. :)

**Comment by vvo** [comment]
I actually did a small demo to test a future implementation was working: https://codesandbox.io/s/rmrw5ozz6m so that would be about copy pasting the method code and releasing now
