### ISSUE TITLE
npm package cannot be used in browser project

### ISSUE THREAD

**Issue by wizcas** [algolia/algoliasearch-client-javascript#756]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

I used `algoliasearch` package in my Angular project. When importing the module it throws an exception of *Cannot read property 'RESET_APP_DATA_TIMER' of undefined* 

I found it is caused by the code in `AlgoliaSearchCore.js`: 

``` js
var RESET_APP_DATA_TIMER =
  process.env.RESET_APP_DATA_TIMER && parseInt(process.env.RESET_APP_DATA_TIMER, 10) ||
  60 * 2 * 1000;
``` 

I think there is no way that browser environment can access `process.env`. Is it a bug or I'm using the package wrong?

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

download `algoliasearch` package by npm/yarn and import it in a browser project

**What is the expected behavior?**

`algoliasearch` is initialized without errors

**Comment by Haroenv** [comment]
you should use the webpack defineplugin to define `process.env` like many more packages do.

Could you give a project in which you can reproduce this?

**Comment by wizcas** [comment]
@Haroenv Thanks for your information! I've got this handled by providing a custom webpack config with `DefinePlugin` in my Angular project. Everything works now :)

**Comment by noslouch** [comment]
I'm trying to use this in an ember project, which does not use webpack as a build pipeline. Do you have any suggestions for ember users?

**Comment by samouss** [comment]
@noslouch How the Ember App is configured? Are you using [`ember-auto-import`](https://github.com/ef4/ember-auto-import)? If yes, you can provide `DefinePlugin` to Webpack through the [`webpack`](https://github.com/ef4/ember-auto-import#customizing-build-behavior) option of `ember-auto-import`.

**Comment by noslouch** [comment]
Yeah, that’s what I ended up doing. Thanks for responding!

**Comment by oskarrough** [comment]
Also seeing this in a Svelte project using rollup.

If https://github.com/algolia/algoliasearch-client-javascript/pull/692 is reopened, we can hopefully avoid this workaround and make it "just work".

**Comment by Haroenv** [comment]
You can use https://github.com/mshick/rollup-plugin-env for example with rollup @oskarrough

**Comment by oskarrough** [comment]
@Haroenv thanks, that works for my Rollup project. But let's reopen #692 and get it fixed so you don't need extra bundlers and plugins to use this package? If I understand it correctly, the `process` var is only needed for an integration test, see https://github.com/algolia/algoliasearch-client-javascript/pull/692#discussion_r188345457.

**Comment by Haroenv** [comment]
@oskarrough, that's true, but it's not the only part which causes the problems (there's more `process` usages). Or do you mean that with only that part changed you can run it without issues?

**Comment by oskarrough** [comment]
Just tried the following, which seems to work here. The error goes away and I don't need any webpack/rollup plugins. Maybe there is a standard/better way to deal with these guards?

```js
var RESET_APP_DATA_TIMER = 60 * 2 * 1000
if (typeof window === 'undefined') {
 RESET_APP_DATA_TIMER = process.env.RESET_APP_DATA_TIMER
}
```

But another one appears, this time from autocomplete.js:

```
Uncaught ReferenceError: global is not defined
    at eval (mutation.js:5)
    at Object../node_modules/immediate/lib/mutation.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (index.js:3)
    at Object../node_modules/immediate/lib/index.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (event_emitter.js:3)
    at Object../node_modules/autocomplete.js/src/autocomplete/event_emitter.js (vendor-suffix.js:1)
    at __webpack_require__ (vendor-suffix.js:1)
    at eval (input.js:18)
```

**Comment by Haroenv** [comment]
can you share a repro project for the autocomplete issue?

**Comment by oskarrough** [comment]
Yes I can, thank you! https://github.com/internet4000/radio4000 — if you `yarn; yarn start` you should see the "process" error first. When I update it as mentioned above, the autocomplete.js "global is not defined" error appears instead.

**Comment by Haroenv** [comment]
Should it be opened in a certain branch? master branch doesn't give me the warnings

**Comment by oskarrough** [comment]
Oh my... just deleted `node_modules`, reinstalled, and now I don't have the errors anymore either. I give up haha.

**Comment by Haroenv** [comment]
sorry for this confusion, process has always been a mess. Luckily in the next version we will no longer rely on these things via env variables!

**Comment by oskarrough** [comment]
No worries, that's nice to hear!

If you do have interest, the `feat/soundcloud` branch on the repo I mentioned still has the process/globals error. Difference is algoliasearch 0.32.0 vs 0.33.0? Although I tried downgrading but errors persists so I'm back to square one.
