### ISSUE TITLE
Copy index task never resolves if source index does not exist

### ISSUE THREAD

**Issue by lenkan** [algolia/algoliasearch-client-javascript#757]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently, when calling `client.copyIndex`, followed by a `index.waitTask` and one of the specified indices does not exist, the `waitTask` promise never resolves.

**Steps to reproduce.**

I have created a gist that reproduces the behaviour: https://gist.github.com/lenkan/13bea464d3621e340bebee731bc0e72f

It is inlined here to clarify:

```javascript
const algolia = require("algoliasearch")
const client = algolia(process.env.ALGOLIA_APPID, process.env.ALGOLIA_APIKEY)

async function run() {
  const source = client.initIndex("test-index-from")
  const target = client.initIndex("test-index-to")
  const task = await client.copyIndex(source.indexName, target.indexName)
  await source.waitTask(task.taskID)
}

run().then(() => {
  console.log("Finished")
  process.exit(0)
}).catch(error => {
  console.error(error)
  process.exit(1)
})
```

Download the files to an empty directory and run 

```
npm install
ALGOLIA_APPID=<app-id> ALGOLIA_APIKEY=<api-key> npm start
```

And observe that the process never exits because `await source.waitTask(task.taskID)` never resolves or rejects.

Please note that using `target.waitTask` behaves the same way.

**What is the expected behavior?**

I expect that either `client.copyIndex` or `source.waitTask` should throw an error.

**Comment by Haroenv** [comment]
I have looked it up, and it's an issue in the API itself, which keeps saying the task is pending when the index you copied from doesn't exist. Workarounds are:

1. call setSettings({}) (a noop) to the source index first
2. do not waitTask a copy to an uninitialised index

I'll keep you updated if this gets resolved!

**Comment by Haroenv** [comment]
Just to keep this issue updated. The API team has decided that this doesn't happen often enough to warrant a (surprisingly  complex) change in the engine, and thus won't fix this. 

I will close this issue, but feel free to comment or open a new issue so I can forward the use case.
