### ISSUE TITLE
Does not work under ReactNative due to reference to window.Promise

### ISSUE THREAD

**Issue by davesag** [algolia/algoliasearch-client-javascript#758]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When my React Native component imports anything from 'react-instantsearch-native' I get

```
    ReferenceError: window is not defined

      at Object.<anonymous> (node_modules/algoliasearch/src/reactnative/builds/algoliasearch.reactnative.js:9:15)
      at Object.<anonymous> (node_modules/algoliasearch/reactnative.js:4:18)
```

See https://github.com/algolia/algoliasearch-client-javascript/blob/9a3fcdc20aeaebf7ab3eccf7bcb8bbfe3f8b636c/src/reactnative/builds/algoliasearch.reactnative.js#L9

React Native components do not have access to a `window` object. Note this does work under `expo` but `expo` is very old and we don't use it in our app. We are using `"react-native": "^0.59.8"`

**What is the expected behavior?**

React Native can just access native Javascript promises so that line is not needed.

**Comment by davesag** [comment]
May relate to #555

**Comment by Haroenv** [comment]
Does relate to #555, but that's not something we are doing within this major version, because it would be a breaking change.

The non-react-native version has this line, but instead of window it's using the implicit global. Can you try that out?

```js
import algoliasearch from 'algoliasearch/lite';
```

This is what we use in our examples, and it works.

Hope that helps!

**Comment by davesag** [comment]
I got it to work. The issue was more to do with test setup than actual running application. However the fact remains relying on `window` is not good practice.

**Comment by Haroenv** [comment]
window is defined on react native though: https://github.com/facebook/react-native/blob/master/Libraries/Core/setUpGlobals.js#L21

**Comment by Haroenv** [comment]
Which kind of errors were you getting? It would be interesting to see which setup is needed to have this failure.

**Comment by davesag** [comment]
Turned out the issue was with my test setup in Jest and not in the actual app.  The Algolia docs are very thin with regards to testing alas.

**Comment by Haroenv** [comment]
that's indeed something which is not always super obvious. My advice would be to unit test the inner components without the connectors, and also pass a fake searchClient to the InstantSearch component for full tests, that way nothing needs to be mocked.

**Comment by davesag** [comment]
The way I resolved it was as follows.

1. Created `__mocks__/algoliasearch/reactnative.js`

```js
const searchClient = jest.fn()
const algoliasearch = jest.fn(() => searchClient)

module.exports = algoliasearch
```

2. In `components/Search/SearchBox/SearchBox.test.js`

```js
import 'react-native'
import React from 'react'
import { shallow } from 'enzyme'

import SearchBox from './SearchBox'

const state = {}
const context = {
  ais: {
    widgetsManager: { registerWidget: jest.fn(() => {}) },
    onSearchParameters: jest.fn(() => {}),
    store: {
      subscribe: jest.fn(() => {}),
      getState: jest.fn(() => state)
    }
  }
}

it(
  'renders correctly', () => {
  const tree = shallow(<SearchBox currentRefinement="name" refine={() => {}}/>, { context })
  expect(tree).toMatchSnapshot()
})
```

This gets me most of the way there.  I've done the same for the `Highlight` and `InfiniteHits` components (all as per the code generated by the app creator.)

For the higher-order search wrapper yes I will mock the searchClient in more detail.
