### ISSUE TITLE
CORS not supported

### ISSUE THREAD

**Issue by nathfreder** [algolia/algoliasearch-client-javascript#763]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`algoliasearch-client-javascript` throws "CORS not supported" in the Cloudflare Workers environment

**What is the expected behavior?**
No error

**Comment by nathfreder** [comment]
It seems this issue occurs because only `window.fetch` is supported but this library doesn't use fetch.

**Comment by Haroenv** [comment]
What you can do is make your own request wrapper for fetch by overriding the default xhr one. Cc @enunomaduro, this looks like a good reason to add a fetch wrapper in v4

**Comment by nunomaduro** [comment]
@Haroenv Indeed. Thanks for the suggestion.

@nathfreder Is it clear for you on how to make your `own request wrapper`? If it is not clear, I can try to provide you a snippet for this.

**Comment by nathfreder** [comment]
@Haroenv Yeah, I’m not sure. It would be great if you could make a small snippet and I could probably pick it up from there.

**Comment by Haroenv** [comment]
https://github.com/algolia/algoliasearch-client-javascript/blob/develop/src/browser/createAlgoliasearch.js#L61-L201 this is the original XHR code, I made a rough version which works for at least the `.search` method (used by InstantSearch).

https://codesandbox.io/s/unruffled-glitter-ld9kv

This is however using internal methods, and thus might break without doing a major version, always be careful when updating :)

**Comment by nathfreder** [comment]
@Haroenv Thanks!
