### ISSUE TITLE
Error on using process.env.RESET_APP_DATA_TIMER

### ISSUE THREAD

**Issue by fender** [algolia/algoliasearch-client-javascript#764]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When running in a client-side bundle without access to `process` (e.g. packaging via Webpack with [Node globals polyfills](https://webpack.js.org/configuration/node/) turned off) there is an error.
```
ReferenceError: process is not defined
```

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**
You can set `node: false` when building any Webpack project that uses this package.

**What is the expected behavior?**
Don't assume `process` is an object. We've been able to avoid this error by passing in the following config to Webpack:
```es6
node: {
  process: 'mock',
  ...
},
```
This ensures `process` is mocked on the client-side [as such](https://github.com/webpack/node-libs-browser/blob/master/mock/process.js) but is deprecated logic.

**Comment by Haroenv** [comment]
This should be solvable by using the DefinePlugin for process instead of mocking too

**Comment by nunomaduro** [comment]
We don't plan to introduce changes on the `v3.x`, and the `v4.x` no longer contains this feature.
