### ISSUE TITLE
Check or implement timestamp as request_options for Insights API methods

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#765]
## Summary

As per documentation request, all non-`after_search` methods of the
`insights_client` must now accepts an optional timestamp as part of their
`request_options`.

We need to make sure that once psased via `request_options`, timestamp are not
ignored and correctly used within the `event` payloads that are serialized and
sent to the Insights API.

## References

 - [Documentation issue](https://github.com/algolia/algoliasearch-client-specs/issues/24)
 - [Documentation PR](https://github.com/algolia/doc/pull/3147)

**Comment by Haroenv** [comment]
Insights is not a part of algoliasearch, but of search-insights, and it has it implemented
