### ISSUE TITLE
Implement two new methods for unit testing of relevance

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#771]
- [Specs and CTS tests](https://github.com/algolia/algoliasearch-client-specs/pull/41)
- [Go client base implementation](https://github.com/algolia/algoliasearch-client-go/pull/524)

**Comment by Haroenv** [comment]
```js
search().then(res => res.hits.findIndex(({ objectID }) => objectID === 'whatever')
```

Note that the response object has no functions now, so I don't think this belongs in the JS client

**Comment by aseure** [comment]
@Haroenv agree about the easy way of doing it, but since it's a change which was requested for all API clients, we will implement it nevertheless. Same in C# for the record, the syntax is really short to do that but again, we want to stay ISO between all our clients.

I'm closing this one as it's indeed something we will want to have once @nunomaduro will have typed the response, I understand it's not possible at the moment (I've opened the ticket too fast). Thanks for noticing.
