### ISSUE TITLE
New method: GetSecuredApiKeyRemainingValidity

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-javascript#772]
## Summary

When a secured API keys expire, search breaks. The current workaround is more complex
than it needs to be. 

The options for developers using Algolia require, at every place where a search
operation is performed, catching an operation error, identify it as a
"ValidUntil" error, then regenerate the API key, and perform the search
operation again.

The idea is to define a method which tells if a `SecuredAPIKey`
is expired or not without making a single call to Algolia's API.

## References

- Specs: https://github.com/algolia/algoliasearch-client-specs-internal/pull/25

**Comment by Haroenv** [comment]
Is it an option to have a method `getSecuredApiKeyValidity(key)`, so a person can do their own calculation, and this method can be side-effect free?

**Comment by Haroenv** [comment]
Note that decoding from base64 is different in browser (`atob`) than in Node (using `Buffer`)
