### ISSUE TITLE
[4.x] Add contextual rules

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-javascript#775]
**TL;DR**: The `condition` field on rules is now optional.

Actions required:

- Update the `cts` with the information on : [#71](https://github.com/algolia/algoliasearch-client-specs-internal/pull/71/files)
- On strongly typed clients, update types in query rules, as the `condition` field in rules is now **optional**

- [Python test suite update](https://github.com/algolia/algoliasearch-client-python/pull/450/files)

**Comment by nunomaduro** [comment]
Closed as pull request as made here: https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Haroenv:patch-3.

**Comment by Haroenv** [comment]
that's not a PR yet, because it's not yet released, so can't be published yet :)

**Comment by nunomaduro** [comment]
Make the following pull request once it's opened : https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...Haroenv:patch-3.

Body of the pull request described here: https://github.com/algolia/algoliasearch-client-specs-internal/issues/42

**Comment by nunomaduro** [comment]
Done on the `v4`.
