### ISSUE TITLE
Please fix the _highlightResult type

### ISSUE THREAD

**Issue by rscotten** [algolia/algoliasearch-client-javascript#780]
Hello, I want to report a Typescript type error.

In the `index.d.ts` file, in the `HitInterface` and `LocalizedHitInterface` types, change `highlightResult` to `_highlightResult`.  

This type error has been around for at least a year.

Thanks.

**Comment by Haroenv** [comment]
Hi @rscotten, this file does not have index.d.ts, which file are you talking about? :)

**Comment by rscotten** [comment]
@Haroenv Sorry, wrong repository.  I was referring to 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/algoliasearch/index.d.ts
