### ISSUE TITLE
[4.x] Adds customNormalization 

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-javascript#797]
Please add the following parameter to `indexSettings` and the related CTS test.

Schema modification in `indexSettings`

```java
"customNormalization" : map<string, map<string,string>>
```

Example:

```java
 "customNormalization": { "default": {"ä": "ae", "ü": "ue"} }
```

**Comment by nunomaduro** [comment]
We already have this https://github.com/algolia/algoliasearch-client-javascript/blob/4ece21070cd811712503f9b69c56b9426c9b1211/packages/client-search/src/types/Settings.ts#L275.
