### ISSUE TITLE
feat: add explain decompounding at query time

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-javascript#798]
Please add the following modifications to both `query` and `searchReponse` objects

**Addition to existing JSON schemas**

Query: new optional parameter `explain` (or not new if Query Rules v2 was already implemented)

```java
{
  "explain": string[]?
}
```

SearchResponse: new `explain` response field (or not new if Query Rules v2 was already implemented)

```java
        "explain": {
            "match": {
                "alternatives": [
                    {
                        "type": string,
                        "words": string[],
                        "typos": int,
                        "offset": int,
                        "length": int
                    }
                 ]
            }
         }
```

**Comment by Haroenv** [comment]
also just for definitely typed
