### ISSUE TITLE
[3.x] Generated search only keys by other api clients causes a 403's

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-javascript#804]
On costumer support, we received an issue where the client is using the Python API Client 1.20 to generate secured api keys, and that search only api key is causing 403 in same cases.

To solve this issue, we should investigate this issue and take a decision. The ticket is: `1003224521/201029`.

**Comment by Haroenv** [comment]
can a broken api key be created for use with the latency app?

**Comment by nunomaduro** [comment]
@Haroenv Was we have discussed, normally the v3 should proxy headers to the body when the url is bigger than 500 chars. And this is the first time we received an issue about this. So I would prefer to keep this on hold until we actually have more than one customer impacted by this.

**Comment by nunomaduro** [comment]
Closing, reasons: https://github.com/algolia/algoliasearch-client-specs-internal/issues/96.
