### ISSUE TITLE
feat(API): introducing the Recommendation client

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-javascript#808]
## Context

The personalization strategy endpoint will migrate from the Search API to the Recommendation API.

The consequences of the breaking changes are:

- In `search_client` both methods `get_personalization_strategy` and `set_personalization_strategy` **must** be deprecated.
- API Clients have to introduce a new `recommendation` client.

### Endpoint

`https://recommendation.{region}.algolia.com` where region can be `us` or `eu`.

Please note that as for the current `analytics_client` the region should be
`settable` when instantiating the client.

### Route

The route will be `/1/strategies/personalization` and support the following HTTP methods `GET`, `POST`, `OPTIONS`.

- `get_personalization_strategy` -> `GET` : `/1/strategies/personalization`
- `set_personalization_strategy` -> `POST` : `/1/strategies/personalization`

### recommendation_client interface

```java
interface recommendation_client {

    function get_personalization_strategy(opts: request_options)
    return get_strategy_response

    function set_personalization_strategy(set_strategy_request: strategy, opts: request_options)
    return set_strategy_response
}
```

### Objects

```java
struct set_strategy_request {
    eventsScoring: events_scoring[]
    facetsScoring: facets_scoring[]
    personalizationImpact: int
}
```

```java
struct events_scoring {
    eventName: string
    eventType: string
    score: int
}
```

```java
struct facets_scoring {
    facetName: string
    score: int
}
```

### Responses

```java
struct get_strategy_response {
    eventsScoring: events_scoring[]
    facetsScoring: facets_scoring[]
    personalizationImpact: int
}
```

```java
struct set_strategy_response {
    status: int
    message: string
}
```

For more details regarding the implementation please see the [specfication PR.](https://github.com/algolia/algoliasearch-client-specs-internal/pull/90)

**Comment by nunomaduro** [comment]
We don't plan to change things on the `v3.x`. And this is done on the `v4.x`.
