### ISSUE TITLE
Add TS type definition file to this package

### ISSUE THREAD

**Issue by rscotten** [algolia/algoliasearch-client-javascript#837]
Hello Algolia Search package owners,

`@types/algoliasearch` contributor here.  I want to make a type fix, but wanted to bring this issue up first.

Can we make the TS type definition file part of this `algoliasearch` package rather than a separate one with `@types/algoliasearch`?  

The `@types/*` package is getting out of hand with thousands (6,200+!!!) type definition files. 
 It's slow and clunky to fork the entire `DefinitelyTyped/DefinitelyTyped` repo just to make a minor type fix.  And it's more elegant to keep everything in one package rather than requiring two.

Thoughts?

**Comment by nunomaduro** [comment]
We are working on the next major version here, and the beta version will be out tomorrow. This new major version is entirely typed: https://github.com/algolia/algoliasearch-client-javascript/pull/836.

**Comment by rscotten** [comment]
@nunomaduro Amazing!  Yes, please ping me.  Thanks!
