### ISSUE TITLE
[BUG] partialUpdateObject does not create objectID for unknown record

### ISSUE THREAD

**Issue by agdavid** [algolia/algoliasearch-client-javascript#850]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**
- v 3.35.1
- Use `partialUpdateObject` on a non-existing record
- Either rely on default of `createIfNotExists:true` or explicitly add `true`
- ObjectID is `undefined`

```
// command
index.partialUpdateObject({
  data: 'without object ID'
}, true, (err, content) => {
  if (err) throw err;

  console.log(content);
});

// result
{ updatedAt: '2019-12-04T19:51:01.914Z',
  taskID: 85525863340,
  objectID: 'undefined' }
```

**What is the expected behavior?**
- Use `partialUpdateObject` on a non-existing record
- Documentation says the default is `createIfNotExists: true`
- For a non-existing/unknown object, this should generate the objectID

HS reference: https://secure.helpscout.net/conversation/1023698988/212110?folderId=1106367

**Comment by Haroenv** [comment]
Hmm, I think create if not exists implies you send an objectID, but will create it if that object doesn’t yet exist

**Comment by nunomaduro** [comment]
We don't plan to change things on the `v3.x`. And this is fixed on the `v4.x`.
