### ISSUE TITLE
empty set settings

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-javascript#852]
In the beta of the new major version:

Doing `index.setSettings({})` is resulting in "No content in PUT request"
This is working in the current version

**Comment by nunomaduro** [comment]
Thanks for reporting this issue. Before we tackle this, it’s important to understand if the behavior as correct from the first place.

@chloelbn can you give a quick test on the php client? Sending a empty set settings?

**Comment by chloelbn** [comment]
The PHP client returns "No content in PUT request" as well when `$index->setSettings([])` is sent

**Comment by nunomaduro** [comment]
Thanks @chloelbn. @maxiloc I think it makes sense, If the previous client allowed to do that, looks like it may be a breaking change for this new one. Sorry.

**Comment by maxiloc** [comment]
I think we should reconsider that (not only for the js client).

This is the cleanest way to create an index without doing hacks and/or putting "dumb" data into the index/settings.

I would suggest to either allow this or create a new method `createIndex`. That being said I find this option to be weird since you'll have to call the setSettings endpoint anyway.

**Comment by maxiloc** [comment]
Actually after looking for an alternative I don't see any other way to create an index that will in 100% of the case not mess up the index if it existed.

In other words: to create an index you need to do a write operation and as far as I know `setSettings({})` is the only way not to modify the state of the index (in case it existed already).

**Comment by nunomaduro** [comment]
@maxiloc Thanks to https://github.com/algolia/algoliasearch-client-javascript/commit/cca2dd32f1bfaa1dfd29ee810680c754fbfd6e38. You should be able to do:

```
await index.setSettings({});
```
