### ISSUE TITLE
Handle `autoGenerateObjectIDIfNotExist` parameter for `replaceAllObjects()` method

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-javascript#876]
The `autoGenerateObjectIDIfNotExist` boolean parameter is for now only valid in
the context of the `saveObjects()` method. As pointed out by @julienpa, it would
make sense to also accepts it as a valid parameter of `replaceAllObjects()`.

For backward-compatiblity, let's make sure the default behavior of calling
`replaceAllObjects()` without the `autoGenerateObjectIDIfNotExist` parameter is
still considered as if it was set to `false`.

**Comment by nunomaduro** [comment]
Done in `v4`.
