### ISSUE TITLE
Inline '../..' imports in npm package cause build errors when importing client-search (beta)

### ISSUE THREAD

**Issue by idpaterson** [algolia/algoliasearch-client-javascript#931]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The npm package for @algolia/client-search (at time of writing, 4.0.0-beta.12) includes several inline imports `import("../..").AddApiKeyOptions` in `dist/client-search.d.ts` that can error out while building TypeScript projects that require @algolia/client-search.

**If the current behavior is a bug, please provide all the steps to reproduce and a minimal
[JSFiddle](https://jsfiddle.net/) example or a repository on GitHub that we can `npm install`
and `npm start`.**

[Gist](https://gist.github.com/idpaterson/78de28d4f067d494bc95ce9f570bed80) showing this issue.

```
> npm start
node_modules/@algolia/client-search/dist/client-search.d.ts:508:126 - error TS2307: Cannot find module '../..'.

508 export declare const getObject: (base: SearchIndex) => <TObject>(objectID: string, requestOptions?: (RequestOptions & import("../..").GetObjectsOptions) | undefined) => Readonly<Promise<TObject & ObjectWithObjectID>>;
                                                                                                                                 ~~~~~~~

node_modules/@algolia/client-search/dist/client-search.d.ts:908:169 - error TS2307: Cannot find module '../..'.

908 export declare const saveRule: (base: SearchIndex) => (rule: Rule, requestOptions?: (RequestOptions & SaveRulesOptions) | undefined) => Readonly<WaitablePromise<import("../..").SaveRulesResponse>>;
                                                                                                                                                                            ~~~~~~~

node_modules/@algolia/client-search/dist/client-search.d.ts:936:181 - error TS2307: Cannot find module '../..'.

936 export declare const saveSynonym: (base: SearchIndex) => (synonym: Synonym, requestOptions?: (RequestOptions & SaveSynonymsOptions) | undefined) => Readonly<WaitablePromise<import("../..").SaveSynonymsResponse>>;
                                                                                                                                                                                        ~~~~~~~

node_modules/@algolia/client-search/dist/client-search.d.ts:1773:102 - error TS2307: Cannot find module '../..'.

1773 export declare const updateApiKey: (base: SearchClient) => (apiKey: string, requestOptions?: (import("../..").AddApiKeyOptions & Pick<RequestOptions, string | number>) | undefined) => Readonly<WaitablePromise<UpdateApiKeyResponse>>;
                                                                                                          ~~~~~~~


Found 4 errors.
```

**What is the expected behavior?**

The project should compile successfully with `npm start`.

We have been using a postinstall script to remove the `import("../..").` as all symbols are available in the .d.ts. This gets hairy when our private module that requires @algolia/client-search is installed, but it has worked for now. This is of course not being used in production, but first-party Algolia typing was a tantalizing addition while working toward our next major release! 🤘

**Comment by nunomaduro** [comment]
Thanks for reporting this issue. Got fixed on the `beta-13`.

Glad that you are testing out the next version of our client. Do have any other feedback for us?

**Comment by idpaterson** [comment]
Currently we are using only the typings, haven't updated any runtime code to the beta yet. It is a much better experience than @types/algoliasearch, which was often too inaccurate to use directly. Kudos! 

I can open a separate issue, but the only other problem I have noticed is the typing of `optionalFilters` does not allow mixed strings and arrays. The example shown in the docs for `optionalFilters` does not work since the typing allows only an array of strings or array of string arrays:
```
optionalFilters: [
  'attribute:value',
  ['attribute1:value', 'attribute2:value'],
]
```

**Comment by nunomaduro** [comment]
Fixed: https://github.com/algolia/algoliasearch-client-javascript/commit/d493ef8c26b1eaea4069547f9f6439eaef03bd56.

Thanks!
